### ISSUE TITLE
Attaching MEI incipits to sources

### ISSUE THREAD

**Issue by lpugin** [rism-ch/muscat#1001]
We currently have some MEI incipits files that needs to be made available and attached to their corresponding source incipits. 

At this stage, we do not plan to have incipits uploaded by the users because encoding format and validity needs to be checked. This is not likely to change soon, so it is safe to go for a solution that works essentially through command-line imports.

At this stage, we are planning to have MEI files corresponding to incipits. However, it is not unlikely that we will want to have MEI files attached to a source - e.g., when a full transcription is available.

### Store MEI files as Digital Object in Muscat

A logical option is to use the Digital Object structure in Muscat. For incipits, they would be uploaded only from the command-line. This means we can control filenames and titles.

Digital Objects are attached to other resources (Sources, Persons). They are not stored in the Marc but only added to the Marc records in the export. For the export to the OPAC, a note field 500 is added.  

We could do something similar for incipits. However, 856 would probably be more appropriate. For MEI files pointing to incipits, we could also use 031$u. To do so, we need to have pattern in place either in the filename or in the title of the Digital Objects.

 ### Store MEI files outside Muscat

Another option is to make the MEI files available somewhere else. Then the import would mean modifying the Marc records in Muscat, which can be either adding 856 for source related MEI files or 031 $u for incipits related ones.

## Open questions

1. Is it preferable to store MEI files as Digital Objects or not?
2. If yes, what is the best way to store the reference to an incipit (in addition to the reference to the source given by the standard DO / Source linkage)? Through filename structure (e.g., 440100876_1.2.2), or through the title? Other ideas?
3. Is it OK to use 031$u to refer to MEI incipit files?

**Comment by lpugin** [comment]
## Decision

* Store them as Digital Objects
* Use 031 $u for references to external incipits (see #1003) to be added in to_external

## Remaining question

* See if it is possible to add columns to PaperClip / ActiveStorage
  * to store incipit number.
  * to store infomation that the XML file is MEI (there is currently not mime type for MEI)

**Comment by xhero** [comment]
The functionality was implemented using PaperClip and stored in the FS, with a type specifier on the DB table. $u is added on export
