### ISSUE TITLE
Clean up drop-down list of source types

### ISSUE THREAD

**Issue by BaMikusi** [rism-ch/muscat#1005]
When searching among the sources the box "Source type" offers a series of random combinations (Ms, Ms., Ms. autogr, Ms. autogr. etc. etc.) that produce zero hits -- could we get rid of these?

**Comment by xhero** [comment]
I reindexed Muscat Saturday
<img width="329" alt="Schermata 2020-10-12 alle 14 40 32" src="https://user-images.githubusercontent.com/1691778/95747627-0a768080-0c99-11eb-91e7-659df56ce540.png">
 night, can somebody confirm we have the right elements in the popup?

**Comment by jenniferward** [comment]
Yes, they are as correct as they can be.
The duplicate "Autograph" and "Probably autograph" will get taken care of with #1006. 
The duplicate "Autograph manuscript," "Manuscript copy", and "Partial autograph" were from a handful of imported Italian records, which I corrected (so the next time you re-index, those will also be dropped).
