### ISSUE TITLE
Remove "Search Sources" box in authorities?

### ISSUE THREAD

**Issue by jenniferward** [rism-ch/muscat#1009]
I just noticed that there is a "Search sources" box in some authorities, but it does not work. Is there a reason to keep it?

![image](https://user-images.githubusercontent.com/18663291/96112275-aa731a80-0ee2-11eb-861a-8b03c8942020.png)

https://muscat.rism.info/admin/standard_terms/25215

Found in Liturgical festivals, Places, Subject headings, Titles/text incipits. It would be useful in theory, but then it should probably also be available for the other authorities as well.

**Comment by xhero** [comment]
This functionality is currently unsupported in Muscat, I'm removing the boxes. If we need to search in the embedded lists we can have an ad-hoc project.
