### ISSUE TITLE
Fixing autocomplete display in editor

### ISSUE THREAD

**Issue by lpugin** [rism-ch/muscat#101]
The format should be
Institution: Siglum – Name and location (For 852)
Institution: Name and location (For 110)
Source: ID – Name, First name: Standardized title
Person: Name, First name (xxxx-xxxx)
Catalogue: Abbreviation – Name, First name: Title…

Can be moved to 3.0.1-0 if necessary

**Comment by lpugin** [comment]
Is this all good?

**Comment by lpugin** [comment]
OK, I hope it is good enough to start with. But it seems to me we need to look at the autocomplete lookup more precisely. I have the impression the filtering is too drastic and I find it difficult to find some values. For example, in the institution fields (110 or 710) we should also be able to search by RISM Sigla or by words other that the starting one.

Example: I can't find "Schweizerische Nationalbibliothek [CH-BEl]" by entering "Nation" o "CH-BEl" or "BEl". This is a high priority

**Comment by xhero** [comment]
Searches now only work with the beginning of words. We can do them for substrings too, but won't we have many many false positives?=

**Comment by xhero** [comment]
Sorry I mean of strings, it is a LIKE xxx% in the autocomplete code. Didn't we do LILE %xx% in muscat 2? Maybe we could use mysql fulltext which is similar to solr.=

**Comment by lpugin** [comment]
It works on beginning of fields. It should work on beginning of words.
Can't we use regex for this?

Substring (anywhere) might be a problem. But words should be the best. If
you don't know if the how is named "Schweizerische Nationalbibliothek" (it
could be National library of Switzerland, or Swiss national library, etc),
then it is particularly difficult to find.

**Comment by lpugin** [comment]
We used REGEXP in CW, but I can't remember where. Something like

SELECT * FROM institutions i WHERE name REGEXP '.*[[:<:]]Natio.*[[:>:]].*'

From my experience this is not as efficient as indexing but could be acceptable for autocomplete

**Comment by xhero** [comment]
This is fixed in testing, when you have tried it we can update prod.

**Comment by lpugin** [comment]
Yes, this looks good for being put in production
