### ISSUE TITLE
Some keys in translations need to be quoted

### ISSUE THREAD

**Issue by ahankinson** [rism-ch/muscat#1011]
The value of `No` in YAML evaluates to `False` by default, which means that the literal value of "No" is not imported. 

Instances of `No` should be quoted, `"No"`. 

e.g., https://github.com/rism-ch/muscat/blob/develop/config/editor_profiles/default/configurations/SourceLabels.yml#L1376

**Comment by HirschSt** [comment]
Since IMO every value is a string, maybe all values should be quoted - this "No" case is very tricky.

**Comment by ahankinson** [comment]
The underlying problem will be fixed as part of #1004, but the one instance where this occurred caused a problem with the migration to this mechanism, so I put in the PR for it.

I reviewed all the other translation files, and it only happened once.

**Comment by xhero** [comment]
Nice catch, I've never noticed this.
