### ISSUE TITLE
Muscat URL

### ISSUE THREAD

**Issue by jenniferward** [rism-ch/muscat#1015]
When you are logged into Muscat and you open up https://muscat.rism.info again (like to work in multiple tabs) then it defaults to https://muscat.rism.info/catalog . I think most people want the Sources view. Can it default to that (or the dashboard)?

https://muscat-training.rism.info/ as well - landing on the faceted search page is confusing to new users.

**Comment by xhero** [comment]
Done, it is a configuration option
