### ISSUE TITLE
Add countries to institutions

### ISSUE THREAD

**Issue by HirschSt** [rism-ch/muscat#1024]
same as https://github.com/rism-international/tasks/issues/905

Bitte ergänze folgende Länder:

Andorra (ISO-Code 3166-1: XA-AD)
Indonesia (ISO-Code 3166-1: XB-ID)
Northern Ireland (ISO-Code 3166-2: XA-GB-NIR)
Monaco (ISO-Code 3166-1: XA-MC)
Philippines (ISO-Code 3166-1: XB-PH)
Saudi Arabia (ISO-Code 3166-1: XB-SA)
Hong Kong (ISO-Code 3166-1: XB-HK)
Taiwan (ISO-Code 3166-2: XB-TW)
Papua New Guinea (ISO-Code 3166-1: XE-PG)
Danke,
Guido

**Comment by ahankinson** [comment]
Thanks @HirschSt !  

Are there translations available as well for these countries?

**Comment by HirschSt** [comment]
German:

Andorra (ISO-Code 3166-1: XA-AD)
Indonesien (ISO-Code 3166-1: XB-ID)
Nordirland (ISO-Code 3166-2: XA-GB-NIR)
Monaco (ISO-Code 3166-1: XA-MC)
Philippinen (ISO-Code 3166-1: XB-PH)
Saudi-Arabien (ISO-Code 3166-1: XB-SA)
Hongkong (ISO-Code 3166-1: XB-HK)
Republik China (Taiwan) (ISO-Code 3166-2: XB-TW)
Papua-Neuguinea (ISO-Code 3166-1: XE-PG)

**Comment by ahankinson** [comment]
These have been added to the new translations system (#1026) so will go live when that gets merged and deployed.
