### ISSUE TITLE
Search for stray HTML code

### ISSUE THREAD

**Issue by jenniferward** [rism-ch/muscat#1025]
I am wondering about cleaning up stray HTML code that is lurking in the data. I only find it by chance (current example: & otilde ; )
https://muscat.rism.info/admin/sources/135067
![image](https://user-images.githubusercontent.com/18663291/98940851-e900f280-24eb-11eb-92a5-2cceedfb44a5.png)

It is displayed fine in the OPAC, but with all the data reuse, it might be better to replace it with unicode. Maybe a script can search for it?

**Comment by fjorba** [comment]
I've found 83, and only in sources, not in any other record type, from October extract file.

```
$ awk '$1 == "001" { recid = $NF+0 } /&[A-Za-z]+;/ && !/http/ { print recid, $0 }' sources.marc21 >sources-html-entities.txt
```

As there are just this few, and some of them require manual decision, probably it woud be better to correct them by hand.  I attach them in this file:

[sources-html-entities.txt](https://github.com/rism-ch/muscat/files/5572443/sources-html-entities.txt)

**Comment by jenniferward** [comment]
Thank you very much for finding those, @fjorba ! I will fix them.
