### ISSUE TITLE
Export of folder only returning sources

### ISSUE THREAD

**Issue by HirschSt** [rism-ch/muscat#1029]
probably https://github.com/rism-ch/muscat/blob/1839b27ee93d82b3f89c9fd3aa00f899fd82f638/app/jobs/export_records_job.rb#L100

**Comment by HirschSt** [comment]
Ok, I see that marc2csv only fits to sources just now

**Comment by xhero** [comment]
Yes the export for the moment was meant to be used only for sources so we could experiment with it, if we have the necessity we can add other models too.

**Comment by HirschSt** [comment]
Thats ok with me, but then we should drop the export action from the sidebar
