### ISSUE TITLE
Standardize form of "unknown" siglum

### ISSUE THREAD

**Issue by ahankinson** [rism-ch/muscat#1046]
Currently the form of the "unknown" institution siglum is "N. N.", which is used to indicate "Nomen nominandum". 

This siglum does not follow the standards for the form of siglum, from the guidelines for 110$g:

"Library sigla are made up of three elements: a country abbreviation, a city abbreviation, and an institution abbreviation. In some cases, the institution abbreviation may be omitted (example: D-B). The abbreviations for the country and city are always capitalized and the abbreviation for the institution is always lowercase.  The country code is separated from the other details by a hyphen.  The code for the country is almost always taken from the list of international vehicle registration codes maintained by the United Nations. City and institution codes are created by the RISM Editorial Center."

At the moment, only a single source is assigned to this institution, to indicate a record that has been previously catalogued, but subsequently sold to an unknown buyer.

The proposal is to adjust the siglum for this institution to "XX-Nn", where "XX" indicates an unknown country (following the MARC21 and ISO-3166-1 forms for unknown countries; the International Vehicle Registration codes do not have a suggestion for unknown country). The "Nn" city and institution codes follow the precedent set to indicate "Nomen nominandum".

**Comment by xhero** [comment]
We can change the source to XX-NN (all capitals), @Docudoctor can you do this please? I leave it up to you if you want to rename the institution or create a new one (it seems to be used only for this source).

**Comment by Docudoctor** [comment]
Changed into XX-NN. 
Best,
Guido
