### ISSUE TITLE
Faceted search links to "Publications"

### ISSUE THREAD

**Issue by jenniferward** [rism-ch/muscat#1057]
I think this is a bug: When you are in the Faceted Search and looking at a record, the "Edit" button in the upper right corner leads to the Publications (Secondary Literature), and of course the record is not found.

Example: https://muscat.rism.info/catalog/1001058746, Edit, which links to https://muscat.rism.info/admin/publications/1001058746/edit

**Comment by fjorba** [comment]
May it be related to #977?

**Comment by fjorba** [comment]
Yes, it was me, sorry. I've confirmed in one of my local Muscat installations. Fixed in #1059
