### ISSUE TITLE
Custom action should depend on user capabilities

### ISSUE THREAD

**Issue by lpugin** [rism-ch/muscat#106]
Currently, any user can perform a batch delete on a selection...

**Comment by xhero** [comment]
Which users did you try this on? only editors can mass-delete, cataloguers cannot. Should this be available only to admins?

**Comment by lpugin** [comment]
Yes, make it admin only for now

**Comment by xhero** [comment]
Ok I have to see if it doable as it is based on the generic :destrpy permission

> Il giorno 27/gen/2015, alle ore 10:35, Laurent Pugin <notifications@github.com> ha scritto:
> 
> Yes, make it admin only for now
> 
> —
> Reply to this email directly or view it on GitHub.
> 

-- 
Io, Liberace, Imperatore del kitsch, Gran Visir della porchetta in Musica, col potere del sacro candelabro, ti nomino Baronetto dell'Ordine delle Note Fritte.
[Liberace da Allevi - http://www.joshuaheld.com/All/all.html]
