### ISSUE TITLE
Search not retrieving expected results

### ISSUE THREAD

**Issue by lpugin** [rism-ch/muscat#116]
Searching for "Musikalien Einzelerwerbungen" in any field does not find
See 852 $z (collection) in http://admin.rism-ch.org/sources/409002015

**Comment by xhero** [comment]
This is pretty strange. If you set a composer filter to "Burkhard" and search "Einzelerwerbungen" you get two records, but 0 with "Musikalien - Einzelerwerbungen" or "Musikalien"
In the same way if you search for "Schweizerische Nationalbibliothek" you get 0 results, and 0 with "Schweizerische", but you find the record with only "Nationalbibliothek".
If you look at the token info in solr it is there, could be a problem in the search commands we use?=

**Comment by lpugin** [comment]
Yes. On my machine I get nothing when searching "Einzelerwerbungen" alone...

**Comment by lpugin** [comment]
OK, in 409002015 it seems that "Einzelerwerbungen" was added today, so this at least explains why I have no results

**Comment by lpugin** [comment]
OK, since it is reindexing I am already closing it
