### ISSUE TITLE
New entries from source in 740 not saved

### ISSUE THREAD

**Issue by lpugin** [rism-ch/muscat#117]
When creating a new standard title from 740, the text is saved in the source but not added to the standard title. (This works with 130 and 730.)

When fixing this, we also need to check that the 740 value in all new titles (410) are in standard_titles

**Comment by xhero** [comment]
We experimented with the autocomplete for this, or we need to modify marc import to make this work.

**Comment by xhero** [comment]
This is fixed in testing, we use the solr index for autocomplete. If it is ok we can move it in prod

**Comment by xhero** [comment]
Fixed in production.
