### ISSUE TITLE
Date should be single date by default

### ISSUE THREAD

**Issue by lpugin** [rism-ch/muscat#122]
In 033, it seems that we still have data range by default in the editor (even though changing it to single date and saving now works).

**Comment by xhero** [comment]
It STILL does not work?



<div>-------- Messaggio originale --------</div><div>Da: Laurent Pugin <notifications@github.com> </div><div>Data:05/03/2015  16:06  (GMT+01:00) </div><div>A: rism-ch/muscat <muscat@noreply.github.com> </div><div>Cc: xhero <rwz@xhero.org> </div><div>Oggetto: Re: [muscat] Date should be single date by default (#122) </div><div>
</div>Assigned #122 to @xhero.

**Comment by lpugin** [comment]
Nope, but I think what was fixed is the saving side. This is just the
default selection...
