### ISSUE TITLE
740 indexing and input to be clarified

### ISSUE THREAD

**Issue by lpugin** [rism-ch/muscat#127]
What we quite likely need is:
- Indexing 740 but also 130, 240 and 730
- Make it an open list (not having to click the unlock button to add an non existing value)

To be discussed (assigned to @cgueggi for this)

**Comment by cgueggi** [comment]
In my opinion 130/240/730 should stay authority files. Only 740 (text) needs no unlock button. To discuss tomorrow.

**Comment by lpugin** [comment]
Sorry, this was misleading. What I meant that only 740 should be list-based
(as opposed to authority-based) without unlock, but that the content of the
list should be gathered from 130, 240, 730 and 740 fields.

**Comment by xhero** [comment]
Ok I am not sure how easy it will be to have an open list there, I think we will need some re-engeneering of the code.

**Comment by xhero** [comment]
Fixed in testing, need to be moved to production when tests are done. I am closing this as it is basically the same as #117.
