### ISSUE TITLE
Autocomplete for titles must search only at the beginning

### ISSUE THREAD

**Issue by lpugin** [rism-ch/muscat#128]
This is for 130, 240 and 730. We should not use REGEXP here (or change the REGEXP to search only an the beginning of the string.

Otherwise single work title do not appear in the result list and cannot be selected (ex: Weisheit)

**Comment by xhero** [comment]
Which are the fields that we want to switch to SOLR? In this case the autocomplete will always start at the beginning of the string.

**Comment by xhero** [comment]
This should be fixed with the new release of the autocomplete, does it work as it should?

**Comment by lpugin** [comment]
@cgueggi ?

**Comment by cgueggi** [comment]
Just discussed oraly with @xhero.

**Comment by xhero** [comment]
We need to discuss the requests, which require a bit of reengineering
* word boundaries instead of beginning
* case insensitive
for both we need to switch to regex

**Comment by lpugin** [comment]
@cgueggi : where do we stand with this?

**Comment by cgueggi** [comment]
130, 240, 730 are perfect now. I think 100 (and 600 if needed in future) should also search at the beginning.

**Comment by lpugin** [comment]
This will be solved with the new select option
