### ISSUE TITLE
Checkbox "Dubious" (100$j) not working

### ISSUE THREAD

**Issue by lpugin** [rism-ch/muscat#130]
I can tick it, but as soon as I save the entry it disappears. For example in title: 410000982

**Comment by lpugin** [comment]
Apparently it is (sometimes?) checked by default. See http://admin.rism-ch.org/sources/406003247

**Comment by xhero** [comment]
But this is correct, the marc has the Attributed to tag:
=100  1#$0143618$jAttributed to$aVranický, Pavel$d1756-1808

so the problem is that is was not checked but after saving is becomes checked?

**Comment by xhero** [comment]
Indeed it does. I cannot figure out why it does not do it in testing.

**Comment by lpugin** [comment]
Which means we need a quick fix. And an new release...

**Comment by xhero** [comment]
Did this thing ever work? I can see what I can do

**Comment by lpugin** [comment]
Yes, I think it did

**Comment by lpugin** [comment]
@xhero : we need to double check this

**Comment by xhero** [comment]
It creates a "$jAttributed to" and it seems to remain checked on reload. There is a fix for this in marc_json. I think we can close
