### ISSUE TITLE
Title crashing

### ISSUE THREAD

**Issue by lpugin** [rism-ch/muscat#131]
http://admin.rism-ch.org/sources/406000829

**Comment by xhero** [comment]
This is the error that crashes it:
Tag 690: missing master (expected in $0), tag contents: =690  #7$nBVW, 244

is this a new record or an old one?

**Comment by lpugin** [comment]
This is an old title

**Comment by lpugin** [comment]
http://www.rism-ch.org/manuscripts/406000829

**Comment by xhero** [comment]
It is part of those titles that do not reindex because the $0 is missing, there should be a ticket for this and/or a list of sources.
