### ISSUE TITLE
search history crashing

### ISSUE THREAD

**Issue by lpugin** [rism-ch/muscat#145]
I, [2015-06-10T14:27:49.386853 #18611]  INFO -- : Started GET "/search_history" for 144.85.170.215 at 2015-06-10 14:27:49 +0200
I, [2015-06-10T14:27:49.389311 #18611]  INFO -- : Processing by SearchHistoryController#index as HTML
I, [2015-06-10T14:27:49.590692 #18611]  INFO -- :   Rendered search_history/index.html.erb within layouts/blacklight (198.4ms)
I, [2015-06-10T14:27:49.591378 #18611]  INFO -- : Completed 500 Internal Server Error in 202ms (ActiveRecord: 0.2ms)
F, [2015-06-10T14:27:49.593530 #18611] FATAL -- : 
ActionView::Template::Error (undefined method `+' for :filter_composer:Symbol):
     7:   <table class="table table-striped search_history">
     8:     <%-  @searches.each_with_index do |search,index| -%>
     9:     <%= content_tag :tr, :id => "document_#{index + 1}" do %>
    10:       <td class="query"><%= link_to_previous_search(search.query_params) %></td>
    11:     <% end #content_tag %>
    12:   <%- end -%>
    13:   </table>
  app/views/search_history/index.html.erb:10:in `block (2 levels) in _app_views_search_history_index_html_erb__4141543245073550855_70220442347840'
  app/views/search_history/index.html.erb:9:in `block in _app_views_search_history_index_html_erb__4141543245073550855_70220442347840'
  app/views/search_history/index.html.erb:8:in `_app_views_search_history_index_html_erb__4141543245073550855_70220442347840'

**Comment by xhero** [comment]
It is a bit easier for me if you give me some more details: on which machine is this? 233 or local? Did you search anything in particular before opening the page? Search history work for me both locally and 233.

**Comment by lpugin** [comment]
This is on 233. But it works on my local machine. I'll try to look at what is in my history

**Comment by lpugin** [comment]
Fixed by dropping session. We need to keep an eye on it
