### ISSUE TITLE
Grace notes in Incipit should be "crossed out"

### ISSUE THREAD

**Issue by cgueggi** [rism-ch/muscat#148]
Sorry, I'm not sure if you understand. I hope the following pic will be shown in github. See the first note.

![grace-palette](https://cloud.githubusercontent.com/assets/9051725/8454954/5d92e0ea-2001-11e5-8cf3-ea95175916fb.png)

**Comment by xhero** [comment]
You mean accuaccaturas only or all graces?

**Comment by cgueggi** [comment]
I'm not sure what the difference exactly is. I mean the code written with "g". F. e.: "gFgGgA" (three grace notes)

**Comment by lpugin** [comment]
Reported in Verovio https://github.com/rism-ch/verovio/issues/107

**Comment by lpugin** [comment]
Fixed in Verovio, will be available in next update of it.
