### ISSUE TITLE
Entry can't be saved

### ISSUE THREAD

**Issue by cgueggi** [rism-ch/muscat#149]
Following message appears: Error saving page! Page will be reloaded. (error Internal Server Error

**Comment by xhero** [comment]
Is it an existing entry or a new one? On 233?

<div>-------- Messaggio originale --------</div><div>Da: cgueggi <notifications@github.com> </div><div>Data:01/07/2015  15:04  (GMT+01:00) </div><div>A: rism-ch/muscat <muscat@noreply.github.com> </div><div>Oggetto: [muscat] Entry can't be saved (#149) </div><div>
</div>Following message appears: Error saving page! Page will be reloaded. (error Internal Server Error

**Comment by cgueggi** [comment]
New one on http://129.194.18.233/admin/
Testing it now

**Comment by xhero** [comment]
Can you give me the basic data you are entering? I tried a bogus one earlier and it saved, so I want to test it with real data 

<div>-------- Messaggio originale --------</div><div>Da: cgueggi <notifications@github.com> </div><div>Data:01/07/2015  15:23  (GMT+01:00) </div><div>A: rism-ch/muscat <muscat@noreply.github.com> </div><div>Cc: xhero <rwz@xhero.org> </div><div>Oggetto: Re: [muscat] Entry can't be saved (#149) </div><div>
</div>New one on http://129.194.18.233/admin/
Testing it now

**Comment by cgueggi** [comment]
This were the basic data: http://admin.rism-ch.org/sources/410001103

**Comment by cgueggi** [comment]
http://129.194.18.233/admin/sources/410001043/edit

**Comment by lpugin** [comment]
Try to add "Weber, Joseph Georg" in 100 and save. It seems to crash consistently

**Comment by xhero** [comment]
Got it: Weber (30043201) has a malformed 670 (misses $0), so when it saves and loads the person data, it crashes. I can fix the data (add $0) but I see no easy way around malformed marc data blocking marc load. Any ideas?

This is the error (for the person):
Tag 670: missing master (expected in $0), tag contents: =670  ##$aKamber, Peter: Zentral- und Hochschulbibliothek Luzern, in: Handbuch der historischen BuchbestÃ¤nde in der Schweiz. Zentralbibliothek ZÃ¼rich (Hrsg.), ZÃ¼rich 2011, S. 93

**Comment by lpugin** [comment]
I think we should change the marc config and remove $0 since this is not valid marc. We should see this with Stephan. Can you try it?

**Comment by xhero** [comment]
you mean from the Person record? yes I will do is asap

**Comment by lpugin** [comment]
Yes
