### ISSUE TITLE
Migrating to $8

### ISSUE THREAD

**Issue by lpugin** [rism-ch/muscat#159]
* Migrate all fields with $3 to $8
* Value should be "01" instead of "Material 1"
* Add a $801 to all fields for records with only one material group (currently no $3)
* Add a $8 to 028 (including in MarcConfig); the value should be the one of the print material group (if only one)
* List all records with more than one print material and a 028 that needs to be matched my hand

**Comment by xhero** [comment]
Implemented into migration script
