### ISSUE TITLE
create_admin_users.rb is missing from the housekeeping folder

### ISSUE THREAD

**Issue by ahankinson** [rism-ch/muscat#160]
The installation instructions give the following command to create the first user:

```
cd housekeeping/admin
ruby create_admin_users.rb -a --username USER --password PASS --email EMAIL
```

However, this script is not present in the 3.2.0 branch (or any other branch for that matter). 

How do you create the initial users?

**Comment by lpugin** [comment]
The documentation is outdated. Could you try
```
rake db:seed
```

**Comment by ahankinson** [comment]
Running `rake db:seed` results in `ActiveRecord::RecordInvalid: Validation failed: Email has already been taken`. However, doing some digging I found out that ActiveAdmin adds an admin user by default: admin@example.org, password: password
