### ISSUE TITLE
Fix action for the new sidebar links

### ISSUE THREAD

**Issue by lpugin** [rism-ch/muscat#165]
Save_and_continue, save_and_exit and cancel in app/views/editor/_section_sidebar.html.erb needs to be properly set

**Comment by lpugin** [comment]
Save and continue says "Error saving page: this is a stale version"

**Comment by lpugin** [comment]
Cancel raises a JS error "Uncaught ReferenceError: marc_editor_redirect is not defined"

**Comment by xhero** [comment]
I know, cancel is not implemented yet

**Comment by xhero** [comment]
Save and c. works for me: it is the same as before

**Comment by lpugin** [comment]
Looks good
