### ISSUE TITLE
rake db:seed tries to create an existing user

### ISSUE THREAD

**Issue by ahankinson** [rism-ch/muscat#171]
The `rake db:seed` command attempts to create an admin user, but this user is already created in the migration stage. 

The solution (I think) is to comment out the user creation in the migration and leave it in the seed. I have a fix pending.

See:
https://github.com/rism-ch/muscat/blob/master/db/migrate/20140331105619_devise_create_users.rb#L5

https://github.com/rism-ch/muscat/blob/master/db/seeds.rb#L12

**Comment by xhero** [comment]
I think the problem is that rarely we actually install muscat without data, so probably no one used db:seed in ages. I agree that it is better moved out to the seed.
