### ISSUE TITLE
ActiveSupport::Concern Exception with rake:reindex from Blacklight

### ISSUE THREAD

**Issue by HirschSt** [rism-ch/muscat#177]
Fresh install of 3.3.0-devel I get an ActiveSupport::Concern Exception starting reindexing the set:

dev@lab:~/projects/muscat$ rake sunspot:reindex
DEPRECATION WARNING: Configuration is now done via blacklight.yml. Suppport for solr.yml will be removed in blacklight 6.0.0. (called from connection_config at /home/dev/.rvm/gems/ruby-1.9.3-p545/gems/blacklight-5.16.3/lib/blacklight.rb:62)
DEPRECATION WARNING: Configuration is now done via blacklight.yml. Suppport for solr.yml will be removed in blacklight 6.0.0. (called from connection_config at /home/dev/.rvm/gems/ruby-1.9.3-p545/gems/blacklight-5.16.3/lib/blacklight.rb:63)
rake aborted!
ActiveSupport::Concern::MultipleIncludedBlocks: Cannot define multiple 'included' blocks for a Concern
/home/dev/.rvm/gems/ruby-1.9.3-p545/gems/activesupport-4.1.13/lib/active_support/concern.rb:126:in `included'
/home/dev/.rvm/gems/ruby-1.9.3-p545/gems/blacklight-5.16.3/app/models/concerns/blacklight/document.rb:31:in `<module:Document>'
/home/dev/.rvm/gems/ruby-1.9.3-p545/gems/blacklight-5.16.3/app/models/concerns/blacklight/document.rb:15:in `<top (required)>'
/home/dev/.rvm/gems/ruby-1.9.3-p545/gems/activesupport-4.1.13/lib/active_support/dependencies.rb:443:in `load'
/home/dev/.rvm/gems/ruby-1.9.3-p545/gems/activesupport-4.1.13/lib/active_support/dependencies.rb:443:in `block in load_file'
/home/dev/.rvm/gems/ruby-1.9.3-p545/gems/activesupport-4.1.13/lib/active_support/dependencies.rb:633:in `new_constants_in'
/home/dev/.rvm/gems/ruby-1.9.3-p545/gems/activesupport-4.1.13/lib/active_support/dependencies.rb:442:in `load_file'
/home/dev/.rvm/gems/ruby-1.9.3-p545/gems/activesupport-4.1.13/lib/active_support/dependencies.rb:342:in `require_or_load'
/home/dev/.rvm/gems/ruby-1.9.3-p545/gems/activesupport-4.1.13/lib/active_support/dependencies.rb:307:in `depend_on'
/home/dev/.rvm/gems/ruby-1.9.3-p545/gems/activesupport-4.1.13/lib/active_support/dependencies.rb:225:in `require_dependency'
/home/dev/.rvm/gems/ruby-1.9.3-p545/gems/railties-4.1.13/lib/rails/engine.rb:468:in `block (2 levels) in eager_load!'
/home/dev/.rvm/gems/ruby-1.9.3-p545/gems/railties-4.1.13/lib/rails/engine.rb:467:in `each'
/home/dev/.rvm/gems/ruby-1.9.3-p545/gems/railties-4.1.13/lib/rails/engine.rb:467:in `block in eager_load!'
/home/dev/.rvm/gems/ruby-1.9.3-p545/gems/railties-4.1.13/lib/rails/engine.rb:465:in `each'
/home/dev/.rvm/gems/ruby-1.9.3-p545/gems/railties-4.1.13/lib/rails/engine.rb:465:in `eager_load!'
/home/dev/.rvm/gems/ruby-1.9.3-p545/bundler/gems/sunspot-9c4ec23487d4/sunspot_rails/lib/sunspot/rails/tasks.rb:34:in `block (4 levels) in <top (required)>'
/home/dev/.rvm/gems/ruby-1.9.3-p545/bundler/gems/sunspot-9c4ec23487d4/sunspot_rails/lib/sunspot/rails/tasks.rb:34:in `each'
/home/dev/.rvm/gems/ruby-1.9.3-p545/bundler/gems/sunspot-9c4ec23487d4/sunspot_rails/lib/sunspot/rails/tasks.rb:34:in `block (3 levels) in <top (required)>'
/home/dev/.rvm/gems/ruby-1.9.3-p545/bundler/gems/sunspot-9c4ec23487d4/sunspot_rails/lib/sunspot/rails/tasks.rb:69:in `with_session'
/home/dev/.rvm/gems/ruby-1.9.3-p545/bundler/gems/sunspot-9c4ec23487d4/sunspot_rails/lib/sunspot/rails/tasks.rb:19:in `block (2 levels) in <top (required)>'
/home/dev/.rvm/gems/ruby-1.9.3-p545/bin/ruby_executable_hooks:15:in `eval'
/home/dev/.rvm/gems/ruby-1.9.3-p545/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => sunspot:reindex

**Comment by xhero** [comment]
We pushed back the working Gemfile.lock, run `bundle install` to rollback; issue will be investigated before next release

**Comment by HirschSt** [comment]
Ok, it works also if I monkey patch app/models/concerns/blacklight/document.rb by dropping (commenting) the included block:
#included do
    extend ActiveModel::Naming
    include Blacklight::Document::Extensions
#end
