### ISSUE TITLE
Change wf_stage and wf_audit to int

### ISSUE THREAD

**Issue by lpugin** [rism-ch/muscat#178]
Use enum instead
http://edgeapi.rubyonrails.org/classes/ActiveRecord/Enum.html

Values should be:
new: 0
pub: 1
del: 2
This should be mapped to in the to_internal - to_external method

Values for wf_audit to be defined, but for now
basic: 0
minimal: 1
full: 2
Migration should be 2 by default

**Comment by xhero** [comment]
Also tested in import so it sets correct default
