### ISSUE TITLE
Refactor standardized title in list (db version) following the opac style

### ISSUE THREAD

**Issue by lpugin** [rism-ch/muscat#179]
Concatenate subfields

**Comment by xhero** [comment]
This means Source.title and Source.tite_m should change their contents?

**Comment by lpugin** [comment]
Yes. Just don't put the siglum and the shelfmark

**Comment by xhero** [comment]
This is not working out of the box; where do we put the title on source (if we keep it). Or should this go into the std_title fields? But then it is not a standard title.
Also in ActiveAdmin it is not simple to replicate the appearance from rism.info, which uses author (or collection) + linebreak + concatenated subfields. Or should this not be saved at all on the database and just shown in AA (in blacklight opac it is already formatted following rism.info)

**Comment by lpugin** [comment]
This should go in std_title fields. This is indeed the standardized title with all its subfields. We should do the same for authors. It is not problem since we don't use the db fields for searching, only for display.

**Comment by xhero** [comment]
Modified title into std_title
