### ISSUE TITLE
Migrate 852 $d to 541 $e 

### ISSUE THREAD

**Issue by lpugin** [rism-ch/muscat#195]
Some access notes are currently in 852 $d?

**Comment by lpugin** [comment]
@cgueggi we have about 8,000 titles with 852 $d. How should we proceed?

**Comment by cgueggi** [comment]
I'm not sure if I understand. As far as I see we need 3 fields for shelf marks: (current) shelf mark (now 852$p), former shelf mark (olim, now 852$d), other shelf mark (has to be added, 541?). So I think we could leave 852$d where it is, no?

**Comment by lpugin** [comment]
Other shelf marks will be in 591. The question for us is that we have
accession notes in 852 $d and we should move them to 541.

**Comment by cgueggi** [comment]
OK. Now I understand. We have a 4th field for access numbers. So we have to go through the 8'000 titles by hand. It should be easy to recognize wether it is an access number or a former shelf mark (as long as you can prepare a manageable list).

**Comment by xhero** [comment]
I made the list of all the field contents

**Comment by cgueggi** [comment]
Hmm. It's not that easy as I first thought... It's difficult to recognize whether it is an access number or a shelf mark. Maybe we should ask Yvonne.

**Comment by xhero** [comment]
[List of field contents](https://github.com/rism-ch/muscat/files/892916/852d.xlsx)

**Comment by cgueggi** [comment]
Please give this to Yvonne Peters. She sometimes used an accession number.

**Comment by xhero** [comment]
What is the status of this? I have no code yet for the conversion. @baccia did you see this with Yvonne?

**Comment by baccia** [comment]
Here's the table (checked with Yvonne):
[852d.xlsx](https://github.com/rism-ch/muscat/files/912958/852d.xlsx)
