### ISSUE TITLE
Adding an option to close (go back to the editor) when documentation is loaded in the editor

### ISSUE THREAD

**Issue by lpugin** [rism-ch/muscat#197]
RSH: In order to ease the find and enter part abbreviations, the list of instrument abbreviations should be easier accessible. Best would be direct access by an own “list” button above the field, with possibility to select from the abbreviation list. Of course, also a “Back” button must included in this list, which at the moment is not the case.

**Comment by xhero** [comment]
Is this still valid?

**Comment by xhero** [comment]
Does the abbreviations field have an autocomplete? I think we can close this
