### ISSUE TITLE
Finalize to_external

### ISSUE THREAD

**Issue by lpugin** [rism-ch/muscat#200]
## Make sure we fill
- [x] leader
- [x] 003
- [x] 005
- [ ] 007
- [ ] 008
- [ ] 035 add B/I number as local ID
- [x] 040 (see below) solved with 3355430
- [x] 130 (see below)
- [x] 240 $n (fed from 383 and 690) solved with 16a75be
- [x] 500 Include digital objects (See #473) solved with a008853
- [x] 594 $a (see below)
- [x] 774 $a (or, better, $a and $t?) solved with f9b6fe7
- [x] Remove internal notes 599 solved with 3527833
## 040

Fill / expand 040
- add $a if not present
- append $c if $a present and not in $c
## 130

Move 240 to 130 when no 100 is provided
## 594

See #340

**Comment by xhero** [comment]
These are the fields to export. It  means to_internal is ok? The ticket was closed

**Comment by lpugin** [comment]
Yes, to_internal looks OK. This is for the next milestone.

**Comment by HirschSt** [comment]
edited list (772 was removed, see #391)

**Comment by lpugin** [comment]
It think for $772 the task was to add a title / composer for the OPAC. Now I wonder if this is still necessary for 774.

**Comment by lpugin** [comment]
Sorry, I am seeing that 774 is still in the list, forget my last comment

**Comment by HirschSt** [comment]
007/008 controlfields are really tricky, I think we should postpone it to a later milestone; maybe we can create a new issue for that

**Comment by xhero** [comment]
What is the status of this? Is to_external ok for now? I think we should close this issue and make a more specific one for the control fields in the postponed milestone.

**Comment by HirschSt** [comment]
Yes, we can close it for now.
