### ISSUE TITLE
Finalize ZR export

### ISSUE THREAD

**Issue by lpugin** [rism-ch/muscat#205]
100 $j, 700 $j (and 710 $g ?) should be mapped as:
* e => Ascertained
* z => Doubtful
* g => Verified
* f => Misattributed
* l => Alleged
* m => Conjectural

518 should be prefixed appropriately (e.g., "Performance date: ")

730 should be split in subfields

772 $a should be dropped

**Comment by xhero** [comment]
Translation table:

```ruby
    if letter == "e"
      word = "Ascertained"
    elsif letter == "z"
      word = "Doubtful"
    elsif letter == "g"
      word = "Verified"
    elsif letter == "f"
      word = "Misattributed"
    elsif letter == "l"
      word = "Alleged"
    elsif letter == "m"
      word = "Conjectural"
    end
```

**Comment by lpugin** [comment]
Dates in 700 should be stored in $d and not in $a with ```<>```

**Comment by HirschSt** [comment]
There is a revised version of sources export at http://dl.rism.info/dataset20160126.tar.gz; <> in 700 would be fixed during export later (not with converting).

**Comment by HirschSt** [comment]
"<>" problem in 700$a with copyists fixed with the latest sources export  (see eg
http://service1.rism.info/opac?operation=searchRetrieve&version=1.1&query=id=464000984&maximumRecords=10
)

**Comment by HirschSt** [comment]
All fixed in https://github.com/rism-t3/marcxml-tools/raw/master/export/sources.tar.gz

100 $j, 700 $j (and 710 $g ?)  FIXED
518 should be prefixed appropriately (e.g., "Performance date: ") FIXED
730 should be split in subfields FIXED
772 $a should be dropped FIXED
