### ISSUE TITLE
Finalize tag config (missing fields)

### ISSUE THREAD

**Issue by lpugin** [rism-ch/muscat#206]
243: contains the title according german RAK guidelines. If we want to keep it, we should have this in different subfields. The simplest would be to have the same as for 240, that is $a, $k, $m, $n, $o and $r. Or somewhere else? To be discussed.

383: contains the opus number as it occurs in the source. We could use 240 $n instead. This would simplify both the data structure and the workflow. Indexing and search (in the OPAC) can be done on 240 $n too. However 383 contains the opus number as it occurs in the source, and not normalized like the 240$n field which is linked to the standard title. To be discussed.

490: is used by A/I to indicate the series of a record (A/I or B/I) in the print export. No issue.

040: used for recording the cataloguing agency and the cataloguing language. To be discussed.

**Comment by HirschSt** [comment]
243 would go to 730
383 should stay as it is in data (after rediscussion in ZR), because it is used in ZR. Proposal is to make 240$n readonly, because in new data there should be a direct link to catalogue in 690. So we have backward compatibility and inserting does not confuse editors which field 240$n/690 they should use.
040 should stay as it is.
@lpugin ok?

**Comment by lpugin** [comment]
I am not sure about the readonly in 240$n. This is a subfield we absolutely need in our Marc data as made available to the export. Now we could imagine adding it to the export, but what if we have more than one 690? This could happen, right? @cgueggi ? Or should we take 383? Is it repeatable?

**Comment by lpugin** [comment]
I think the only question left whether we can migrate 490 to 035. This would be better since this is one less field for the cataloguer.

**Comment by HirschSt** [comment]
490 indicates the series of the record (A/I, A/II, B/I etc.), not the id; probably in the future there is no need to use it anymore in the editor. Moving it to 035 is wrong because it is no number.

**Comment by lpugin** [comment]
@HirschSt you are absolutely right. I am adding it to the editor as a select field. We can removing it later, but I think it was still desired for the opac filtering.

**Comment by lpugin** [comment]
I'll make it a select. @HirschSt what series should we list?

**Comment by HirschSt** [comment]
A/I, A/II, B/I, B/II, B/IV

**Comment by lpugin** [comment]
This is now looking all good. Closing.
