### ISSUE TITLE
Make cataloguing agency an install parameter

### ISSUE THREAD

**Issue by lpugin** [rism-ch/muscat#209]
the value should be given in application.rb

Then we should use in to_external
For all marc (including auth)
* add 001 with
* add it in 040 ($a or $d if $a there and different)

**Comment by lpugin** [comment]
Relates to #206

**Comment by lpugin** [comment]
@HirschSt we should probably have the same (with to_internal and to_external) for the authorities. This means also drop 003 and 005 during the import.

Another question: do we absolutely want to have 040?

**Comment by lpugin** [comment]
@HirschSt what shall we do for 040?

**Comment by HirschSt** [comment]
@lpugin 040 could persist with 040$a from application.rb if we don't have 040$a in marc_source
I think about the values if we import from external (eg ICCU), which then should use 040$a=ICCU and 040$d=DE-633?

**Comment by lpugin** [comment]
You are right. We should keep it and eventually only add it in to_external is not given.
