### ISSUE TITLE
Clarifying values in 593 $a

### ISSUE THREAD

**Issue by lpugin** [rism-ch/muscat#211]
Abbreviated values such as 'mw', 'mt', etc. should be matched to un-abbreviated content

**Comment by lpugin** [comment]
See record 225005556

**Comment by HirschSt** [comment]
would be fixed in the export

**Comment by HirschSt** [comment]
Is fixed at https://github.com/rism-t3/marcxml-tools/blob/master/export/sources.tar.gz
