### ISSUE TITLE
Switch 039 (gender) to the more standard 375

### ISSUE THREAD

**Issue by HirschSt** [rism-ch/muscat#214]
Switch 039 (gender) to the more standard 375 (http://www.loc.gov/marc/changes-rda-375.html) in Person.
Must be fixed in export too (https://github.com/rism-t3/marcxml-tools/issues/2).

**Comment by HirschSt** [comment]
see: http://beta.rism.info/admin/people?utf8=%E2%9C%93&q%5B375a_contains%5D=female&commit=Filtern&order=id_desc

**Comment by lpugin** [comment]
Perfect.
