### ISSUE TITLE
Export Digital Object Metadata

### ISSUE THREAD

**Issue by HirschSt** [rism-ch/muscat#216]
Should contain:
- filename
- Id
- Description etc.

**Comment by HirschSt** [comment]
id should direct to source, not to self

**Comment by HirschSt** [comment]
id leaves as it is, instead add tag "sources_id" because this is an array

**Comment by HirschSt** [comment]
Hi,
revised version of the metadata xml is avaliable at http://dl.rism.info/DO/mm.tar.gz.

There is a sources tag with an array of rism_ids (sorry, but I was thinking from DO to sources and not in the other direction).

**Comment by lpugin** [comment]
Thanks. I can see that some images are not linked to a source. Are they linked to something else? As it is now in the interface, images have to be linked to a source. We need to think about what we want to have.

**Comment by HirschSt** [comment]
Indeed DO (links and images) can also (as with sources) have a many to many relation to a Person (see copyist Geissler in https://opac.rism.info/search?id=600500807), so DO probably should be a model where other entities can connect to.

**Comment by lpugin** [comment]
Ok, we can make then linkable to other object. However, it seems the example is a one to many. I am not sure we would want a many to many (one image linkable to several objects). Do we have this?

**Comment by lpugin** [comment]
Forget it, I can see some.
