### ISSUE TITLE
Adding possibility to change templates afterwards (RSH)

### ISSUE THREAD

**Issue by HirschSt** [rism-ch/muscat#237]

**Comment by lpugin** [comment]
Since we have dropped the Convolutum template, this is not a high priority anymore. Moved to wishlist.

**Comment by HirschSt** [comment]
Sooner or later we should enable editors to change the template afterwards (eg. from Ms to Print with holding); I think we can integrate this somewhere in the frontend, so we may have it in > 3.6.10;

**Comment by HirschSt** [comment]
Moved to 3.6.11 ;-)

**Comment by xhero** [comment]
I think the time is ready for this, I had multiple requests of this feature.
We can add a very simple selection menu that changes the template, what about the marc fields? The "wrong" ones remaining from the old template probably would end up un-grouped and get a validation warning

**Comment by lpugin** [comment]
I would suggest to see if we can enable this only if the content is compatible with the target template.

**Comment by HirschSt** [comment]
some initial steps with https://github.com/rism-ch/muscat/pull/769

**Comment by jenniferward** [comment]
I meant to ask about this today - my coworkers and I need this desperately! It would contribute to the "stability" of Muscat (or more precisely, how our data is organized in Muscat).

**Comment by HirschSt** [comment]
I think it's more or less ready, aside from UI. If you provide a folder with records and the target template on the testing system, it can be tested and checked after serverside maintenance.

**Comment by xhero** [comment]
We have this in 6.1
