### ISSUE TITLE
Clarification of the workflow (RSH)

### ISSUE THREAD

**Issue by HirschSt** [rism-ch/muscat#241]

**Comment by lpugin** [comment]
Needs clarification

**Comment by HirschSt** [comment]
Currently we only have "published" and "in progress". One wish is that all new records should be tagged as "published" by default. 
But probably there are more steps as "corrected", "incomplete" etc. which could be also adopted to the workflow. So we need some input here from the editors.

**Comment by HirschSt** [comment]
no technical issue
