### ISSUE TITLE
Binding is missing from 563$a (RSH)

### ISSUE THREAD

**Issue by HirschSt** [rism-ch/muscat#249]

**Comment by HirschSt** [comment]
Binding is in the export (s. http://service1.rism.info/opac?operation=searchRetrieve&version=1.1&query=id=469017000&maximumRecords=10) and in the conf, so everything should be fine with the next release.

**Comment by lpugin** [comment]
Yes, this is good. I think it is still missing in the editor profile. I check/add it. I what section should it appear? @cgueggi ?

**Comment by cgueggi** [comment]
In version 3.2 it was in "physical description". Since this does not exist anymore and it is not possible to insert into "group 01" etc. (binding is normally independent from a certain material group) best would be in "references and notes" after 525 "supplementary material". What do you think?

**Comment by lpugin** [comment]
OK, this sounds like a good place. I put it there.

**Comment by lpugin** [comment]
563 is actually now in material set since we have it related to material sets in the ZR data. See #351 for how to accommodate the CH data.
