### ISSUE TITLE
Merging the functions for people 700 (RSH)

### ISSUE THREAD

**Issue by HirschSt** [rism-ch/muscat#252]

**Comment by lpugin** [comment]
Relates to #289

**Comment by lpugin** [comment]
We need to see what is currently used. If only 10%, then we should certainly shorten the list and have only one list. If 90%, we need to see how to improve the interface.

**Comment by HirschSt** [comment]
1. What is currently used:
arr cmp clb ccp lbt lyr prf pbl scr asn fmo dte prt 

might me used sometime in future:
ppm egr edt dnr com dub

probably never used
art bnd chr cnd cst dnc evp ill itr ltg otm pat prd trl voc

2. In Kallisto we currently have two groups: work related functions and other functions:
work related:
arr cmp clb lyr lbt 
other:
ccp prf pbl scr asn fmo dte prt

**Comment by lpugin** [comment]
@xhero : could you extract a list of the relator codes $4 we have in our data?

**Comment by xhero** [comment]
Here it is:

```
arr
art
asn
aut
bnd
bsl
ccp
chr
clb
cmp
cnd
com
cst
dnc
dnr
dte
dub
edt
egr
fmo
ill
itr
lbt
ltg
lyr
pat
pbl
ppm
prd
prf
prt
scr
smp
trl
voc
```

**Comment by HirschSt** [comment]
Looks like we should leave it as it is...

**Comment by lpugin** [comment]
Yes... I will see if we can have a single structured list instead of two. This could a an acceptable compromise.

**Comment by lpugin** [comment]
Structured list in 5f88753775312eddd727d1052551657a3898fb4c
