### ISSUE TITLE
Adding filter for watermarks (GHK)

### ISSUE THREAD

**Issue by HirschSt** [rism-ch/muscat#272]

**Comment by xhero** [comment]
Are we sure we need all the tickets with *all* the requests before discussing them? Some, like this one, are not possible at the moment and would need a feasibility study and a modification to the schedule to achieve.

**Comment by lpugin** [comment]
I am not sure either. At least the tickets should be more explicit. We will need to go through them together on Thursday.

**Comment by HirschSt** [comment]
We think that we need the tickets for our work. So we can be shure that no
proposal get lost. Naturally it is important to order the points regarding
its priority. The list is a short description of the somehow more extensive
test remarks from our collegues. If you like I can copy the original
remarks into our ZR folder and into the issue system of Github. But most of
the remarks are in German. Stephan has already filtered the list.

2016-04-11 10:24 GMT+02:00 Laurent Pugin <notifications@github.com>:

**Comment by lpugin** [comment]
OK. I will try to go through before Thursday and mark the ones that needs clarification. Then we can go through together and decide for their priority and assign them.

**Comment by xhero** [comment]
Isn’t it better to make a list of the proposed modifications, discuss it and then actually make tickets with what we will implement into muscat? Tickets should be for active development, not proposed one

**Comment by HirschSt** [comment]
I would not be so restrictive, we can just take the issues for discussing
them via github and decide later what we should do with them. Nobody says
that we should realize everything.

Best,
Stephan

2016-04-11 10:49 GMT+02:00 xhero <notifications@github.com>:

> Isn’t it better to make a list of the proposed modifications, discuss it
> and then actually make tickets with what we will implement into muscat?
> Tickets should be for active development, not proposed one
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/rism-ch/muscat/issues/272#issuecomment-208235339>
>



-- 

Répertoire International des Sources Musicales
Stephan Hirsch
IT-Manager
Zentralredaktion
Sophienstraße 26
D-60487 Frankfurt am Main
Tel: +49 (0) 69 70 62 31
Fax: +49 (0) 69 70 60 26
http://www.rism.info

**Comment by lpugin** [comment]
Isn't searching in any field not enough?

**Comment by HirschSt** [comment]
For some collegues working extensivly with watermarks is usual, and looking in fulltext maybe not sufficient. But I think this requirement could be put to later development.
