### ISSUE TITLE
Mapp 243 (RAK-title) to 730g (Schaumberg)

### ISSUE THREAD

**Issue by HirschSt** [rism-ch/muscat#287]

**Comment by lpugin** [comment]
To be clarified

**Comment by HirschSt** [comment]
Idea is to have a selector in 730$g to show the rule type of the title (eg RDA, RAK, RISM etc.)

**Comment by lpugin** [comment]
OK, sounds good to me. What will the existing data have? RISM? Or undefined?

Also, we should probably also have a default value in the form so user do not have to select it every time.

**Comment by HirschSt** [comment]
Existing data will have "RISM", and this should be also the default imo.

**Comment by HirschSt** [comment]
Closed with 80fa53b
actually there is no default value in subfield_secondary, probably we should add an option to the configuration?

**Comment by lpugin** [comment]
Yes, we would need this
