### ISSUE TITLE
Add autocomplete to filters: name, profession, country code (JW)

### ISSUE THREAD

**Issue by HirschSt** [rism-ch/muscat#308]

**Comment by lpugin** [comment]
I guess this needs to be postponed to 3.6.0?

**Comment by HirschSt** [comment]
Country is resolved; with profession it is very difficult because we have a bulk of values (german, english, gnd-abbreviations etc.). Autocomplete for name is unclear
Fazit: postponed for 3.6

**Comment by xhero** [comment]
This should be in the People index or when referenced from the source editor?

**Comment by lpugin** [comment]
This ticket remains cryptic for me. Are we indeed talking about relator codes in sources or data in person?

**Comment by xhero** [comment]
If this is not needed I would like to close the ticket or postpone it to whishlist - it is not clear to me what needs to be modified
