### ISSUE TITLE
Add name variants to  places related filters (JW)

### ISSUE THREAD

**Issue by HirschSt** [rism-ch/muscat#309]

**Comment by lpugin** [comment]
Not clear enough. Could you elaborate?

**Comment by lpugin** [comment]
Found it: In the filter "Composer contains", name alternatives should be searchable. Example:
"Tchaikovsky" does not find "Čajkovskij".

**Comment by lpugin** [comment]
This actually works in the People search, so it looks good to me. I don't think we want this in the autocomplete because it will make the list too long and useless. Can be re-open if necessary
