### ISSUE TITLE
Use default values in selection boxes

### ISSUE THREAD

**Issue by HirschSt** [rism-ch/muscat#329]

**Comment by HirschSt** [comment]
@lpugin  for subfield_select I would propose to use the first value as default. Any other proposal?

**Comment by lpugin** [comment]
I would suggest to add a "default: value" in the config. They are cases where we don't want any value to be chosen by default because the field can remain empty (e.g., 700 $4).
Alternatively, you could do "default: true" and in that case only select the first one. I am fine either way.

**Comment by HirschSt** [comment]
Adding "default: value" pair looks quite good in my opinion, thanks

**Comment by HirschSt** [comment]
Default values are indeed rare so I think this can be closed with ecfa179

**Comment by lpugin** [comment]
Thanks!
