### ISSUE TITLE
Adding 383 (opus) in the various configurations

### ISSUE THREAD

**Issue by lpugin** [rism-ch/muscat#330]
Questions:

@HirschSt 
* Should it be repeatable ? 

@cgueggi
* Where do we want it in the editor template?
* Where do we want it in the show template?
* Should it be an open field by default in the editor?

**Comment by HirschSt** [comment]
Yes, it should be repeatable.

**Comment by lpugin** [comment]
@cgueggi - remaining questions?

**Comment by cgueggi** [comment]
1. In the "title and content" section after "catalogue name" (690). But I don't understand why we need a new field at all, since the opus is already given in 240$n?
2. If 383 really is needed in "references" (also after "catalogue name")
3. closed
