### ISSUE TITLE
852$d check that not several shelfmarks given in one single field

### ISSUE THREAD

**Issue by cgueggi** [rism-ch/muscat#331]

**Comment by lpugin** [comment]
@cgueggi could you clarify this?

**Comment by lpugin** [comment]
@cgueggi do you have one example?

**Comment by xhero** [comment]
@cgueggi do you have an example?

**Comment by cgueggi** [comment]
Here the list with all 852$d with more than one shelf mark. In total 40 titles, so we could correct them manually (but only in the new Muscat version [591], because we don't have the field "other shelf marks" in Muscat 3.5).
Bear in mind: we have many shelf marks with an additional RISM-Ms.-number in paranthesis like: (Ms. 6370). They come from the old record cards. We already decided many years ago to delete them resp. move to another field. The question is where exactly. Ask YP?!
[852 $d more than 1 shelf mark.xlsx](https://github.com/rism-ch/muscat/files/875668/852.d.more.than.1.shelf.mark.xlsx)

**Comment by xhero** [comment]
This is to be done after the migration right?

**Comment by cgueggi** [comment]
No, could be done now. 852 $d is repeatable. Could you do that please @baccia ?

**Comment by baccia** [comment]
Certainly! I'll split the numbers into several 852 $d.
