### ISSUE TITLE
Providing dataset of RISM-ZR records

### ISSUE THREAD

**Issue by HirschSt** [rism-ch/muscat#333]
Just only to have a list of the links to the data here too (not only in mail)...

**Comment by HirschSt** [comment]
http://dl.rism.info/muscat-data/muscat3data_20160426.tar.gz

**Comment by HirschSt** [comment]
http://dl.rism.info/muscat-data/muscat3data_20160426.tar.gz

changelog: tags with empty $0 removed in https://github.com/rism-t3/marcxml-tools/commit/2e3a3a6e5403da4457d58a19830fcb98faef3e5b

**Comment by HirschSt** [comment]
http://dl.rism.info/muscat-data/muscat3data_20160429.tar.gz

Changelog: added 337$a (physical medium) to catalogue, related to #286

**Comment by HirschSt** [comment]
http://dl.rism.info/muscat-data/muscat3data_20160503.tar.gz

Changelog: transposing 622 to 371, 569 to 551

**Comment by xhero** [comment]
Thanks! Are these exports with the full dataset?

**Comment by HirschSt** [comment]
Yes.

**Comment by HirschSt** [comment]
http://dl.rism.info/muscat-data/muscat3data_20160511.tar.gz

Changelog: added 541 and 561 in sources, 680 and 667 in institutions, splitted 510 in people

**Comment by HirschSt** [comment]
http://dl.rism.info/muscat-data/muscat3data_20160512.tar.gz

Changelog: Fixes missing 510$0 in people

**Comment by HirschSt** [comment]
http://dl.rism.info/muscat-data/muscat3data_20160513.tar.gz
- transferred urls to 856 in source
- linked 670 to catalogue in people
- having all catalogue db entries (ca. 33.000) in export

**Comment by HirschSt** [comment]
http://dl.rism.info/muscat-data/muscat3data_20160519.tar.gz
- inserted inventories (Bestand) in institutions and sources (710 with relator code 'dpt')

**Comment by HirschSt** [comment]
http://dl.rism.info/muscat-data/muscat3data_20160520.tar.gz
- added digital_objects.xml for import of Digital Objects; related images at http://dl.rism.info/muscat-data/images_20160520.tar.gz (3.5 GB)

**Comment by HirschSt** [comment]
http://dl.rism.info/muscat-data/muscat3data_20160525.tar.gz @xhero 
- data update

**Comment by HirschSt** [comment]
http://dl.rism.info/muscat-data/muscat3data_20160601.tar.gz
- included non-publishing records
- replaced &gt; and &lt; entities in authorities

**Comment by xhero** [comment]
Super thanks! I’ll start the update now

**Comment by HirschSt** [comment]
Tomorrow I can provide a new set with removed zero 700$0/710$0 links and <> replaced by [] in sources

**Comment by HirschSt** [comment]
http://dl.rism.info/muscat-data/muscat3data_20160602.tar.gz
- removed zero 700/710$0 links in sources
- "&lt;/&gt;" replaced by "[ ]"
- making 852$p non repeatable

**Comment by HirschSt** [comment]
http://dl.rism.info/muscat-data/muscat3data_20160606.tar.g
- removed empty 852$x
- corrected empty 690/691$0 links

**Comment by HirschSt** [comment]
http://dl.rism.info/muscat-data/muscat3data_20160609.tar.gz
- Fixed multiple shelfmarks
- Fixed wrong header with autographs
- Added Anonymus in 100 again
- Removed 856 if it's Digital Object

**Comment by xhero** [comment]
Importing now, thanks!

**Comment by HirschSt** [comment]
@xhero Updated dataset at
http://dl.rism.info/muscat-data/muscat3data_20160912.tar.gz

- Added Thesaurus
- Removed 240$0 from sources

**Comment by HirschSt** [comment]
@xhero http://dl.rism.info/muscat-data/muscat3data_20160920.tar.gz
- Moved 772 -> 774
- Splitted 031$t
- Reactivated 852$c

**Comment by HirschSt** [comment]
@xhero http://dl.rism.info/muscat-data/muscat3data_20160922.tar.gz

- Fixes error with multiple 031$t
- Removed 852 from B/I-subitems closes #409 
- Renamed "DIGITALISAT", closes #411

**Comment by HirschSt** [comment]
@xhero  http://dl.rism.info/muscat-data/muscat3data_20160923.tar.gz

- Copied roles from 031$t to 595$a if not already there, closes #400 
- Fixes two records with multiple 852, closes #408

**Comment by HirschSt** [comment]
@xhero http://dl.rism.info/muscat-data/muscat3data_20160928.tar.gz
- Various changes in catalog
- Fixes #412

**Comment by xhero** [comment]
Thanks! I'm updating so tomorrow I will have in on out test server.

**Comment by xhero** [comment]
I am marking this as open so I see it in the list

**Comment by HirschSt** [comment]
http://dl.rism.info/muscat-data/muscat3data_20160929.tar.gz

- Moved 490 to 510 in sources
- Add incipit scoring in 031$z

@xhero please do a merge with 3.6.0-devel-authority before the import

**Comment by HirschSt** [comment]
@xhero http://dl.rism.info/muscat-data/muscat3data_20161001.tar.gz
- Generated values 210$a in Catalogue
- Various changes in institutions
- Added renumbered records from Bach Digital

**Comment by HirschSt** [comment]
http://dl.rism.info/muscat-data/muscat3data_20161004.tar.gz
- Fixed date values in 005
- Changed id range for Bach Digital

**Comment by HirschSt** [comment]
@xhero http://dl.rism.info/muscat-data/muscat3data_20161005.tar.gz
- Removed 130$0
- First line in *_analyze.txt shows highest id

**Comment by HirschSt** [comment]
@xhero http://dl.rism.info/muscat-data/muscat3data_20161014.tar.gz
- Various corrections in migration
- Full updated dataset
- related images at http://dl.rism.info/muscat-data/images_20161014.tar.gz

**Comment by xhero** [comment]
thanks! Importing at full steam

**Comment by HirschSt** [comment]
http://dl.rism.info/muscat-data/muscat3data_20161021.tar.gz
- Added internal remarks
- Added 596
- Fixed unknown relator codes
etc etc

**Comment by HirschSt** [comment]
@xhero  http://dl.rism.info/muscat-data/muscat3data_20161026.tar.gz
- Date in 260$c in format YYYYMMDD in some cases
- Added 856 in material
- Included all title incl. non-publishing
- Added ISIL code to 024 in institution
- Images at http://dl.rism.info/muscat-data/images_20161026.tar.gz

**Comment by HirschSt** [comment]
http://dl.rism.info/muscat-data/muscat3data_20161029.tar.gz
- Moved extent of 300$a to 590$b in case of parts
- Changed date format to YYYY in case of YYYY0000
- Url in 500 not moved to 856 anymore
- Added comment to scoring to 500

**Comment by HirschSt** [comment]
@xhero @lpugin http://dl.rism.info/muscat-data/muscat3data_20161031.tar.gz
- Transcribed PiKaDo chars *m33 etc. #390 
- Added "fl. " in 100$y with people
- Moved Kallisto URL from to 856
- Removed false HAY records in export
- Images at http://dl.rism.info/muscat-data/images_20161031.tar.gz

**Comment by HirschSt** [comment]
@xhero http://dl.rism.info/muscat-data/muscat3data_20161103.tar.gz
- Preserved sorting of entries in collecion closes #440 
- {{brk}} as linebreak closes #438 
- utf8 replacement of most diacritis closes #424 
- Concat of multiple 856$z subfields in one subfield
- All Kallisto url items now in 856 instead of 500
- Images at http://dl.rism.info/muscat-data/images_20161103.tar.gz

**Comment by HirschSt** [comment]
@xhero @lpugin http://dl.rism.info/muscat-data/muscat3data_20161104.tar.gz
- Added title in material 
- Added external note in material
- Minor changes in catalogue
- Images at http://dl.rism.info/muscat-data/images_20161104.tar.gz

**Comment by HirschSt** [comment]
@xhero @lpugin http://dl.rism.info/muscat-data/muscat3data_20161105.tar.gz
- Multiple 500 in material if public note
- Removed initial "Public note" with 500 in material
- Minor fixes in catalogue
- Images at  http://dl.rism.info/muscat-data/images_20161105.tar.gz

Let's cross fingers this will be the last pre-final set!

**Comment by HirschSt** [comment]
@xhero @lpugin http://dl.rism.info/muscat-data/muscat3data_20161107.tar.gz
- Fixed missing < > replacement (now [ ] again)
- Removed corrupt record with orphaned incipits
- Removed zeros if year is YYYY0000 in 260c

**Comment by HirschSt** [comment]
@xhero  @lpugin http://dl.rism.info/muscat-data/muscat3data_20161110.tar.gz
- no changes (except internal data)
- Images at http://dl.rism.info/muscat-data/images_20161110.tar.gz

Made overnight to gain some more time ;-)

**Comment by lpugin** [comment]
Great!

**Comment by xhero** [comment]
So this is it? ;)

**Comment by HirschSt** [comment]
Yepp!

**Comment by xhero** [comment]
Super! I'm starting now

**Comment by xhero** [comment]
I think we can close this now :)
