### ISSUE TITLE
NoMethodError in Admin::People#show 

### ISSUE THREAD

**Issue by HirschSt** [rism-ch/muscat#334]
Occurs if empty? is called with nil class (in active_admin_auth_show_title( val1, val2, id ))

see http://beta.rism.info:3367/admin/people/50000000

This happens if people records are autogenerated with empty 700$a in sources (see http://service1.rism.info/opac?operation=searchRetrieve&version=1.1&query=id=551002233&maximumRecords=10)

**Comment by lpugin** [comment]
Yes, this is problematic. Shouldn't we have something like [unspecified] for such cases? Empty (nil) values will always be problematic.

**Comment by xhero** [comment]
The code is wrong. It should check for nil before empty?. I can fix it

**Comment by HirschSt** [comment]
Probably testing for "blank?" could be handy here

**Comment by lpugin** [comment]
The main question is why do we have empty $a. It does not make sense to me.

**Comment by HirschSt** [comment]
Because in Kallisto people sometimes fill out anything else (eg funktion "src") and forget to link to people (sigh). Unfortunately there is no validating in Kallisto to prevent this, and even harder to erase.

**Comment by xhero** [comment]
I see to distinct problems here:

* The partial should not crash on invalid data (well spotted and easy to fix)
* What sense does it make to have a 700 field with empty $a and $0?

**Comment by HirschSt** [comment]
Yep. First should be fixed IMO, second: maybe I can drop these tags if $0 is empty during the convert, I will test it...

**Comment by lpugin** [comment]
First: I agree, we do need to fix the problem. I
Second: we should have them dropped during the export since they make no sense

**Comment by lpugin** [comment]
Is this related? (It crashes for me)
http://muscat-dev.rism.info/admin/people/40006447

**Comment by HirschSt** [comment]
Not exactly , and it is already fixed in 884d298

**Comment by xhero** [comment]
The display function seems fixed and so the data (40006447 loads now)
