### ISSUE TITLE
Migrate 240 $n to 383 $b

### ISSUE THREAD

**Issue by lpugin** [rism-ch/muscat#339]
Catalog references in 240 $n can be ignored, only opus number have to be migrated

240 $n also needs to be dropped

**Comment by xhero** [comment]
How do I tell the difference between catalog reference and opus number? is there a particular format to follow?

**Comment by xhero** [comment]
I made a list for @cgueggi, if it seems ok I will add this to the script

**Comment by lpugin** [comment]
240 $n (and 730 $n) also needs to be dropped

**Comment by xhero** [comment]
The script will split $n into the opus number and catalog number, opus number will be migrated. @cgueggi I'm waiting your OK with the data.

**Comment by cgueggi** [comment]
Sorry, see e-mail 15 minutes ago. Corrections done, two questions there.
