### ISSUE TITLE
Add 383 and 690 to std_title

### ISSUE THREAD

**Issue by xhero** [rism-ch/muscat#341]
the std_title field in the database should always contain the valid title for a source. Every time the source is listed this field should be used - marc should never be accessed directly, for example in the source listing in admin/sources.
The complete_title title function should be moved to provide the correct input for std_title. I reverted the patch at the moment because in some cases loading marc during listing crashes the system.
What are the fields that need to be in std_title, other than 240 $a, $o, $k and $m?

**Comment by lpugin** [comment]
We also need 691 (subfield to see) and 383

**Comment by xhero** [comment]
Was it ever decided what goes in 691 and 383?

**Comment by xhero** [comment]
New format:` Trios - vl (2), vlc; op.54/2; GerB 114` generated from `"#{title} - " + [extract, arr, scoring, opus, cat_no]`
