### ISSUE TITLE
Previous entry 775 in source yields wrong relation

### ISSUE THREAD

**Issue by lpugin** [rism-ch/muscat#346]
Tag 775 is a hierarchical relationship. This means that the link should not be via source_id but instead via source_to_source. This is currently wrong

**Comment by xhero** [comment]
Where does this happen? In 3.5-devel no tag is configured for sources_to_sources, nor it is enabled in the allowed_links, and the table remains empty, as no tag is configured to fill it. The relation on 775 currently does nothing as it still has to be assimilated in the 773 one (which is a special case and does not use the foreign_links)

**Comment by xhero** [comment]
I created a hard-coded fix which is robust enough for now - the get_all_foreign_associations will need to be rewritten
