### ISSUE TITLE
Abbreviation of key?

### ISSUE THREAD

**Issue by cgueggi** [rism-ch/muscat#347]
e. g. "Eb" (RISM-CH), "E|b" (RISM-ZR)?

**Comment by xhero** [comment]
Is this still relevant?

**Comment by xhero** [comment]
in 031 $r and 240 $r

**Comment by xhero** [comment]
I would migrate all to the ZR spelling. This is the data we have in 031r:

```
 c
1
10t
11t
12t
1t
1t
2/4
2t
3/4
3t
4t
4t
5t
5t
6t
6t
7t
8t
8t
9t
A
Ab
B
Bb
B|b
C
C        -
C#
C-1
Cb
Cx
D
D
D#
Db
E
Eb
E|b
F
F#
Fb
Fx
G
G
G#
Gb
H
Hôte du diable quelle tièdeur
S
a
a#
ab
b
bE
bb
c
c#
cx
d
d#
e
eb
f
f#
fx
g
g        -
g / G
g#
gb
gx
h
```

**Comment by xhero** [comment]
And this in 240r:

```
 Bb
10t
11t
12t
1t
2t
3t
4t
5t
6t
7t
8t
9t
A
A-Dur
Ab
B
B Dur
Bb
Bb
C
C
C#
C-Dur
Cb
Cx
D
D
Db
E
E Dur
Eb
Eb
Es Dur
F
F
F#
Fx
G
G
G Dur
G-Dur
Gb
Ges Dur
H
ParC 54
\
a
a#
a/A
ab
b
bb
c
c moll
c#
cx
d
d moll
d#
d/D
db
e
eb
f
f#
fb
fx
g
g moll
g#
gb
gx
h
op. 58
```

**Comment by xhero** [comment]
In Muscat 3.6 both fields have a pop-up list, should we transform these values in the correct ones in this list? This is the list:

```
     - "A"
      - "a"
      - "A|x"
      - "a|x"
      - "A|b"
      - "a|b"
      - "B"
      - "b"
      - "B|b"
      - "b|b"
      - "C"
      - "c"
      - "C|x"
      - "c|x"
      - "C|b"
      - "c|b"
      - "D"
      - "d"
      - "D|x"
      - "d|x"
      - "D|b"
      - "d|b"
      - "E"
      - "e"
      - "E|b"
      - "e|b"
      - "F"
      - "f"
      - "F|x"
      - "f|x"
      - "G"
      - "g"
      - "G|x"
      - "g|x"
      - "G|b"
      - "g|b"
      - "1t"
      - "2t"
      - "3t"
      - "4t"
      - "5t"
      - "6t"
      - "7t"
      - "8t"
      - "9t"
      - "10t"
      - "11t"
      - "12t"
```

**Comment by cgueggi** [comment]
In my opinion yes! But there are some wrong contents, e. g. (in 031 $r) "Hôte du diable quelle tièdeur", "2/4", "3/4" etc. They're probably in the wrong field. Also "H" should be changed to "B" and many more (also in 240$r). What can we do?

**Comment by xhero** [comment]
I would do it this way:

- The ones that need to be moved to another field should be done by hand.
- For the others I make a conversion table:

```
H -> B
Eb - > E|b
C-Dur -> C
etc...
```

**Comment by cgueggi** [comment]
Ok. Seems to be a good way to manage this. Could you please give me a list (split by 031 and 240) with the wrong content (including the ID-no.)? That is:
031$r: 1, 2/4, 3/4, C-1, Hôte du diable quelle tièdeur, S, g / G
240 $r: ParC 54, \ , op. 58
What about the # that indicates a sharp key. Possible to include that in your conversion table @xhero ?
There are two contents that begin (wrongly) with a blank (in 031 it is [blank]c, in 240 it is [blank]Bb. If not possible to do automatically it should be included to the list with the wrong contents.
@baccia Please do the corrections then.

**Comment by xhero** [comment]
I sent the list. For the ones starting with a blank I can strip them with no problem.
Everything else can be matched:

`b# -> B|x`

**Comment by baccia** [comment]
The offending 031r and 240r have been corrected.

**Comment by baccia** [comment]
Conversion table completed.

**Comment by xhero** [comment]
In the table some values are left empty (like C-1), I assume they have to be deleted, right?

**Comment by xhero** [comment]
And these are the results. 031r:

```
10t
11t
12t
1t
1t
2t
3t
4t
4t
5t
5t
6t
6t
7t
8t
8t
9t
A
A|b
B
B|b
C
C|b
C|x
D
D
D|b
D|x
E
E|b
F
F|x
G
G
G|b
G|x
a
a|b
a|x
b
b|b
c
c|x
d
d|x
e
e|b
f
g
g|b
g|x
```

**Comment by xhero** [comment]
Getting the correct 240r was more difficult, but here is the list:

```
10t
11t
12t
1t
2t
3t
4t
5t
6t
7t
8t
9t
A
A|b
B
B|b
C
C|b
C|x
D
D|b
E
E|b
F
F|x
G
G|b
a
a|b
a|x
b
b|b
c
c|x
d
d|b
d|x
e
e|b
f
f|x
g
g|b
g|x
h
```
