### ISSUE TITLE
Titles with more than one material set and a 563 binding note

### ISSUE THREAD

**Issue by lpugin** [rism-ch/muscat#351]
@cgueggi  : in version 3.5.0, the binding note is available in material sets only (and not at the source level). We currently have about 250 titles with a 563. Most of them have only one material set, so we can easily migrate them to the material set. However, about 30 have more than one. So we should either 1) migrate them by hand, 2) move the 563 to 500, or 3) allow 563 at the source level. What do you think?

**Comment by lpugin** [comment]
See http://www.rism-ch.org/admin/folders/92

**Comment by cgueggi** [comment]
As far as I see most of them could be migrated either to 500 or 563 (in the material set). It depends on the individual case. We should do that by hand. We definitely don't need an extra 563 in the general remarks section!

**Comment by lpugin** [comment]
@cgueggi : we can look how to do it by hand

**Comment by cgueggi** [comment]
Proposal: Migrate all 563 $a to 563 $a in the first material group. Afterwards sort out the 30 titles with more than one material group by hand. Use following folder: http://www.rism-ch.org/admin/folders/92

**Comment by xhero** [comment]
You can edit the excel file I sent you to add after the 563 the number of the group to which it will be associated, this way I will do it automatically in the migration script.

**Comment by xhero** [comment]
I also assume I do **not** need to do what was specified in #207, right?

**Comment by cgueggi** [comment]
@xhero #207 is in my opinion obsolete. I'll do the corrections by hand. Some of them go to 500, others have to be splitted and added to different material groups (what then has to be done by you). I'll prepare the excel file.

**Comment by cgueggi** [comment]
Here is the excel file. Some went to 500 and are already done (marked green). The first one (purple) has to be discussed with YP. A few just go to the 1st or 2nd material group (see first column), I had to reformulate them (signed green in first column). In two cases (406000113, 407001352) 563 is used more than once (not assigned in the excel file by xhero). They go to different material groups (to do after migration?). In four cases (407001363, 407001366, 407001368, 409000513) in one 563 field is information that has to be split, reformulated and migrated to two different material groups.
The last cases can be discussed next week.
[563 hand_materials CG.xlsx](https://github.com/rism-ch/muscat/files/881081/563.hand_materials.CG.xlsx)

**Comment by xhero** [comment]
Since the "wrong" records are not many, I would add $801 to each 563 and maybe then they can be fixed by hand afterwards?

**Comment by xhero** [comment]
I added the code to the script - we can test the result on 232.

**Comment by xhero** [comment]
At the moment I just add $801 to each 563, making it belong to the first group. Can the handful of wrong titles be corrected by hand before/after the update?

**Comment by baccia** [comment]
Yes, I'll correct the wrong titles.

**Comment by baccia** [comment]
Corrected by hand.
