### ISSUE TITLE
Removing repeated shelfmarks

### ISSUE THREAD

**Issue by lpugin** [rism-ch/muscat#353]
Currently we have some records (about 14,000) with repeated shelfmarks ($p). We should have only one. Other shelfmarks should go in 591a.

However, it seems that in some (or all?) cases, the repeated shelfmark is not several shelfmark but one that is is wrongly split. See  455032860 is
```
<marc:subfield code="p">Mus.ms. 30220</marc:subfield>
<marc:subfield code="p">(8a)</marc:subfield>
```

But should be just one single Mus.ms. 30220 (8a)

https://opac.rism.info/id/rismid/455032860?format=marc

**Comment by HirschSt** [comment]
In 455032860 we have indeed an alternative shelfmark, see http://service1.rism.info/opac?operation=searchRetrieve&version=1.1&query=id=455032860&maximumRecords=10. The XML output at BSB seems to be misleading, shelfmarks are generally not splitted in the export. 
591 also contains old shelfmarks, so I am not in favor of putting multiple 852$p there; but maybe we can use an indicator to specify the kind of shelfmark (591$b with "old shelfmark" or "other shelfmark"; or do we have more options?

**Comment by lpugin** [comment]
OId shelfmarks are in 852 $d, so I don't think we need to add something for 591

**Comment by HirschSt** [comment]
Old shelfmarks are going to 852$d, multiple values in 852$p to 591$a in the export; 852$p contains only the first shelfmark then
