### ISSUE TITLE
Catalogues, People and Institutions generated from scatch by Source

### ISSUE THREAD

**Issue by xhero** [rism-ch/muscat#354]
There are c.a. 2193 People, 3 Institutions and 513 Catalogues that do not have marc_source. This is because they are created during Source import and have no corresponding value existing in the auth file.

**Comment by HirschSt** [comment]
Obviously these are coming from empty 700/710$0 links, see eg http://service1.rism.info/opac?operation=searchRetrieve&version=1.1&query=id=551002233&maximumRecords=10, which is resolved with the latest export > 20160601; what may be the reason for the 513 catalogues?

**Comment by xhero** [comment]
This is one of them `BlazekovicK 2009: Colla, Domenico (Cola; Kola) &lt;1730c*&gt;`

**Comment by xhero** [comment]
I still find all the people, with ids like 322, 55076, 60188 - who creates them?

**Comment by xhero** [comment]
BTW there is just one "orphan" source, 453450999

**Comment by HirschSt** [comment]
It seems that these people have got a new id, but this change wasn't triggered to update the linked sources. I have to find a way to resolve this ...
I can't find BlazekovicK 2009 anywhere in the latest sources export; 453450999 is a reference by 453450138 and will be fixed in the data

**Comment by HirschSt** [comment]
Got it: catalogue entries are generated by not linked bibliographic data from people, there is no exact matching possible in 670 (in Kallisto it is a string field); so everthing is fine except marc (and description) is nil, which probably could be fixed by workaround.

**Comment by HirschSt** [comment]
There are remaining linkage work for a major update, so this issue is taken to 3.6

**Comment by xhero** [comment]
This needs to be verified with the new import
