### ISSUE TITLE
Adding drop down menus to various fields

### ISSUE THREAD

**Issue by lpugin** [rism-ch/muscat#356]
240 $k "Excerpts", "Sketches", and "Fragments"
240 $o "Arr", "Var"
240 $k keys (list to be provided by Jennifer)
340 $d (list to be provided by @cgueggi 
031 $r (key or mode, list to provided by Jennifer)
031 $g (all clefs, list to be provided by Jennifer)

I think all lists need to be localized (including clef since added information such as "Treble clef" is desired)

**Comment by xhero** [comment]
Didn't we drop 130? and moved it to 240?

**Comment by lpugin** [comment]
Yes, only 240, sorry (and 730 when applicable)

**Comment by xhero** [comment]
ok - what is the label for $n?

**Comment by xhero** [comment]
Is it normal we do not have 340 in the data? $d was not configured in the editor. Is this only for CH?

**Comment by lpugin** [comment]
I'll make a ticket for 340 $d for the next version
