### ISSUE TITLE
Improve shelfmark sorting

### ISSUE THREAD

**Issue by lpugin** [rism-ch/muscat#363]
For the records, from @ahankinson 
https://github.com/diamm/diamm/blob/master/solr/conf/schema.xml#L137
http://www.andornot.com/blog/post/Make-numbers-behave-when-sorting-alphanumerically-in-Solr.aspx

**Comment by xhero** [comment]
The new setup needs a full reindex, not the parallel one

**Comment by lpugin** [comment]
Sorting works now perfectly. We need to see the reindex constraint, so I am leaving the issue open.

**Comment by xhero** [comment]
It will work with the parallel one also, but since I changed various fields I want to wipe the index so there are no old leftovers

**Comment by lpugin** [comment]
Great!
