### ISSUE TITLE
Adding messages to be displayed below the fields after validation

### ISSUE THREAD

**Issue by xhero** [rism-ch/muscat#364]
as title; should not prevent record from saving but show a warning. On loading? On loading after save? Or should it prevent the first save but then go on?

**Comment by lpugin** [comment]
Looks great. Didn't we have message added underneath the fields at some point?

**Comment by xhero** [comment]
It was disabled at some point, I think it made a mess with autocomplete fields, we can make a ticket for the messages

**Comment by lpugin** [comment]
I am changing the label

**Comment by xhero** [comment]
It actually makes a mess with checkboxes, I will see if I can fix this
