### ISSUE TITLE
Make repeatable fields non repeatable in editor

### ISSUE THREAD

**Issue by xhero** [rism-ch/muscat#365]
The Marc configuration should always follow the marc standard, so repeatable fields should be marked as such.
In some cases, like material groups, repeatable fields should not be repeated in the group (as they are already repeated by the groups). Add a "non repeatable in editor" override in the configuration.

**Comment by xhero** [comment]
I need a list of fields - all of the ones groupable or only some?

**Comment by xhero** [comment]
Before I can close this issue I need the list of the fields which should never be repeatable

**Comment by lpugin** [comment]
Yes, I'll look at this. 594 was still unclear, I'll look at others with @cgueggi
