### ISSUE TITLE
Add items to a collection from the collection record

### ISSUE THREAD

**Issue by mjwalter** [rism-ch/muscat#373]
It may be convenient or intuitive to be able to add an item that belongs to a collection from the beginning. Being able to select which fields would prepopulate the item record would help ensure consistency in the data between the collection and item records.

The current interface seems to allow it, but the functionality is not present.

**Comment by lpugin** [comment]
Link fields to child records are indeed read-only from the collection. The reason for that is that these fields are added by the system when a link to the collection is made from the child record. We could evaluate if we can allow the opposite but we would need to make sure that data integrity is maintained.
