### ISSUE TITLE
Appearance of "owner" filter

### ISSUE THREAD

**Issue by mjwalter** [rism-ch/muscat#375]
Filtering by owner is useful. As the number of owners is quite large (and unsorted), it might be better if it were a text field, perhaps with autocomplete, rather than a drop-down selection menu.

**Comment by xhero** [comment]
Autocompletes are not supported in the sidebar. Implementing it is not too complex but not straightforward either. If it is not urgent I would move this after 3.6

**Comment by xhero** [comment]
I nobody requests this anymore, I would close

**Comment by HirschSt** [comment]
Yes, can be closed IMO... BTW: I would like not to extend server side processing too much with UI, but to reduce the complexity of the system whenever possible.

**Comment by jenniferward** [comment]
Is this still relevant? When I log in as a cataloger, I only see my name as an option under Owner.

**Comment by HirschSt** [comment]
Catalogers are can search only for their own records because of privacy, only admins and editors can look for records of other users. Because there is no need to do this every day, the existing option list is quite good. We can reopen it if there is an urgent need to have an autocomplete.
