### ISSUE TITLE
Tabs instead of panels when creating record

### ISSUE THREAD

**Issue by mjwalter** [rism-ch/muscat#376]
When creating a record, the various sections ("Library information and relations", "People and institutions", etc.) are stacked in one long vertical area. It might be easier from a UI perspective to display these as tabs. This would allow users to navigate quickly from one section to the other; it might also make it easier to confirm that the right fields have been filled out.

**Comment by lpugin** [comment]
We decided to have a sidebar instead of tabs because it has the advantage of remaining visible even when scrolling down. With tabs, users would have to scroll up for changing tab.
