### ISSUE TITLE
Toggle button to hide unused fields

### ISSUE THREAD

**Issue by mjwalter** [rism-ch/muscat#377]
There are a large number of useful fields, but seeing all of them when only several will be used might slow work in certain circumstances. A toggle button to hide unused fields would alleviate this problem. With the Duplicate feature, users can ensure that the fields that they will be using are not empty, so they will not be hidden.

**Comment by lpugin** [comment]
This is a good idea. We need to see how to integrate it in the interface.

**Comment by xhero** [comment]
Non-default fields are all collapsed by default now
