### ISSUE TITLE
Allow user to customize source index columns

### ISSUE THREAD

**Issue by mjwalter** [rism-ch/muscat#378]
Sometimes a particular column may be unnecessary for a user, while other times one that is less important would be very useful to display. Allowing the user to select which columns will display would be valuable.

**Comment by lpugin** [comment]
Unfortunately, this is not easily feasible. We could allow columns not to be shown, but I am not sure this would be very helpful. I am leaving the issue open in case somebody has an idea how to deal with it.

**Comment by xhero** [comment]
Is there any followup? This feature was not requested again and it would be quite complex to do.

**Comment by HirschSt** [comment]
We could do this with datatables, but this indeed would be complex...my propose: let's postpone this until we make a refactor of UI without AA :-)
