### ISSUE TITLE
Use autocomplete search value for new window search

### ISSUE THREAD

**Issue by lpugin** [rism-ch/muscat#381]
See https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/muscat/yWn5_d67Jus

I think we need in the config a way to specify what search field (filter) need to be populated, but otherwise it does not sound too complicated to pass this as param in the url. We should try to have this for 3.6.0 but we can postpone it if necessary.

**Comment by xhero** [comment]
On the message-passing side it is quite easy, we need to test it because the search in the new window and the agglomerated data in the autocomplete can be quite different.

**Comment by lpugin** [comment]
I haven't test it but I feel that adding the truncation would be useful.

**Comment by lpugin** [comment]
Is this up on 232?

**Comment by xhero** [comment]
Sorry, forgot to recompile assets
