### ISSUE TITLE
IT translations

### ISSUE THREAD

**Issue by baccia** [rism-ch/muscat#386]
- [x] RISM Series (490) change into: Serie RISM
- [x] sources: 511 'Nota sui interpreti' change into: 'Nota sugli interpreti'
- [ ] sources: translate page 'Create New Folder'?
- [ ] sources: translate buttons 'Previous, Back to the list, Next'?
- [x] sources: 594 'NUMBER' (in all langs)?
- [x] sources: 710 'DEPOSITOR' in Italian is 'Depositante' (treccani.it, entry 'deposito')
- [x] digital_objects: filters, 'Nome file' change into: 'Grandezza file'
- [ ] comments: translate page title 'Comments' and search options? 
- [ ] comments: translate page 'Dettagli comments'?
- [x] people: 400, 'Name variants' = 'Varianti del nome'
- [x] people: 400, drop-down menu: 'Altre form' change into: 'Altra forma'
- [x] people: 400, drop-down menu: 'Monogram' change into: 'Monogramma'
- [x] people: 400, drop-down menu: 'Pseudonym' change into: 'Pseudonimo'
- [x] people: 400, drop-down menu: 'Kind of variant' = 'Tipo di variante'
- [x] people: 667: 'Non public note' = 'Nota interna'
- [x] people: 670, 'Source data found' = 'Fonte dei dati citati'
- [x] people: 680, 'General note' = 'Osservazioni'
- [x] catalogues: 'Note sul sitolo uniforme' change into: 'Note sul titolo uniforme'
- [x] catalogues: translate drop-down menu in 240?
- [x] catalogues: translate drop-down menu in 337?
- [x] catalogues: translate 'Control fields' in results view?
- [x] catalogues: 'Indicatione di possesso' change into: 'Indicazione di possesso'
- [x] catalogues: items_list_page 'Series items' change into: 'Volumi della testata'?
- [ ] liturgical_feasts: translate search options in result page?

**Comment by lpugin** [comment]
@xhero if you do not want to do it yourself just organize for @baccia to do it directly

**Comment by xhero** [comment]
For me is the same, I thought Claudio wanted to do it, but I can do it Monday, no prob

**Comment by baccia** [comment]
Ciao Rod, lo faccio io volentieri, martedì mi spieghi come fare!
C.
