### ISSUE TITLE
Migrate 518 and 033

### ISSUE THREAD

**Issue by lpugin** [rism-ch/muscat#389]
- 033 is now only used for the publication data in material groups
- 518 is now used only as general data (not bound to a material group)

**Comment by xhero** [comment]
See #401

**Comment by cgueggi** [comment]
Hmm, I think we have to go through the list. After a first sight some will go to 518, some to 500 or even others. According to the latest guidelines 033 is used for all dates on the source (without any commentary field), 518 only for performance date. So what should we do with cases like "composition date: 1733"? Do we want to ask Jennifer?

**Comment by jenniferward** [comment]
No, according to the latest guidelines the 033 is used for "the formatted date of the performance that is named in the field Note on performance (518)." Meaning 518 has to be filled out first and the 033 is the coded form of the date.

It seems to me that "composition date: 1733" would either go in the 500, or if it is referring to the source at hand, in the 260.

**Comment by cgueggi** [comment]
Sorry, I only had a look at the german version of the guidelines. This seems to be outdated. So you're right. Then we have to go through the list and manage it (more or less) by hand?

**Comment by jenniferward** [comment]
(Sorry about the confusion, the German guidelines are correct on guidelines.rism.info but need to be updated on the public view of Muscat.  They read: "Dieses Feld enthält die im Feld Bemerkung zur Aufführung (518) genannte Daten in Kodierter Form.")
