### ISSUE TITLE
Remove old PiKaDo encoding 

### ISSUE THREAD

**Issue by lpugin** [rism-ch/muscat#390]
We still have some old PiKaDo encoding, such as "*m33" (about 600). See for example
https://opac.rism.info/search?id=110002190

Any other sign?

**Comment by cgueggi** [comment]
The same with "*n33" (about 1'200). See for example: http://www.rism.info/en/service/opac-search.html

The codes stand for overlines: "m̅" resp. "n̅" = "mm" resp. "nn"

**Comment by HirschSt** [comment]
Need unicode replacement char to change this, but can't find one. Any suggestions?

**Comment by lpugin** [comment]
Aren't the codes provided above a good suggestion?

**Comment by HirschSt** [comment]
Looks good, I will take them during the conversion
