### ISSUE TITLE
Import: drop 003 and 005 in authorities

### ISSUE THREAD

**Issue by lpugin** [rism-ch/muscat#396]
They should be provided back by to_external. See #209 

What about 040 (sources and authorities)?

**Comment by lpugin** [comment]
@xhero : we should do as for the sources, which is to use 005 for the creation / modification date

**Comment by lpugin** [comment]
Relates to #407

**Comment by HirschSt** [comment]
@lpugin  @xhero  Will it be dropped during import, or shall I drop it with the export?

**Comment by lpugin** [comment]
During import, nothing to do on your side

**Comment by lpugin** [comment]
Actually one question for you @HirschSt : is it OK if we change the authorities so it is the same as for the sources? That is: 003 and 005 are dropped when imported and the put back in to_external. The reason is that we do not want to have to update 005 every time we save a record, because this would yield an versioning item to be generated (even if there is no other change)

**Comment by xhero** [comment]
the leader is also dropped as in source: I would need a table to re-generate it

**Comment by HirschSt** [comment]
@lpugin Yes, processing authorities like sources is ok for me
