### ISSUE TITLE
Finalize 518

### ISSUE THREAD

**Issue by lpugin** [rism-ch/muscat#401]

**Comment by lpugin** [comment]
Not sure what need to be done in the export

**Comment by xhero** [comment]
Can I move this of milestone? I have no idea what to do here

**Comment by lpugin** [comment]
Yes. I will talk about it with Jennifer tomorrow

**Comment by xhero** [comment]
Is the list OK? What should we do with this issue?

**Comment by lpugin** [comment]
@cgueggi : could you look at what we have and the new guidelines? Thanks

**Comment by xhero** [comment]
From #389:

033 is now only used for the publication data in material groups
518 is now used only as general data (not bound to a material group)

**Comment by xhero** [comment]
[List of all 518 values](https://github.com/rism-ch/muscat/files/892424/all_518a.txt)

**Comment by xhero** [comment]
Do we need to split/parse these?

**Comment by xhero** [comment]
Just to make matters more interesting: in 3.2 12409 records already have 033, _outside_ the group. The guidelines for 3.6 state that 033 should be _inside_ the group. How should we proceed?

Also: what data do we have in 033 in 3.2? from comments on #389 it seems that in 3.6 this is the **performance** date.

**Comment by xhero** [comment]
[518_non_regular.xlsx](https://github.com/rism-ch/muscat/files/896391/518_non_regular.xlsx)
These are the 518 that do NOT contain the popup menu values: _First performance date_, _Performance date_, _Composition date_
