### ISSUE TITLE
Fix "phantom" sources

### ISSUE THREAD

**Issue by xhero** [rism-ch/muscat#412]
There are some sources which do not have MARC data. They are referenced and created by some other sources in the 773 $w field but then they are not filled in.

Phantom Source | Referred by
---------------- | ------------
303005137 | 303005140
303005137 | 303005141
303005166 | 303005167
303005166 | 303005168
303005193 | 303005197
303005637 | 303005639
456017204 | 456017205
456017218 | 456017219
456017218 | 456017221
456054251 | 456054253
456054251 | 456054259
456054251 | 456054260
456054273 | 456054276
456054273 | 456054290
456054273 | 456054307
456054273 | 456054340
456054273 | 456054343
456054273 | 456054368
456054384 | 456054394
456054384 | 456054449
456054384 | 456054489
456054384 | 456054500
456054384 | 456054510
456054384 | 456054658
456054572 | 456054595
456054572 | 456054596
456054572 | 456054609
456054617 | 456054623
456054640 | 456054642
456054640 | 456054652
456054659 | 456054662
456054659 | 456054664
456054659 | 456054665
456054659 | 456054673
456054775 | 456054801
456054775 | 456054812
456054775 | 456054821
456054775 | 456054822
456054887 | 456054898

**Comment by xhero** [comment]
I propose we delete them all, It would be best if this is done in the Export so they are not imported at all (and all refs. created, etc)

**Comment by HirschSt** [comment]
@xhero is the list complete or a sample?

**Comment by xhero** [comment]
complete (39 phantoms, quite good!)

**Comment by HirschSt** [comment]
Pefect, I will correct them in the export
