### ISSUE TITLE
Fix "phantom" catalogues, institutions and people

### ISSUE THREAD

**Issue by xhero** [rism-ch/muscat#413]
As for the Sources, there are many many catalogues, institutions and people that are either created from scratch (id > 95000000, missing ID in the reference) or references to an ID that is then not in the authority file.
I can make a (huge) list of these, or should I run `scaffold_marc` on them and have the basic marc data?

**Comment by xhero** [comment]
Related to #354

**Comment by HirschSt** [comment]
I tend to scaffold_marc because I'm not sure the reason for that in all cases (probably mostly they came from pure string fields without direct binding to authority). Can you give me the list anyway?

**Comment by xhero** [comment]
I like scaffold_marc too, if it is OK with everyone I will make a script
