### ISSUE TITLE
Malformed 773 and 774 $w

### ISSUE THREAD

**Issue by xhero** [rism-ch/muscat#418]
There are 2656 ca. records in the range 998000002 - 998004649 that have a malformed 773 tag (this is from record 998004649):

```xml
   <datafield tag="773" ind1="0" ind2=" ">
     <subfield code="w">HAY000039</subfield>
   </datafield>
```
**HAY000039** is not a valid ID. In the same manner there are many with a 774 tag in the same format

**Comment by HirschSt** [comment]
Fixed with latest dataset 20161004
