### ISSUE TITLE
Diacritics in keywords

### ISSUE THREAD

**Issue by lpugin** [rism-ch/muscat#424]
We need to check where this comes from
http://muscat-dev.rism.info/admin/standard_terms/95000484

**Comment by HirschSt** [comment]
It's coming from http://muscat-dev.rism.info/admin/catalogues/1250, and it's wrong in the kallisto data itself (most probably copy & paste latin-1 by the cataloger). I think we have to improve this on our side only we have a bulk more...

**Comment by HirschSt** [comment]
Made the replacement of most diacritics (about ~90 %). Can't do a list with east european chars, but there are only a few.
Resolved with dataset 20161103
