### ISSUE TITLE
If possible, export the record creation date

### ISSUE THREAD

**Issue by lpugin** [rism-ch/muscat#427]
This should go in a 008 field, first six positions for yymmdd.

**Comment by HirschSt** [comment]
It's stored in the export in 005 as yyyymmdd, eg.
<controlfield tag="005">20150928111111.0</controlfield>

**Comment by lpugin** [comment]
OK. I think the idea is to have 005 for the last modification date and 008 for the creation date.

**Comment by HirschSt** [comment]
It will be copied over from 005 to 008 in the converted export, in the format yymmdd.

**Comment by HirschSt** [comment]
BTW, will this date be used as :created_at attribute?

**Comment by lpugin** [comment]
Yes, 008 at created_at and 005 as updated_at

**Comment by HirschSt** [comment]
In Kallisto we have an additional created value which unfortunately is not in the marcxml; it can be set with the latest release of link_users.yml in the format {rismid => [user, created_at]} (in the marcxml is a date correlating with the release date).

**Comment by HirschSt** [comment]
related to #428

**Comment by lpugin** [comment]
@xhero all good?
