### ISSUE TITLE
Preserved record ownership

### ISSUE THREAD

**Issue by lpugin** [rism-ch/muscat#428]
We can try to preserve the record ownership. No all records will have one. This will come as a separate file with record id and name. The name will match the name in the user model.

@xhero what would be the simplest format? csv or xml as for do?

**Comment by xhero** [comment]
csv is the simplest, or you could make yml that is even simpler

**Comment by HirschSt** [comment]
Have prepared "link_users.yml" in the private muscat_users repository with id: username, maybe this can be used to define the ownership by a postfix.

**Comment by lpugin** [comment]
All good now, isn't it?
