### ISSUE TITLE
Add backend validation for Google Map Tags

### ISSUE THREAD

**Issue by xhero** [rism-ch/muscat#430]
The partial currently does not check if the fields are filled correctly, and if not, it will crash. It should also make sure that the link passed is a valid geolocation. It would be desirable to activate the editor validation also. I can make a special validator for geotags if I have the specifics.

**Comment by lpugin** [comment]
@HirschSt was this fixed?

**Comment by HirschSt** [comment]
No, not from my side

**Comment by xhero** [comment]
What should I do with this? If the data is incorrect it crashes pretty hard, but I do not have any info on how to validate it...

**Comment by HirschSt** [comment]
In beta.rism.info it crashes if one field is empty, but even if I take strings (see http://beta.rism.info/admin/institutions/51000008/edit) it shows an incorrect map and don't crash. Although we really need to improve the validation, I think we can use an intermediate workaround in 05f70dbab0586e44e355ec355f0a3d21b15e02f8
