### ISSUE TITLE
Referencing institutions in institution/show is very slow

### ISSUE THREAD

**Issue by xhero** [rism-ch/muscat#432]
in app/admin/institution.rb. The culprit is a very slow solr query, in production it is commented out but this needs to be fixed before the release (or completely removed)

**Comment by xhero** [comment]
The code I changed above makes a call to Solr to find the institutions that are linked to the one displayed. Is it correct? In this case we can just use `@item.institutions`, which has the list cached on the DB and does not need a query. Also `get_deposita` makes 2 Solr queries, but I could not really figure out why. It seems it is looking for a marc field? It would be better to access the marc data directly. Am I missing anything?

**Comment by lpugin** [comment]
If I remember correctly there was a reason not tu use `@item.institutions` and to have a solr query instead. But it should not be slow and do it twice anyway
