### ISSUE TITLE
Remove Verified from 100 (and 700 and 710?)

### ISSUE THREAD

**Issue by lpugin** [rism-ch/muscat#435]
The value $j Verified has to be remove

http://muscat-test.rism.info/admin/sources/659100305/edit

**Comment by HirschSt** [comment]
Sure? This is a loss of information...

**Comment by lpugin** [comment]
Double check with Martina or Jennifer.

**Comment by HirschSt** [comment]
They like to preserve this value, although it's not in the option list.

**Comment by lpugin** [comment]
OK, then the guidelines and the values and the translation needs to be fixed. I am leaving the ticket open for now.

**Comment by lpugin** [comment]
@HirschSt was "Verified" removed or not?

**Comment by HirschSt** [comment]
"Verified" is preserved.
