### ISSUE TITLE
Adding a script to mark the Bach Digital titles as unpublished

### ISSUE THREAD

**Issue by lpugin** [rism-ch/muscat#437]
We do not have this in the MarcXML, we need an additional post-script

**Comment by HirschSt** [comment]
Can be done by unpublishing these records via the frontend too

**Comment by lpugin** [comment]
Yes. I any case we need the list of records

**Comment by xhero** [comment]
A list of IDs is sufficient for me.

**Comment by HirschSt** [comment]
All records with 989* should not be published

**Comment by xhero** [comment]
Basically it is id > 988999999 and id < 990000000? I see different bachs and Haydn there, 4647 records, it is ok to blanket unpublish them?

**Comment by HirschSt** [comment]
Yes, that's ok.
