### ISSUE TITLE
Preserve collection content ordering

### ISSUE THREAD

**Issue by lpugin** [rism-ch/muscat#440]
This information is currently lost. The best would be to re-order the 774 accordingly

**Comment by xhero** [comment]
I need more information on this... Were is it lost? when saving? when importing?

**Comment by HirschSt** [comment]
@xhero was prepared to answer you ;-)

Ordering will be represented now by the ordering of the 774 fields in the collection entry. The order in the marc now is defined only by the special sorting field of Kallisto, as requested.

**Comment by lpugin** [comment]
Great!

**Comment by HirschSt** [comment]
resolved with dataset 20161103
