### ISSUE TITLE
Verify templates

### ISSUE THREAD

**Issue by lpugin** [rism-ch/muscat#444]
We have about 3,000 titles with a "Treatise handwritten" template. Something must be wrong
http://muscat-test.rism.info/admin/sources?utf8=%E2%9C%93&q%5Brecord_type_select_with_integer%5D=record_type%3A6&commit=Filter&order=std_title_shelforder_desc

**Comment by HirschSt** [comment]
I thinks it's an error coming from https://github.com/rism-ch/muscat/blob/3.6.1-devel/lib/marc_source.rb#L218, where pm is defined as theoretica source. Our definition from the leader was pm = mixed material item.

**Comment by xhero** [comment]
Could we have a table somewhere with the definitive schema for leaders? They seem to be the most nebulous part in the import, and I already changed them a few times but it seems it never gets to the definitive setup. What template should be associated to “mixed material”?

**Comment by HirschSt** [comment]
As I have sent it via mail:
- Record status:
"n" (which means "new" in all cases for the new import)

- Type section:
"c" (notated music), "d" (manuscript notated music) or "p" (mixed material)

- Bibliographic level:
"c" (collection), "d" (subunit) or "m" (item)

**Comment by xhero** [comment]
but this does not tell me what mixed material in in muscat. A source? and edition? a new template?

**Comment by HirschSt** [comment]
In most cases it should be source.

**Comment by xhero** [comment]
I verified the template, and since none of these records appear to be collections I made them sources and changed the to_import (in 859502a).
