### ISSUE TITLE
Check list

### ISSUE THREAD

**Issue by lpugin** [rism-ch/muscat#445]
* [x] Reset autoincrement ids to 4xx... after the import
* [x] Use recent create_users.rb with the import
* [x] Use recent link_users.yml with the import
* [x] Verify that there is no treatise or libretto template
* [x] Correct header in the facetted search
* [x] Correct solr port / environment for Blacklight
* [x] Correct version of the guidelines (3.6.1)
* [x] Change owners of authorities to Admin (instead of 0)
* [x] Turn down muscat-test and put a maintenance page
* [x] Verified log rotation (if not done make a ticket 1st priority for 3.6.2)
* [x] Set all 989* records to unpublish

**Comment by HirschSt** [comment]
RSH is not owner of all SBB; in Kallisto we have the user IIIB, which is transferred to RSH in link_users.yml

**Comment by lpugin** [comment]
OK, thanks. Does this mean that nothing needs to be done in Muscat?

**Comment by HirschSt** [comment]
Ownership will be set by the link_users.yml at the import, after that there is nothing to do.

**Comment by HirschSt** [comment]
@xhero obviously autgeneration will extend the range from 39* to 40*, see http://muscat.rism.info/admin/standard_titles?order=id_desc&page=11594

**Comment by lpugin** [comment]
I just send an email about this

**Comment by HirschSt** [comment]
Same idea at same time :-)

**Comment by lpugin** [comment]
@HirschSt ;-)

**Comment by lpugin** [comment]
@xhero double check blacklight index. It is showing unlikely values in Source Type facet (mk, 4, etc.)

**Comment by xhero** [comment]
I put log rotation to 50M and max 10 old (compressed) logs

**Comment by HirschSt** [comment]
Perfect, thanks!
