### ISSUE TITLE
Show deposita partial in institution

### ISSUE THREAD

**Issue by HirschSt** [rism-ch/muscat#452]
Related to #451, see https://github.com/rism-ch/muscat/commit/64f6292cdcd344a8f5dfb72f5ccc1f6f3ce3f35c#diff-5133048893e6c2dec9f09291d03b608fR264

**Comment by xhero** [comment]
Where should the partial be shown in the page?

**Comment by xhero** [comment]
I did some investigation and it seems the bad bug was triggered when the siglum was empty, as MarcSelect would select the whole institution set. I see in your commit that you make sure it is present - is this enough to fix the issue?
