### ISSUE TITLE
Add support for g-2 clefs

### ISSUE THREAD

**Issue by lpugin** [rism-ch/muscat#453]
Update drop-down list and Verovio (https://github.com/rism-ch/verovio/issues/350)

**Comment by HirschSt** [comment]
Any risk that we are loosing this key values (g-2) after update now?

**Comment by xhero** [comment]
I just made a fix online for this - do you have a record with this clef to test?

**Comment by HirschSt** [comment]
http://muscat.rism.info/admin/sources/451025885, second and third

**Comment by HirschSt** [comment]
Thanks; version tag in impressum is cheating now?

**Comment by xhero** [comment]
No I actually modified the running code so we can have it now. Today (or tomorrow) I will make a release with all the day's fixes

**Comment by lpugin** [comment]
The impressum says [modified]

**Comment by xhero** [comment]
Muscat 2016 tags/v3.6.1 [modified] (db5ad56) 

Isn't this ok? it is actually modified (by me)

**Comment by lpugin** [comment]
This is OK. We should try to avoid this however and go for proper updates. But when there is a risk to loose data and a possible quick fix we can do it.

**Comment by HirschSt** [comment]
no, it's ok; I actually wasn't aware that these changes are made directly in the production system and had overseen the modified tag.

**Comment by xhero** [comment]
Yup, that is why I want to make an update ASAP to 3.6.2
