### ISSUE TITLE
Showing the full list  of sources related to a standard title entry (or clarifying)

### ISSUE THREAD

**Issue by lpugin** [rism-ch/muscat#465]
Currently the list show only the sources with the standard title (DB-link). The source with an incipit text are not listed (Solr values).

If we cannot change this we should at least make it clear that the list contains only the standard titles or change the source count accordingly

**Comment by xhero** [comment]
This is work in progress in -devel-auth-link, it could also include SOLR links (to be tried!)

**Comment by HirschSt** [comment]
false commit reference (should be at rism-international/tasks)
