### ISSUE TITLE
Multiple copied text incipits in import instead of variants

### ISSUE THREAD

**Issue by HirschSt** [rism-ch/muscat#466]
Something ugly went wrong here, see eg. http://muscat.rism.info/admin/sources/211004774, where 1.1.2 is copied to the other textfield in 031$t (also in other incipits).

It's correct in the final dataset: 
 ```
<datafield tag="031" ind1=" " ind2=" ">
    <subfield code="a">1</subfield>
    <subfield code="b">1</subfield>
    <subfield code="c">2</subfield>
    <subfield code="g">C-4</subfield>
    <subfield code="m">T solo</subfield>
    <subfield code="n">xF</subfield>
    <subfield code="o">2/4</subfield>
    <subfield code="p">4-/=7/{6.,B3'C}{6.,A3B}/6GG8G{6.'C3D}{6.,B3'C}/6,AA8A</subfield>
    <subfield code="r">G</subfield>
    <subfield code="2">pe</subfield>
    <subfield code="u">31960689</subfield>
    <subfield code="z">Scoring: Solo: S, T, B; Coro; strings, bc; fl 1, 2, ob 1, 2; cor 1, 2</subfield>
    <subfield code="t">Edler bester Greis dich krönt Ruhm und Preis</subfield>
    <subfield code="t">Frommer Fröhlichkeit sei dies Fest geweiht</subfield>
  </datafield>
```
Any idea?

**Comment by HirschSt** [comment]
It was ok in yesterdays version, see http://beta.rism.info/admin/sources/211004774

**Comment by HirschSt** [comment]
Copying of the first textincipit is done during saving.

**Comment by xhero** [comment]
I already got and fixed the error. It seems it was always there, but not when you added a text incipit, only when saving a record with multiple ones

**Comment by HirschSt** [comment]
Thanks a lot, this is great. I think we should fix this in production as soon as possible because no one will recognize this error during the work.
