### ISSUE TITLE
Training server finalization

### ISSUE THREAD

**Issue by lpugin** [rism-ch/muscat#467]
* [x] Change the header to have linkes to the cataloguing, etc.
* [x] Change the BL headlines as in the image below
* [x] Make sure indexes are correct (BL works but nothing in AA)
* [x] Make sure email notification is disabled
* [x] Decide how to manage additional users

**Comment by lpugin** [comment]
![image](https://cloud.githubusercontent.com/assets/689412/20595336/dd8d96f2-b239-11e6-8296-0742ea19fc48.png)

**Comment by xhero** [comment]
Server is up and running, auto-updating every sunday morning. Will see monday how it works :)

**Comment by HirschSt** [comment]
Are the user table allways be overwritten? We like to preserve a special training account.

**Comment by xhero** [comment]
Yes they are copied over. BUT I could add a small sql-injection that adds one or more users every time the machine in synced. Do you have a name/pass for the account (and role)?

**Comment by lpugin** [comment]
Alternatively we could export the muscat-training users before reload, and the merge them (sql create if not exists) afterwards. This is a bit more work to put in place but then we can add training users directly from the user interface in muscat-training. @xhero whatever is best for you.

**Comment by rism-t3** [comment]
AFAIK We only need one user training@rism.info with the standard ActiveAdmin "password" :-)

**Comment by rism-t3** [comment]
Role should be cataloger

**Comment by rism-t3** [comment]
And default Workgroup 8 (USA)...sorry for the  step by step posting

**Comment by lpugin** [comment]
For workshops we will need more than one account because otherwise this will create problem. Shouldn't straightaway and training-01@rism.info with 01 to 99? Same password everywhere is OK, name should be distinct (e.g., "Training 01"). OK?

**Comment by xhero** [comment]
For me it is the same, I can make a script that creates how many users we want :)

**Comment by xhero** [comment]
I added a small script to do that (the names are without dash to make it simpler), we can modified if needed

**Comment by xhero** [comment]
BTW I create only 50 users - will we need more?

**Comment by lpugin** [comment]
Seems enough to me

**Comment by jenniferward** [comment]
I am thinking about the logistics of the users and passwords. Can the users be reused? On January 12 and 18 there will be two separate Muscat workshops held by IAML Austra. I presume it will be up to the organizers to distribute training-01 through training-12 to the first group of participants. Does the second group then get training-13 through training-25? Or can the second group start at training-01 again?

**Comment by lpugin** [comment]
They can be re-used without problem. Also, the server is reset every Sunday. Having more than one participant using the same login than another one at the same time technically works, but it will be harder for them to understand ownership because they will also own titles create by others (with the same account). So it would be good if organizers can assign account at the beginning of the workshop.

**Comment by jenniferward** [comment]
OK I understand. I presume that there will be a few people every so often who hang onto their test accounts and either log onto rism-training as a sandbox from time to time, or give the passwords to students or colleagues to experiment with, or demonstrate Muscat to a class.

**Comment by xhero** [comment]
That’s why it is wiped each Monday. We could also create ad-hoc users, and delete them when not needed anymore (I can make them persistent using a script)

**Comment by jenniferward** [comment]
Can someone announce this to the Muscat group? I'm sure there are people who would like to be aware of this for upcoming meetings, conferences, workshops, etc.

**Comment by lpugin** [comment]
Yes, I will do it later this morning
