### ISSUE TITLE
Remove delete action from index page

### ISSUE THREAD

**Issue by HirschSt** [rism-ch/muscat#469]
According to colleagues risk is too high to delete record by accident

**Comment by xhero** [comment]
This did not make it in 3.6.5. I have a couple questions: isn't the confirmation dialog enough? Should I remove it for all users or leave it for editors/admins?

**Comment by HirschSt** [comment]
Our editors are anxious to delete a record by accident, so they want to hide the delete option from all index pages - confirmation dialog seems not to be enough (that's not my opinion BTW). Destroy action should remain for editors/admins at show page. Probably we had to overwrite AA default actions?

**Comment by xhero** [comment]
It is very easy to hide in case. OK on *all* index pages?

**Comment by lpugin** [comment]
Don't we want to keep it on Comments? We should encourage people to delete them...

**Comment by HirschSt** [comment]
Yep, we should keep them in comments...

**Comment by jenniferward** [comment]
Guido told me shortly after the meeting where this was decided, and confirmed it just now, that he wants the delete option in the indexes (I guess he wasn't paying attention at the meeting). Can we pause this discussion until further notice? We need to discuss it again.

**Comment by lpugin** [comment]
OK, we will wait until @jenniferward clarifies it

**Comment by jenniferward** [comment]
Oops, I forgot to raise this point at today's meeting. It will have to wait until our next staff meeting in January.

**Comment by jenniferward** [comment]
We discussed this today and decided to leave everything as it is.
