### ISSUE TITLE
Monitor collections with deleted (missing) items

### ISSUE THREAD

**Issue by lpugin** [rism-ch/muscat#472]
See 1001001018 here
http://muscat.rism.info/admin/sources/1001000076

**Comment by HirschSt** [comment]
There is http://muscat.rism.info/admin/sources/1001000570 with many "DB link does not exist to this item" items (these are existent, but now refering to another collection). Is this related?

**Comment by lpugin** [comment]
This probably comes from a collection duplication. The expected behaviors is for the collection content to be dropped when duplicating a record. We need to check this

**Comment by lpugin** [comment]
@xhero can't you remember having done this? That is dropping 774 when duplicating? I cannot find it

**Comment by xhero** [comment]
I remember we made a script to fix but we never finalized to do it in the duplication process

**Comment by xhero** [comment]
I added code in 3.6.5 to drop 774
