### ISSUE TITLE
To_external should include DO public path

### ISSUE THREAD

**Issue by HirschSt** [rism-ch/muscat#473]
As with https://opac.rism.info/id/rismid/600077725?format=marc, but maybe 500$a=description: link
Example: 
500$a C & I HONIG [beneath a posthorn in a cartouche (crowned) - countermark:] IV: http://muscat.rism.info/system/digital_objects/attachments/000/013/138/maximum/H-26_wm_C_I_HONIG.JPG?1479983800

**Comment by lpugin** [comment]
OK. I added this to the list here https://github.com/rism-ch/muscat/issues/200 

Also, I can see the the images are accessible without login. This is fine but we want to make sure this is desired.

**Comment by HirschSt** [comment]
From my side it is desired :-)

**Comment by lpugin** [comment]
OK. Maybe we want symlink the path to something we can maintain more easily.

**Comment by HirschSt** [comment]
That's ok with me too

**Comment by lpugin** [comment]
I would suggest to have a symlink in ./public. Since 'images' is already used, maybe 'resources' ?

So the url would be:
http://muscat.rism.info/resources/000/013/138/original/H-26_wm_C_I_HONIG.JPG

OK?

**Comment by lpugin** [comment]
Alternatively we could have another subdomain

http://resources.rism.info/000/013/138/original/H-26_wm_C_I_HONIG.JPG

But I think this would be more complicated.

**Comment by HirschSt** [comment]
Yes, adding a new subdomain isn't neccessary IMO, I would prefer an easy:

http://muscat.rism.info/DO/000/013/138/original/H-26_wm_C_I_HONIG.JPG

to keep it short and to show the entity.

**Comment by lpugin** [comment]
Fine with me. @xhero : where do we add it? Directly on the server(s), or in the repository?

**Comment by lpugin** [comment]
This issue has no milestone. 3.7 or whish-list?

**Comment by HirschSt** [comment]
Adding the DO to the external is done, see https://github.com/rism-ch/muscat/blob/857224f7f3f914bf9caf76f158b0d7dbc67b52a9/lib/marc_source.rb#L466. Only a maintenance script for dropping the old dl.rism.info references are needed now, see https://github.com/rism-international/tasks/issues/307; so this issue could be closed IMO
