### ISSUE TITLE
Remove $q from 852 in sources

### ISSUE THREAD

**Issue by lpugin** [rism-ch/muscat#477]
This comes from Muscat 2.0 and A/I. It should not available on sources. We need to remove it from the tag_config for sources.

Maybe we can make it hidden straight away in 3.6.6, and then have a maintenance task to check the records (probably only a few?) that use it? We can quite likely fix them by hand.

**Comment by HirschSt** [comment]
Made 852$q hidden with cfbc8d4
Maintenance task will follow, then we can remove it from the tag_config.

**Comment by xhero** [comment]
What is the status of this? $q is still in the configuration, can it be removed?

**Comment by lpugin** [comment]
We need to check if we still have records using $q

**Comment by xhero** [comment]
In CH data we have none, but in ZR yes:

```
1001000241
1001026346
1001026348
1001026350
1001026769
1001026770
1001026771
1001026772
1001026773
1001026849
```
I will remove $q from the configuration in the meantime
