### ISSUE TITLE
Create a statistics page

### ISSUE THREAD

**Issue by HirschSt** [rism-ch/muscat#478]
To show current increase and such stuff. I would use [chart-js-rails](https://github.com/coderbydesign/chart-js-rails) if there are no cons, it's easy to use. This statistic page should be limited to editors and admins.

**Comment by lpugin** [comment]
Looks good to me. I would suggest to develop it in its own branch.

**Comment by lpugin** [comment]
@HirschSt  along the same lines, I reactivated the dashboard, which you can see up and running on muscat-test. Let me know what you think.
