### ISSUE TITLE
Create selection for 596

### ISSUE THREAD

**Issue by HirschSt** [rism-ch/muscat#491]
(JW) für das Feld Querverweise zu RISM A/I und RISM B (596 $a) bitten wir um ein Auswahlmenü, um die Eingabe zu vereinheitlichen. Hier sollen die A- und B-Bänden, die Drucke enthalten, zur Auswahl stehen. Wir wollen die folgenden Möglichkeiten anbieten:
A/I 
B/I
B/II
B/III
B/VI
B/VIII
B/IX/1
B/IX/2
B/XIII
B/XV
B/XVII

**Comment by xhero** [comment]
Should this be a fixed field (popdown list with no editing) or an autocomplete field which can accept other values?

**Comment by jenniferward** [comment]
A drop-down list, please.
