### ISSUE TITLE
Date filter uses US style dates

### ISSUE THREAD

**Issue by xhero** [rism-ch/muscat#492]
2017-24-05 will crash the filter. I added a fix so it does not crash, but we need to properly format the dates so our users can use the right date format.

**Comment by HirschSt** [comment]
"Right" date format should be ISO-8601 (YYYY-MM-DD), as it is with the selector; user input was YYYY-DD-MM, so I have no idea to parse this input correctly (as with the DateTime.parse method). Nevertheless rescueing this is necessary, thanks.

**Comment by xhero** [comment]
My idea (for the withlist) is to show the user an error message on the search page.
