### ISSUE TITLE
Fix get_miscellaneous_values

### ISSUE THREAD

**Issue by xhero** [rism-ch/muscat#495]
Still gets data from obsolete tags:
language from 008
dates from 033 (!!)

The source table still contains an unused "language" column, to decide if it is the case to drop it.

**Comment by xhero** [comment]
I would postpone this to 3.7, so we also remove redundant values in the database

**Comment by lpugin** [comment]
Sounds good

**Comment by xhero** [comment]
This was fixed when dates were fixed
