### ISSUE TITLE
Adding source description in editing mode

### ISSUE THREAD

**Issue by lpugin** [rism-ch/muscat#498]
In the edit mode for collections, please display title information about the individual entries. Currently only the RISM number is displayed:

![image](https://user-images.githubusercontent.com/689412/29062095-9faa8d66-7c20-11e7-82d6-a2e35ebb6283.png)

In the full record view, brief title information is displayed:

![image](https://user-images.githubusercontent.com/689412/29062115-b1043e22-7c20-11e7-8668-717129f836ec.png)

It would be useful to have also a minimal information displayed in editing mode

**Comment by xhero** [comment]
This is actually quite complex to do, since we would need to redesign the subfield_secondary it use (unless the tag is hardcoded), or to make a specialized partial simil-subfield_secondary (and hardcode it there)

**Comment by lpugin** [comment]
Yes, I thought so. I'll think about it too.

**Comment by HirschSt** [comment]
duplicate:

![image](https://user-images.githubusercontent.com/6461776/47483917-b0294e80-d83a-11e8-99bc-4f414f68b888.png)
