### ISSUE TITLE
Improve unpublishing action in folders

### ISSUE THREAD

**Issue by HirschSt** [rism-ch/muscat#513]
At the moment catalogers are able to unpublish records (s. #460); aside from this someone can unpublish a print with all holding records. What we should improve
- [x] enable rights management
- [x] exclude prints from this action
- [ ] include holding records if possible
- [ ] write rspec tests
- [x] use PaperTrail (probably inactive with the unpublishing action; needs more testing)

**Comment by xhero** [comment]
I think the basic stuff is done, should we move the rspecs for 6.0?

**Comment by HirschSt** [comment]
yes
