### ISSUE TITLE
Fix relator codes

### ISSUE THREAD

**Issue by lpugin** [rism-ch/muscat#514]
Relator codes in 700 (and 710?) where not fully migrated. See

409003483 voc
409003438 clb
409003482 bsl
409003484 ccp

We probably need to start with a list of relator codes we still have and then match them to the current list

**Comment by xhero** [comment]
Didn't we already do this? Relator codes were not touched by this migration

**Comment by lpugin** [comment]
I think we overlooked it

**Comment by xhero** [comment]
Ok, I'm making a list

**Comment by cgueggi** [comment]
Please send the list to me.

voc should be migrated to prf
clb should remain clb
bsl: I'm not sure wheter it was migrated to asn or oth
ccp: As discussed on monday, we need this relator code ("Autor der Textvorlage"). If it was deleted, please recreate it again!

**Comment by xhero** [comment]
I think the discussion should also include the ZR, particularly if we add codes that are not in the list. It the list we use now in muscat up-to-date?

**Comment by cgueggi** [comment]
Could you send me the latest list please? I can't find it anymore...

**Comment by xhero** [comment]
label | code | quantity
---- | ---- | ----
Other function |	oth	| 1
[unspecified] |	smp	| 1
Papermaker |	ppm	| 1
Binder |	bnd	| 1
[unspecified] |	62881fb0397b0131dcd0002215c9f3f4 |	1
Production personnel	| prd	| 1
Costume designer	| cst	| 1
Artist	| art	| 10
Illustrator	| ill	| 11
Compiler	| com	| 11
Choreographer	| chr	| 12
Donor	| dnr	| 12
Dancer	| dnc	| 13
Patron	| pat	| 18
Author	| aut	| 24
Contributer	| clb	| 28
Bookseller	| bsl	| 35
Conductor	| cnd	| 51
Engraver	| egr	| 54
Vocalist	| voc	| 127
Instrumentalist	| itr	| 142
Lithographer	| ltg	| 146
Translator	| trl	| 280
Conceptor	| ccp	| 301
Uncertain	| dub	| 393
Editor	| edt	| 394
Printer	| prt	| 591
Performer |	prf	| 612
Librettist	| lbt	| 681
Other	| asn	| 716
Publisher |	pbl	| 1070
Composer cross-reference | 	cmp |	1503
Dedicatee |	dte	| 3598
Arranger	| arr	| 4725
Copyist	| scr	| 4954
Former owner |	fmo	| 6064
Text author	| lyr	| 15062

**Comment by xhero** [comment]
And this is the 710:

label | code | count
---- | ---- | ----
Patron | pat | 5
Event organizer | otm | 11
Editor | edt | 25
Bookseller | bsl | 36
Performer | prf | 199
Other | asn | 251
Dedicatee | dte | 656
Printer | prt | 730
Donor | dnr | 1251
Former owner | fmo | 1614
Publisher | pbl | 1898

**Comment by xhero** [comment]
code | label
---- | ----
arr | Arranger
asn | Other
aut | Author
cmp | Composer cross-reference
ctb | Co-composer
dpt | Depositor
dte | Dedicatee
dte | Dedicatee
dub | Uncertain
edt | Editor
edt | Editor
egr | Engraver
fmo | Former owner
fmo | Former owner
ill | Illustrator
lbt | Librettist
ltg | Lithographer
lyr | Text author
oth | Other function
oth | Other function
pbl | Publisher
pbl | Publisher
prf | Performer
prf | Performer
prt | Printer
prt | Printer
scr | Copyist
scr | Copyist
trl | Translator

**Comment by xhero** [comment]
Relator codes only for 710

code | name
-- | --
asn | Other
dpt | Depositor
dte | Dedicatee
edt | Editor
fmo | Former owner
oth | Other function
pbl | Publisher
prf | Performer
prt | Printer
scr | Copyist

**Comment by xhero** [comment]
700 is fixed, 710 is pending discusison

**Comment by xhero** [comment]
Any news on the status of this? It would be nice if it can be included in 3.6.12

**Comment by cgueggi** [comment]
Add evp (event place/Aufführungsort) to the list. @xhero

**Comment by cgueggi** [comment]
fr: "Lieu de l'e**v**énement"

**Comment by jenniferward** [comment]
EN is fine
