### ISSUE TITLE
Verify "yellow" validated fields

### ISSUE THREAD

**Issue by xhero** [rism-ch/muscat#517]
Users report some strange behaivour in validated fields, that sometimes are yellow yet trigger no validation.

**Comment by jenniferward** [comment]
When creating a new record, the *only* yellow field that triggers a validation is the Subject heading (650), that is to say: it is possible to create a record consisting of only a subject heading. Is this intentional?

**Comment by HirschSt** [comment]
No, obviously that is is connected with "mandatory" tag in the validation: the only mandatory field we have at the moment is 650, see  https://github.com/rism-ch/muscat/blob/5c5e56845749fb8d280f702ae53cb5426e26db67/config/editor_profiles/default/configurations/SourceValidation.yml#L62

I just would suggest to add the mandatory tag to some other fields (eg 100, 852, 240 etc.), if it plays well with the template system...

**Comment by HirschSt** [comment]
ok, I have seen #395 concerning the templates...

**Comment by xhero** [comment]
We could reopen #395, I think it would be useful

**Comment by jenniferward** [comment]
In November 2016 the ZR editors submitted a list with suggestions for what fields should be open and what fields should be yellow. Our requested open fields are open but we would still like the following fields to be yellow and required, i.e. no record should be saved for a single (non-collection) manuscript source without the following:

Bibliothekssigel (852)
Komponist/Autor (100)
Diplomatischer Titel (245)
Einordnungstitel (240)
Schlagworteintragung (650)
Besetzung (594)
Quellentyp (593)
Abschrift oder Impressum: Jahr (260)
Material (300)

**Comment by jenniferward** [comment]
PS: Could you close the field  KATALOGISIERUNGSQUELLE (040)?

**Comment by xhero** [comment]
I added 594 that was missing.
To clarify, in Muscat we have three levels of validation:

1. **warning** - Shows a warning but then saves the second time
2. **required** - This triggers only if other fields of the tag are filled and the required one empty. The motivation is that if a tag is left completely empty it will not be added to the source, but it would be invalid if partially filled up
3. **mandatory** - The required value has to be there or the manuscript will not save. This tag must be filled in and must be present in the source.

Now, in the configuration the only "mandatory" tag is 650, all the others are "required". I can obviously change this - just make sure cataloguers will not be annoyed when they cannot save a record before it is fully entered.

**Comment by xhero** [comment]
Updated in 1dcc127e83c5ac38fa0406b70699c916d04b7e60

**Comment by jenniferward** [comment]
I can't predict how catalogers will feel, but we at the ZR do not want records that lack values in the fields listed above. According to your definitions, this means making them "mandatory".

Alexander has suggested creating a section on the template on the right (where you jump to different sections) called "Pflichtfelder"/"Required fields" (sorry for the confusion, there is a difference between how you use required/mandatory and how I use them), perhaps appearing above "Library information and relations," that displays only the required fields so catalogers can quickly identify the core fields and fill them out and save. Perhaps that would alleviate any concerns about saving records before they are fully entered.

**Comment by HirschSt** [comment]
I think we should change this after 3.6.12 because we need some time for testing on the user side to be sure that everything works as expected.

**Comment by HirschSt** [comment]
At least I have a cleared list with mandatory fields:
**:collection => 1**
Siglum (852$a)
Shelfmark (852$c)
Original title (245$a)
Individual title (130$a)
Scoring (594$a)
Type (593$a)
Material (300$a)

**:source => 2**
Siglum (852$a)
Shelfmark (852$c)
Author (100$a)
Original title (245$a)
Individual title (240$a)
Genre (650$a)
Scoring (594$a)
Type (593$a)
Material (300$a)

260$a should be required in both cases

I will communicate this proposal to the mailing list, afterwards I can adjust the configuration.

**Comment by jenniferward** [comment]
Here are two new lists.
Current warnings already present in Muscat can stay and are not repeated below.

**For collection records for manuscripts**, no record may be saved without the following:
Library siglum (852$a)
Shelfmark (852$c)
Diplomatic title (245$a)
Standardized title (240$a)
Physical description/Format, extent (300$a)

When Added Personal Name (700 $a) is filled out, the function (700 $4) must also be filled out. Same for Additional Institution (710 $a and $4).

These fields, when empty, should trigger a warning: 
Total scoring (594$a)
Source type (593$a)
Date (260 $c)

**For manuscripts not part of collections**:
Library siglum (852$a)
Shelfmark (852$c)
Composer/Author (100$a)
Diplomatic title (245$a)
Standardized title (240$a)
Subject heading (650$a)
Source type (593$a)
Physical description/Format, extent (300$a)

When Added Personal Name (700 $a) is filled out, the function (700 $4) must also be filled out. Same for Additional Institution (710 $a and $4).

These fields, when empty, should trigger a warning: 
Total scoring (594$a)
Date (260 $c)

**Comment by HirschSt** [comment]
This is the basic set we have with latest 3.7 953f15a8f0f933865514b773b908c8c43a6f0f1b:
mandatory: 240a, 245a, 650a, 852a, 852c
required: 031, 240m, 100a, 260c, 300a, 593a, 594a

Since some fields should be mandatory depending on their template (eg 100 mandatory with 002 source, required with 000 collection) I have set them to required for now to be on the safe side, so we could do refinement later by adding more sophisticated validation (eg Holding records).

**Comment by HirschSt** [comment]
further discussion at #577 because the real original issue concerning yellow fields seem to be unrelated
