### ISSUE TITLE
CH Data: Change print template to manuscript

### ISSUE THREAD

**Issue by xhero** [rism-ch/muscat#518]
A global search-and-replace, maybe add a note to indicate it was migrated? or make a list of ids?

**Comment by cgueggi** [comment]
I don't understand "search-and-replace". What should be replaced?

**Comment by xhero** [comment]
the print record_id with the ms one

**Comment by xhero** [comment]
Besides, should I make a list of changed IDs / add an internal note so we know which ones were changes?

**Comment by xhero** [comment]
There is also the template "libretto_edition_content" used in 18 sources, should it be left as-is?

**Comment by lpugin** [comment]
Libretto: we should change it to Libretto manuscript

**Comment by xhero** [comment]
Done in production
