### ISSUE TITLE
Verify translations against EN

### ISSUE THREAD

**Issue by xhero** [rism-ch/muscat#519]
There are various UPPERCASE terms still, particularly in DE and FR translations. It is a good moment to review them all (I will check IT translation).

**Comment by cgueggi** [comment]
pleas send me the link to the exact place in github, where it could be done

**Comment by xhero** [comment]
For 3.6.12:
https://github.com/rism-ch/muscat/blob/3.6.12-devel/config/locales/de.yml

**Comment by cgueggi** [comment]
German done. Some additional corrections also done.

Line 576: "HLS" = Abbreviation or to translate? To what?
Line 578: "ENG" = Abbreviation or to translate? To what?

**Comment by xhero** [comment]
I think HLS is the abbreviation of “Historisches Lexikon der Schweiz” while ENG is for English?

**Comment by cgueggi** [comment]
So I don't change anything

**Comment by xhero** [comment]
Ok I already updated test.

**Comment by cgueggi** [comment]
Please new update. Changed now "Vorschau vergeben" to "Vorschau verbergen" (as discussed on monday). Sorry, didn't see it this morning.

**Comment by xhero** [comment]
I would like to correct relator code "Contributer" to Contribut**_o_**r, any objections?
