### ISSUE TITLE
Analyze prints without date

### ISSUE THREAD

**Issue by xhero** [rism-ch/muscat#522]
circa 26000 prints have no date in 260 $c. I have a request to set it to "s.d" but before this we should make sure the date is not there is some other form (i.e. in the parent).
How to proceed?

**Comment by lpugin** [comment]
I don't like it. I would certainly not do it blindly on items in collections. Maybe only on single items? At the same time it does not bring anything so we could even leave it empty for now.

**Comment by cgueggi** [comment]
I would also leave it empty for now. I don't think that there are many dates in "some other form".
