### ISSUE TITLE
Titles not compliant with templates - 3.6.x edition

### ISSUE THREAD

**Issue by xhero** [rism-ch/muscat#526]
A followup on #336

**Comment by xhero** [comment]
This is the list of misplaced fields after the migration. I think we can correct them by hand?

1. **774**
	400065438 - source
	402005276 - source
	402005347 - source
	402006298 - source
	403010334 - source
	406002385 - source
	408000603 - source
	408001279 - source
	408002041 - source
	408002051 - source
	408002106 - source
	408002107 - source
	408002439 - source
	409000840 - source
	409003427 - source
	410001590 - source
2. **657**
	403011769 - collection
3. **651**
	407002648 - collection
	407002676 - collection
	407002683 - collection
	407002701 - collection
	407002711 - collection
	407002719 - collection

4. **031**
	409000222 - collection

**Comment by xhero** [comment]
These are tags that are NOT in the tag configuration, this means they are in the data but not shown or editable directly. They need to be migrated by hand and I will then drop them:

```
402006298: 110 2#$aDomchorarchiv$050007131
407002688: 533 ##$aHeliokopie.
407002691: 533 ##$aHeliokopie.
410000106: 110 2#$aKatholisches Pfarr- und Kirchgemeindearchiv, Fischingen TG$050006835
410001165: 110 2#$aAssociation Niedermeyer - Centre de documentation$050007932
```

**Comment by cgueggi** [comment]
657, 651 done
031: change template of 409000222 from collection to music manuscript
774: done. Change template of the following two IDs from music manuscript to collection: 402006298, 
406002385

**Comment by xhero** [comment]
Done for the three records! how should I proceed with the five records above?

**Comment by baccia** [comment]
Done the five remaining tags by hand.
