### ISSUE TITLE
Ungrouped tags become Unknown tags

### ISSUE THREAD

**Issue by xhero** [rism-ch/muscat#527]
Tags that always should be in a group, if are not in the group, end in the "unknown" tag list. I would make a separate group for them (ungrouped?) so to clarify they are two different things.

**Comment by xhero** [comment]
<img width="1009" alt="schermata 2017-09-20 alle 15 27 33" src="https://user-images.githubusercontent.com/1691778/30646145-4afcd99e-9e18-11e7-8fe2-e608742462d0.png">
Example of why this is annoying...

**Comment by lpugin** [comment]
Yes, this would be better. We should also look at having a cron job that check this.

**Comment by xhero** [comment]
Please have a look at the labels :)
