### ISSUE TITLE
Validate $0 entries

### ISSUE THREAD

**Issue by xhero** [rism-ch/muscat#53]
If the master is not generated in the editor saving will crash. This happens for example in an autocomplete filed when it is not filled. Eg if no Lib Siglum is inserted in the 852 it will generate the following MARC:

=852  ##$bSondersammlung$pMs.N.136:B.I.a.1.1$zNachlass Richard Rosenberg

the $0 is missing and it will crash on save.
Validation should be added to the field.

**Comment by lpugin** [comment]
Duplicates with #174
