### ISSUE TITLE
Holding show page is redirected to source_show

### ISSUE THREAD

**Issue by HirschSt** [rism-ch/muscat#537]
see https://github.com/rism-ch/muscat/blob/773e6a9679e7e6ef97b178193f0d0fdba44c513f/app/admin/holding.rb#L92

Any reason for this? The alternative section below is commented out.

Later a holding record can contain much more information than 852, so we should consider something of a show page of a holding record.

**Comment by xhero** [comment]
Originally holding records were not meant to be shown outside their bibliographical record, that's why it redicrects. We can change it if needed

**Comment by HirschSt** [comment]
Sounds reasonable, so we can stay with that for now. Thanks!
