### ISSUE TITLE
Space correction

### ISSUE THREAD

**Issue by lpugin** [rism-ch/muscat#545]
Felds :031$d - 245$a - 246$a - 300$a - 383$a - 500$a - 505$a - 518$a - 525$a - 561$a - 563 - 590$b - 691$n
* Add a wide space after: op. - p. - f. - vol. - pt. - suppl. - clm.
* Add a wide space before: p. - f.
* When „Suppl.“, replace with „suppl.“.

**Comment by xhero** [comment]
This issue was moved to rism-ch/muscat-maintenance#14
