### ISSUE TITLE
Correct slash

### ISSUE THREAD

**Issue by lpugin** [rism-ch/muscat#546]
Field: 031$d - 246$a - 500$a - 505$a - 525$a - 518$a - 561$a - 563
* Change " / " to  " | "

**Comment by xhero** [comment]
I can just do a gsub right? There should not be particular cases?

**Comment by cgueggi** [comment]
What's a gsub?
Be careful about the blanks befor and after the sign. This is absolutely urgent. Otherwise you'll change the superscript signs ;-)

**Comment by xhero** [comment]
global substitution :) I have already taken spaces in account ;)

**Comment by cgueggi** [comment]
Yeah sure you have. Just wanted to be sure... Sorry!

**Comment by xhero** [comment]
This issue was moved to rism-ch/muscat-maintenance#13
