### ISSUE TITLE
Move article at the end of the title

### ISSUE THREAD

**Issue by lpugin** [rism-ch/muscat#547]
Field:  240$a   -   730$a
Article has to move from the back (after the comma) to the front( Der,  Die,  Das,  Ein, Eine, La,  Le,  L‘,  Les,  Il,  Lo,  Gli,  El,  Las,  Los,  The,  A ...)
* Problem: capital letter in the text following:
 "Kleine Mädchen, Das" would become "Das Kleine Mädchen" instead of "Das kleine Mädchen")

* [x] Make a list with all: „, Der  „, „, Die„  and „, Das„ (@xhero)
* [x] Correct titles by hand (@baccia)
* [ ] Correct remaining titles automatically (@xhero)
* [ ] Verification (@baccia)

Additional remark: we should preserve the information in the indicator, namely the number of character to ignore for sorting. See http://www.loc.gov/marc/bibliographic/bd130.html).

**Comment by xhero** [comment]
Shouldn't we do this in the StandardTitle and then re-save the sources?

**Comment by lpugin** [comment]
Yes, this is the right way to do it. The only question is then with the indication. Ideally is should be in the authority too. This is actually similar to the $d for people, even though we do not have this implemented with and indicator. Any thoughts?

**Comment by xhero** [comment]
I think there is no support for this currently, the indicator is always fixed. We would need to change the backend.

**Comment by xhero** [comment]
Here are the titles. The first two columns are for me, then there is the original and the modified version. On column E just place a "1" and the script will lowercase the second word of the modified version, eg:

`Le Due contesse => Le due contesse`

On column F if the entry needs to be rewritten, for example an error in the conversion:

`eleison Kyrie => Kyrie, eleison (should not happen!)`

Column F has the precedence over E, so if set the 1 will be ignored

[titles.xlsx](https://github.com/rism-ch/muscat/files/1744217/titles.xlsx)

**Comment by xhero** [comment]
For the backend: we need to add a partial when std_titles are created so the indicator 1 can be entered, and shown when selected from the autocomplete. resolve_externals should be verified to take care of the indicators, and verify that the editor passes them correctly.

**Comment by baccia** [comment]
Here are the corrected titles.
[547_titles.xlsx](https://github.com/rism-ch/muscat/files/1936922/547_titles.xlsx)

**Comment by xhero** [comment]
This issue was moved to rism-ch/muscat-maintenance#12
