### ISSUE TITLE
Change autograph collections 593 and remove 700

### ISSUE THREAD

**Issue by lpugin** [rism-ch/muscat#548]
For collections with a composer where all the items are "Autograph manuscript" in 593 $a:
* Change the 593 $a of the collection to "Autograph manuscript"
* Remove the 700 where the person is the same as the composer and relator code is "Schreiber"
Example: http://www.rism-ch.org/catalog/400102777, http://www.rism-ch.org/catalog/400107252

**Comment by xhero** [comment]
To get that a collection has only 1 composer I trust the presence of 100? Or we can have the case that the collection has 100 and then sources by different composers?
When I open the single items, should I consider also the ones that are only "Autograph"?

**Comment by xhero** [comment]
Small list, I think unrelated to this, maybe the Anonymous should be fixed?

```
402006298: expected Anonymus found Danby, John
402006298: expected Anonymus found Schmidt, Johann Philipp Samuel
406000970: expected Munzinger, Edgar found
406001593: expected Fröhlich, Friedrich Theodor found
407001151: expected Huber, Ferdinand Fürchtegott found
407001151: expected Huber, Ferdinand Fürchtegott found
407001269: expected Huber, Ferdinand Fürchtegott found
407001269: expected Huber, Ferdinand Fürchtegott found Kreutzer, Conradin
407001323: expected Huber, Ferdinand Fürchtegott found
408001438: expected Anonymus found
408001438: expected Anonymus found
408001438: expected Anonymus found
408001438: expected Anonymus found
408001438: expected Anonymus found
408001572: expected Anonymus found
408001572: expected Anonymus found
408002339: expected Anonymus found
408002339: expected Anonymus found
408002339: expected Anonymus found
410001727: expected Niedermeyer, Louis Abraham found Bellini, Vincenzo
410001942: expected Niedermeyer, Louis Abraham found
410001942: expected Niedermeyer, Louis Abraham found
```

**Comment by xhero** [comment]
Just for completeness, these are collections with no 100 but only one author in them

```
400056063 Stierlin, Ambrosius
400150012 Diener, Olga
402009693 Dittersdorf, Karl Ditters von
404000347 Zech, Markus
406003316 Dreyer, Johann Melchior
408000411 Vanhal, Johann Baptist
409000058 Neumann, Fritz
409000884 d'Alessandro, Raffaele
409000920 d'Alessandro, Raffaele
409000979 d'Alessandro, Raffaele
409001010 d'Alessandro, Raffaele
409001038 d'Alessandro, Raffaele
409001103 d'Alessandro, Raffaele
409001128 d'Alessandro, Raffaele
409001150 d'Alessandro, Raffaele
409001174 d'Alessandro, Raffaele
409001185 d'Alessandro, Raffaele
409001197 d'Alessandro, Raffaele
409001206 d'Alessandro, Raffaele
409001612 Roelli, Hans
409003553 Dittersdorf, Karl Ditters von
410002605 Juon, Paul
410004255 Reichel, Adolf
410004892 Gluck, Christoph Willibald
410005896 Laquai, Clara
```

**Comment by lpugin** [comment]
> Just for completeness, these are collections with no 100 but only one author in them

It seems that the collection should get a 100

**Comment by lpugin** [comment]
Previous list, we have various cases. For example,

> 402006298: expected Anonymus found Danby, John
402006298: expected Anonymus found Schmidt, Johann Philipp Samuel

means that 402006298 is a collection with multiple composers.

It should be easy to correct them by hand. @cgueggi : who do you want to do this?

**Comment by xhero** [comment]
Another thing: 593 is the material groups, should all the groups have "autograph" for the collection to become autograph too?

**Comment by lpugin** [comment]
As I said, if all the child sources have at least one material group being Autograph, then the collection should be Autograph. @cgueggi OK?

**Comment by xhero** [comment]
These are all the collections that have two or more material groups, and have children with one or more Autographs inside. I think is it better to fix them by hand so the material groups can be matched

```
400100616
400100622
400100630
400100633
400100699
400100734
400100900
400100920
400101160
400101171
400101179
400101196
400101309
400101343
400101372
400101375
400102080
400108584
400109036
400150233
401000227
401000236
401000245
401000310
401000706
402005033
402005088
402005096
402005100
402005107
402005144
402005265
402005513
402005543
402005553
402005598
402005629
402005944
402005947
402005972
402006952
402007094
402009504
402010174
402010272
402010539
402010846
403000268
403000280
403013518
403013686
403013697
403013947
405000509
405000557
405000561
405000566
405000641
405000693
405000700
405000704
405000719
405000743
405000752
405000920
406000051
406000062
406000106
406000165
406000173
406000183
406000191
406000198
406000239
406000259
406000278
406000516
406000622
406000625
406000630
406000658
406000847
406000894
406000974
406001233
406001402
406001795
407001364
407001379
407001386
407002770
407003065
407003082
407003145
407003166
408003492
409000138
409000184
409000763
409000822
409000847
409002529
409003259
410001264
410001289
410003162
410003170
410003353
410003359
410003487
410003608
410004872
410004884
410004992
410005038
410005453
410005537
410006058
```

**Comment by cgueggi** [comment]
@lpugin The collection should have as many material groups as the children
@xhero Corrections by hand is ok for me. Please assign Claudio for that

**Comment by xhero** [comment]
> 
> @lpugin The collection should have as many material groups as the children

Another thing to check ;)

**Comment by lpugin** [comment]
I was not aware of this... Yes, definitely to check.

**Comment by baccia** [comment]
OK, I’ll go through the lists.

> On 22 Feb 2018, at 09:47, cgueggi <notifications@github.com> wrote:
> 
> @lpugin The collection should have as many material groups as the children
> @xhero Corrections by hand is ok for me. Please assign Claudio for that
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Dr. Claudio Bacciagaluppi

Swiss RISM Office
Hallwylstrasse 15
PO box 286
CH-3000 Bern 6

Tel. +41 (0)58 465 03 59
Mob. +41 (0)76 503 30 71
e-mail: claudio.bacciagaluppi@rism-ch.org
www.rism-ch.org

(working days: Monday, Tuesday)

**Comment by xhero** [comment]
I made a text list of all the collections that have a different number of 593 in respect to the children. How should we proceed? I can do automatically when there is a 1:1 correspondence surely.

[collecion_multiple_593_multi_child.txt](https://github.com/rism-ch/muscat/files/1763290/collecion_multiple_593_multi_child.txt)

**Comment by baccia** [comment]
Thanks for the list! As far as I have seen, I must go through them by hand. In some instances, no correction is necessary: e.g., when one material group is a score, and another one are parts for one only of the works in the collection. In other instances, the material groups in the parent record have to be sorted out again because the ‘autograph’ category was only used in the child records.

> On 27 Feb 2018, at 15:44, xhero <notifications@github.com> wrote:
> 
> I made a text list of all the collections that have a different number of 593 in respect to the children. How should we proceed? I can do automatically when there is a 1:1 correspondence surely.
> 
> collecion_multiple_593_multi_child.txt
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Dr. Claudio Bacciagaluppi

Swiss RISM Office
Hallwylstrasse 15
PO box 286
CH-3000 Bern 6

Tel. +41 (0)58 465 03 59
Mob. +41 (0)76 503 30 71
e-mail: claudio.bacciagaluppi@rism-ch.org
www.rism-ch.org

(working days: Monday, Tuesday)

**Comment by baccia** [comment]
Checked by hand: collections with varying number of groups between parent and children; collections with no 100 but only one author; collections with 100 but different authors.

**Comment by baccia** [comment]
In other words, @xhero: now you can proceed automatically with all collections with only one 593='manuscript' and 100=700 'copyist'.

**Comment by xhero** [comment]
This issue was moved to rism-ch/muscat-maintenance#1
