### ISSUE TITLE
Missing superscript sign

### ISSUE THREAD

**Issue by lpugin** [rism-ch/muscat#549]
Field: 031$d - 245$a - 246$a - 300$a - 500$a - 505$a - 518$a - 525$a - 561$a - 563
* Number of letters as superscript not always coded according to the guidelines
Example: (1|er) http://www.rism-ch.org/catalog/400187650 (Not sure this is the correct example)

* [x] Make a list of possible term to search (@cgueggi)
* [ ] Apply the correction (@xhero)

**Comment by cgueggi** [comment]
Quite difficult to make a list with terms to search for. Could be anything. Would it be a possible way to make a list with all "|" (without blank) in the stated fields and have a look on that on screen (paper)? Maybe it's not that much.

**Comment by xhero** [comment]
I am not 100% sure the list is 100% accurate, but these are the superscripts with more characters after | as in @lpugin 's example.

[superscripts.xlsx](https://github.com/rism-ch/muscat/files/1740636/superscripts.xlsx)

**Comment by cgueggi** [comment]
Seems quite accurate. How do we proceed? Can it be done automatically?

**Comment by xhero** [comment]
I can try to scaffold a script...

**Comment by xhero** [comment]
These are the substituted values. Look good to me. Can you double check?
[substituted.xlsx](https://github.com/rism-ch/muscat/files/1743328/substituted.xlsx)

**Comment by cgueggi** [comment]
I double checked. There are some missing corrections (see attached list). In some cases only one out of two or more superscript signs were changed. Shall I do it manually?
- 402014328 and 410005538 were other problems. -> manually solved
- 10 marked entries in orange: only one superscript sign was right (old german spelling for mutated vowel, f. e. u|e = ü). Maybe to discuss
[substituted CG.xlsx](https://github.com/rism-ch/muscat/files/1747157/substituted.CG.xlsx)

**Comment by xhero** [comment]
This issue was moved to rism-ch/muscat-maintenance#11
