### ISSUE TITLE
Renaming 300$a values

### ISSUE THREAD

**Issue by lpugin** [rism-ch/muscat#551]
Replace:
* "piano score" with: "keyboard score" + Plural!  
* "short score (piano score)" with : "keyboard score" + Plural!
* "short score (particella)" with: "particella" + Plural!
* "short score (vocal score)" with: "vocal score" + Plural!

Possible repeated field!
http://www.rism-ch.org/catalog/402005369, http://www.rism-ch.org/catalog/403013051

**Comment by xhero** [comment]
How should I apply the plural? Is there an indication that it should be?

**Comment by cgueggi** [comment]
It's just the plural-s at the end:
"piano scores" -> "keyboard scores"
"short scores (vocal score)" - "vocal scores"
What about particella? Is there an example with more than one? What is sungular, what is plural?

**Comment by xhero** [comment]
particella**s** or particell**e** (english or italian plural)?

**Comment by xhero** [comment]
There are also a couple strange ones:

```
short scores (2x/piano score)
2 short scores (piano score and particella): 28, 12p.
2 short scores (piano score): 3, 3p.
1 short score (piano score/choruses 2 and 4): 15p.
4 short scores (piano score/2x and choral score/2x): 44, 44, 20, 20p.
```

What should it become? Or should I change just the ones that exactly match, like `1 short score (piano score)` ?

**Comment by cgueggi** [comment]
particellas/particelle: Was my question, too. Guidelines not clear, ask ZR?!

**Comment by cgueggi** [comment]
Please give me the IDs of the "strange ones"

**Comment by xhero** [comment]
A couple ones (do you want a full list?)

```
400109049 - 4 short scores (piano score/2x and choral score/2x): 44, 44, 20, 20p
400101301 - 14 short scores (piano score): 4, 5, 3, 5, 7, 5, 1, 6, 2, 2, 4, 2, 2, 6p.
400107034 - 1 short score (piano score/choruses 2 and 4): 15p.
400039288 - 2 short scores (2x/piano score)
```

**Comment by cgueggi** [comment]
The four "strange ones" are done (changed entries)

**Comment by xhero** [comment]
Do you need the full list? That is 4 out of a couple thousand.

**Comment by cgueggi** [comment]
Ooops, really? Ok, make the list please. I'll have a look and will decide how to proceed

**Comment by jenniferward** [comment]
English plural, please!

**Comment by xhero** [comment]
This issue was moved to rism-ch/muscat-maintenance#9
