### ISSUE TITLE
Translate terms in 518a

### ISSUE THREAD

**Issue by lpugin** [rism-ch/muscat#554]
Translate to German or French according to 040$b)
"Performance date:" as "Aufführung:" or "Représentation:"
"First performance date:" as "Uraufführung:" or "Première représentation:"

**Comment by xhero** [comment]
Is this right? The autocomplete only had english terms in it

**Comment by lpugin** [comment]
Yes, it looks right to me.

**Comment by xhero** [comment]
This issue was moved to rism-ch/muscat-maintenance#6
