### ISSUE TITLE
Rename 593 with new values

### ISSUE THREAD

**Issue by lpugin** [rism-ch/muscat#556]
List of equivalences to be provided by @cgueggi

**Comment by xhero** [comment]
I need the list ;)

**Comment by xhero** [comment]
Easy peasy (I hope!!) Here are the current values:

```
Autograph
Autograph manuscript
Libretto, printed
Manuscript
Manuscript copy
Manuscript copy with autograph annotations
Manuscript with autograph annotations
Other
Partial autograph
Possible autograph manuscript
Print
Print with autograph annotations
Print with non-autograph annotations
Probably autograph
Treatise, handwritten
```

**Comment by cgueggi** [comment]
Indeed it is easy peasy ;-)

Autograph -> Autograph manuscript
Autograph manuscript -> Autograph manuscript
Libretto, printed -> Libretto, printed
Manuscript -> Manuscript copy
Manuscript copy -> Manuscript copy
Manuscript copy with autograph annotations -> Manuscript copy with autograph annotations (change guidelines? It says: Manuscript with autograph annotations [without "copy"], but in the dropdown list it is with "copy"
Manuscript with autograph annotations -> see above
Other -> Other
Partial autograph -> Partial autograph
Possible autograph manuscript -> Possible autograph manuscript
Print -> Print
Print with autograph annotations -> Guidelines vs. dropdown!
Print with non-autograph annotations -> Guidelines vs. dropdown!
Probably autograph -> Possible autograph manuscript
Treatise, handwritten -> Treatise, handwritten

**Comment by xhero** [comment]
This issue was moved to rism-ch/muscat-maintenance#4
