### ISSUE TITLE
Show new tag/subfield entries on marc configuration page

### ISSUE THREAD

**Issue by HirschSt** [rism-ch/muscat#558]
Because we had added some new fields in the marc-configuration (esp. sources and catalogue), is there any objection to give them some sort of a special mark for identifieing them easily on the configuration show page? See below or http://beta.rism.info/admin/doc

![image](https://user-images.githubusercontent.com/6461776/34993355-5933858e-fad0-11e7-9cf6-a6f6d2d5f9f7.png)

It can be done as key-value pair at the subfield, eg:

  ```
"563":
    :master: u
    :indicator: "##"
    :occurrences: "*"
    :fields:
    - - a
      - :occurrences: "?"
    - - u
      - :occurrences: "?"
        :new: 2018
    - - "8"
      - :occurrences: "?"
        :no_browse: true


```

**Comment by xhero** [comment]
I would place this in Labels.yml and not tag_config as it seems more appropriate since it is related to view

**Comment by HirschSt** [comment]
Yes, that's much better, I will do it this way. Thanks!
