### ISSUE TITLE
Filtering by date yield weird "Search Status"

### ISSUE THREAD

**Issue by lpugin** [rism-ch/muscat#559]
![image](https://user-images.githubusercontent.com/689412/34994855-1817c434-fad5-11e7-98a1-b7ff1b0f680c.png)

**Comment by xhero** [comment]
The fix is quite and ugly monkey-patch, and affects only the elements that correspond to a DB record (created_at, updated_at). The others show but untranslated. It seems to be a bug in AA.

**Comment by xhero** [comment]
https://github.com/activeadmin/activeadmin/issues/5329

I opened a ticket for AA. Will put this one in the wishlist
