### ISSUE TITLE
Version history does not show up

### ISSUE THREAD

**Issue by lpugin** [rism-ch/muscat#560]
Clicking on the version history for a sources does not show anything. jQuery related?

**Comment by xhero** [comment]
It seems the model no longer respond to paper_trail_enabled_for_model?, or paper trail is not enabled for some reason

**Comment by lpugin** [comment]
I am confused. I now works (locally) on 3.7.0-mergall but not on the (232 server).

**Comment by xhero** [comment]
You need 3.7.0-gem-upgrade to break it :) mergeall is stil AA 1.0

**Comment by lpugin** [comment]
OK. It seems to work with paper_trail 5.0 but not 6.0 or greater (currently 8.0). Should we just stick with 5.0 for now and upgrade it later with rails 5 and BL ?

**Comment by lpugin** [comment]
Issue fixed with d216f7553d92e560c6f66ffd42e82c6d622f7aca

To be updated later (#565)
