### ISSUE TITLE
Saving error with person

### ISSUE THREAD

**Issue by lpugin** [rism-ch/muscat#563]
Creating an new Person, searching VIAF and selecting a values (without additional) edition crashes when saving

**Comment by HirschSt** [comment]
@xhero which branch? Probably writing an rspec testing this is desirable.

**Comment by xhero** [comment]
-gem-update, yes a rspec would be fantastic!

**Comment by xhero** [comment]
I can't reproduce this - what exactly should I do?

**Comment by lpugin** [comment]
Can't anymore either...
