### ISSUE TITLE
Change English for printed edition terms

### ISSUE THREAD

**Issue by jenniferward** [rism-ch/muscat#568]
Looking at: http://prints.rism.info/admin/holdings/new?source_id=1517060

Please change "New Holding" to "New holdings information"

Please change "Preserved Parts" to "Material held"

[unspecified] on the right under "Sections and actions" can be "Administration", right?

**Comment by xhero** [comment]
I applied the changes, how should "New holdings information" be shown in DE translation>

**Comment by jenniferward** [comment]
Martina will be joining us on GitHub soon! Then she can answer :)

**Comment by MFalletta** [comment]
Ja bitte: "Neuer Exemplareintrag" und "Erhaltenes Material" - wie bisher
