### ISSUE TITLE
BL: Searching for siglum not consistent

### ISSUE THREAD

**Issue by jenniferward** [rism-ch/muscat#570]
In http://muscat.rism.info/admin/sources you have to search for **B-*** in order to get all sources from Belgium.

In http://muscat.rism.info/admin/institutions a search for **B-*** has 0 results. Here, you have to search for 
 **B-** .

Can this be made consistent? It would be better to use the * to truncate throughout.

**Comment by HirschSt** [comment]
Not closed because of some BL stuff; reindex of institutions needed
