### ISSUE TITLE
Deleting a Catalogue with no source fails

### ISSUE THREAD

**Issue by lpugin** [rism-ch/muscat#573]
Is says "The catalogue could not be deleted because it is used by 0 sources, 0 institutions, 0 catalogues and 1 people". 

Is the Person using the catalogue, or is it its author?

(Set to 3.7.1)

**Comment by xhero** [comment]
A partial fix is in 92e08ac3cbc66bdbe650e8a8df4b6667255eae2c, a dedicate branch is made to add the relevant interface pieces

**Comment by xhero** [comment]
This is related to #465 - show other link types in the auth files, now it works only with sources

**Comment by xhero** [comment]
Also related to #543
