### ISSUE TITLE
Improving source validation

### ISSUE THREAD

**Issue by HirschSt** [rism-ch/muscat#577]
This is the basic set we have with latest 3.7 953f15a:
mandatory: 240a, 245a, 650a, 852a, 852c
required: 031, 240m, 100a, 260c, 300a, 593a, 594a

Since some fields should be mandatory depending on their template (eg 100 mandatory with 002 source, required with 000 collection) I have set them to required for now to be on the safe side, so we could do refinement later by adding more sophisticated validation (eg Holding records).

**Comment by jenniferward** [comment]
Is it possible for ZR staff to have the rights to bypass validation (i.e., we continue clicking to save despite red warnings)? This would be convenient when focusing on certain types of corrections.

**Comment by xhero** [comment]
I would prefer not, as all the red validation issues could potentially insert invalid data in the system and/or render that particular source uneditable

**Comment by HirschSt** [comment]
Aside from this maintaining different validation systems due to the user role is obviously a nightmare.

**Comment by HirschSt** [comment]
Since we are on a way to a more clever validation for all marc classes this issue can be closed
