### ISSUE TITLE
Change filter Status / In Progress

### ISSUE THREAD

**Issue by jenniferward** [rism-ch/muscat#580]
Here http://muscat.rism.info/admin/sources it looks like unpublished records are marked UNP in the column "Status." However, in the drop-down menu for the filter "Status", the option is called "In progress". Can you please change this to "Unpublished" so that it matches UNP?

**Comment by lpugin** [comment]
I would suggest instead to add UNP in (). This will work better with translations. So it would be "In progress (UNP)" and "In Arbeit (UNP)" for German. OK?

**Comment by jenniferward** [comment]
I'd rather have it be consistent, because it's just easier to explain to users, and unpublished/published is cleaner than in progress/published. Would it be better if the German was "Unveröffentlicht"? 

This has made me wonder if it would make sense to add (MSR) (COL) etc. to the Template Types in the filters. I admit I get lost sometimes with the colors and abbreviations.

**Comment by jenniferward** [comment]
Yes, the abbreviation in parens completely makes sense, for English too.
