### ISSUE TITLE
Cropped rendering incipits with Firefox 52.*

### ISSUE THREAD

**Issue by HirschSt** [rism-ch/muscat#583]
![image](https://user-images.githubusercontent.com/6461776/35576412-2dc73b60-05df-11e8-9dbc-42f3b5b28bca.png)

Can be reproduced with Firefox 52*; at the moment my advice is to use Firefox 58 or Chrome instead.

**Comment by lpugin** [comment]
This is an old bug in Firefox that was now apparently corrected. A possible fix (CSS) is provided here
https://github.com/rism-ch/verovio/issues/79
https://github.com/rism-ch/verovio/issues/138

**Comment by HirschSt** [comment]
Thanks for this, I think using a more recent version of firefox would the best fix...
