### ISSUE TITLE
Strange fulltext index

### ISSUE THREAD

**Issue by HirschSt** [rism-ch/muscat#584]
Seach for "450201065"

With Index filter **120 hits** (worse and different to 3.6): 
http://muscat.rism.info/admin/sources?utf8=%E2%9C%93&q%5Btitle_equals%5D=450201065&commit=Filtern&order=id_desc

With Catalog **2 hits** (better): http://muscat.rism.info/catalog?utf8=%E2%9C%93&search_field=any_field&q=450201065

Any idea?

**Comment by xhero** [comment]
This was due because by default the fulltext search would try to match also the incipit data, I excluded it from the search in AA. In BL it was already disabled.

**Comment by xhero** [comment]
I have pushed the mod in testing and I too see only two items in both interfaces (ms and coll). If you can test this too I would close.

**Comment by HirschSt** [comment]
Now I understand (due to incipit search) the results...I have tested the commit: it's perfect now, thanks!
