### ISSUE TITLE
source.id should not be set to source.source_id

### ISSUE THREAD

**Issue by xhero** [rism-ch/muscat#585]
A record cannot be the parent of itself. We need to add

- [ ] Database constraint
- [x] Active record constraint
- [x] relative interface items to warn/block the user

**Comment by HirschSt** [comment]
I think we can add an AR validation which raises a "could not be saved" message too.

**Comment by xhero** [comment]
I would dor the other parts of the ticket in 4.1

**Comment by lpugin** [comment]
Agree. We should release 4.0.1 with what we have an improve it later without rushing.

**Comment by xhero** [comment]
MySQL does apparently does not support this kind of constraint, I think the AR constraint added by @HirschSt should be enough. Was the data all fixed?
