### ISSUE TITLE
.xml returns 401 Unauthorized

### ISSUE THREAD

**Issue by xhero** [rism-ch/muscat#587]
Seems related to AA 1.2

**Comment by lpugin** [comment]
It would also be good to have .xml for other marc models

**Comment by HirschSt** [comment]
Probably a security issue, for myself I am taking SRU as a workaround (eg http://muscat.rism.info/sru/sources?operation=searchRetrieve&version=1.1&query=id=000051755&maximumRecords=1)

**Comment by xhero** [comment]
It seems an AA issue.

**Comment by xhero** [comment]
AA 1.2 enables XML download only when :download_links is true, apparently there is no way to override this (https://github.com/activeadmin/activeadmin/blob/master/lib/active_admin/resource_controller.rb#L52). The solution right now is to show the download_links.

**Comment by xhero** [comment]
@HirschSt do we need a spec on these?
