### ISSUE TITLE
Prints: Muscat sources-index after changing a siglum not up to date

### ISSUE THREAD

**Issue by Docudoctor** [rism-ch/muscat#588]
Dear colleagues, 
after changing a siglum in 98 A/I-records the search result in the Muscat sources-index is not up to date. That means I have not received the changed 98 A/I-recvords after a search for the new siglum, but for the former one, which is not present anymore in the print records. I changed SK-Mms into SK-Msnk.  

Best,
Guido

**Comment by Docudoctor** [comment]
See also in institutions the sigla with the suffix "duplicate" and the linked sources. Same problem.
Best,
Guido

**Comment by lpugin** [comment]
This is quite likely a reindexing that is not triggered for holdings

**Comment by xhero** [comment]
I added the reindex for the holding records for 4.0.2.But we still need to update the view to actually see them. This is for 4.1 and the new related view boxes

**Comment by HirschSt** [comment]
Can you give me a hint concerning the "view boxes"?
