### ISSUE TITLE
Remove role cataloger_prints

### ISSUE THREAD

**Issue by HirschSt** [rism-ch/muscat#590]
After the testing period of 4.0 we could drop this special role and give the templates to all catalogers.

**Comment by xhero** [comment]
Did we remove this?

**Comment by HirschSt** [comment]
Not now, because all print members are part of this role. But cataloger has the same rights, so I can drop it after User.where(role: cataloger_prints).each {|user |user.update(role: cataloger)}

**Comment by HirschSt** [comment]
Resolved with 9507be90c1c4c0ee5f1b6c697b2e1e81068dbd52
