### ISSUE TITLE
Clear designation of local fields

### ISSUE THREAD

**Issue by jenniferward** [rism-ch/muscat#591]
On this page:
http://muscat.rism.info/admin/doc
It would be helpful for external users if Muscat clearly documented the fields that are local fields in Muscat. We have [NEW IN 2018]; I would suggest [local field] .

On that page (and in the menu link), could you also please write MARC instead of Marc?

**Comment by HirschSt** [comment]
These comments only should be used to indicate changes/additions to the marc configuration, other explanation should be made in the guidelines.

**Comment by jenniferward** [comment]
The configuration page is a convenient way for people to get an overview of the MARC implementation in Muscat. Non-RISM people sometimes ask about the MARC configuration and I point them there (in the training server). This is important for people when evaluating the possibility of data transfers or other use of the data and local fields should be made clear. The guidelines are quite dense and are not meant to be a resource for technical specifications, but if this is the only option then I will add them somewhere. What are the local fields? 59X, 69X, any others?
