### ISSUE TITLE
Duplicates in filter "Source type" 

### ISSUE THREAD

**Issue by jenniferward** [rism-ch/muscat#592]
"Manuscript copy", "Print", "Libretto, printed" are duplicated in the "Source type" drop-down menu, with different results for each search.

**Comment by lpugin** [comment]
This is a capitalization issue in the data (we have 'Print' and 'print'). This have to be fixed in maintenance task. See the list here
http://muscat.rism.info/catalog/facet/593a_filter_sm?facet.sort=index&q=&search_field=any_field&utf8=%E2%9C%93

**Comment by xhero** [comment]
Unfortunately the search is case sensitive. I would still run a fixing script but we can add a custom field in SOLR which is only lowercase and only for this field. It requires some extensive testing so I would leave this for 4.1

**Comment by xhero** [comment]
Unless this is a priority I would move it to the wishlist

**Comment by jenniferward** [comment]
I would like it to be fixed at some point because it is confusing for contributors - "manuscript copy" and "print" are two source types in particular that are likely to be searched. Once prints are open to all contributors, more and more will want to search for prints only and they might get incorrect results if they don't know to search twice. But it's not a priority for me.

**Comment by jenniferward** [comment]
Our Dresden colleagues just reported that the doubled "Print" in the Source Type makes searching difficult.

**Comment by xhero** [comment]
This is fixed in -test!
