### ISSUE TITLE
v4.0 - Error in Statistics when no Institutions

### ISSUE THREAD

**Issue by iwascraig** [rism-ch/muscat#598]
When installing a new database, do migrations then seed database.
Add a new workgroup and user then go to Statistics page get an error.

./lib/statistics/institutions.rb line #23 is hardcoded to lookup institution with id=5 if there are no returned from the main query.

**Comment by xhero** [comment]
@HirschSt could you have a look here? It would be probably better not to have hardcoded ids in the statistics :)
