### ISSUE TITLE
Reindex sources through UI doesn't process due to PaperTrail version issue

### ISSUE THREAD

**Issue by shaunmuscat** [rism-ch/muscat#599]
In Muscat v4.0.1 (PaperTrail version 5) when selecting to reindex sources through the active admin UI, jobs remain enqueued and don't get processed. Inspection of the development console reveals the following error with Paper Trail.

```
D, [2018-02-12T16:55:04.600059 #78993] DEBUG -- : 
D, [2018-02-12T16:55:04.600208 #78993] DEBUG -- : 
I, [2018-02-12T16:55:04.600373 #78993]  INFO -- : Started GET "/progress-job/10" for 127.0.0.1 at 2018-02-12 16:55:04 +1100
I, [2018-02-12T16:55:04.608135 #78993]  INFO -- : Processing by ProgressJob::ProgressController#show as */*
I, [2018-02-12T16:55:04.608205 #78993]  INFO -- :   Parameters: {"job_id"=>"10"}
D, [2018-02-12T16:55:04.609380 #78993] DEBUG -- :   Delayed::Backend::ActiveRecord::Job Load (0.5ms)  SELECT  `delayed_jobs`.* FROM `delayed_jobs` WHERE `delayed_jobs`.`id` = 10 LIMIT 1
D, [2018-02-12T16:55:04.611365 #78993] DEBUG -- :   User Load (0.3ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 2  ORDER BY `users`.`id` ASC LIMIT 1
I, [2018-02-12T16:55:04.611949 #78993]  INFO -- : Completed 200 OK in 4ms (Views: 0.1ms | ActiveRecord: 0.8ms | Solr: 0.0ms)
/Users/shaun/.rvm/gems/ruby-2.3.0@muscat/bundler/gems/progress_job-b085abb0983e/app/controllers/progress_job/progress_controller.rb:
user_for_paper_trail is present, but whodunnit has not been set.
PaperTrail no longer adds the set_paper_trail_whodunnit callback for
you. To continue recording whodunnit, please add this before_action
callback to your ApplicationController . For more information,
please see https://git.io/vrTsk
```

This error gets shown each time the application attempts to process the job. 

Apparently this is due to upgrading to PaperTrail version 5 without adding a whodunnit tracking callback https://github.com/airblade/paper_trail/blob/master/doc/warning_about_not_setting_whodunnit.md

**Comment by xhero** [comment]
This is strange, as that should be a warning and do no harm. Indeed in muscat production (with 4.0.1) jobs do run if I select them. What is written in the DB for the failed jobs?

**Comment by shaunmuscat** [comment]
I checked the db and the jobs weren't being processed. After further inspection it seems the cause of this was the delayed job worker terminated and wasn't re-initialised. After starting it back up the jobs are running fine with the PaperTrail warning. Apologies, closing ticket since it is no longer an issue.

**Comment by xhero** [comment]
No problem, updating paper_trail (and finally suppressing the warning) is on track for 4.1
