### ISSUE TITLE
Change fields in non coded drop-down lists

### ISSUE THREAD

**Issue by xhero** [rism-ch/muscat#608]
Some dropdown menus contain "real" data and not coded data (i.e. 593 in sources or 550 in people). While changing the elements is possible, the data should be updated alongside.

**Comment by jenniferward** [comment]
You can delete the misspelled term "unkown" from the 042. (I forgot to include it on the list.) It was not an option in Kallisto and Alexander hasn't been using it, so it shouldn't be in too many records, if at all.

**Comment by jenniferward** [comment]
The ZR doesn't need the drop-down list in 550 $i in Personal Names at all. Alexander always only used "profession". We are in favor of simply deleting it. Is there a reason to keep it?

**Comment by xhero** [comment]
I fixed "unkown", but there are 4 people (30019369, 41009752, 41009765, 41010264) that have it in 042 (41010264 in 550). I guess they can be fixed by hand.
I can delete the 550 $i, but it appears there are 77815 person records that use it, I think we need a script to fix them

**Comment by jenniferward** [comment]
Thanks for fixing it!
Alexander corrected the people and confirmed that 550 $i can really and truly be deleted.

**Comment by HirschSt** [comment]
It's not so easy, because $i defines the relationsship of the $a topic; so if there is any description in 550 it should be explained - at least for the VIAF export - in $i.
