### ISSUE TITLE
Add RepertoriumSchweiz to Reichel

### ISSUE THREAD

**Issue by xhero** [rism-ch/muscat#610]
Add in all entries where "Reichel, Adolf (1816-1896)" is the composer (100) the literature note "RepertoriumSchweiz" in 691$a.

**Comment by cgueggi** [comment]
What is the status in this matter?

**Comment by xhero** [comment]
[Here you go!](http://www.rism-ch.org/admin/sources?utf8=%E2%9C%93&q%5Bcomposer_contains%5D=Reichel%2C+Adolf&q%5Btitle_equals%5D=RepertoriumSchweiz&commit=Filtra&order=id_desc)
