### ISSUE TITLE
Improve holding display in source show

### ISSUE THREAD

**Issue by lpugin** [rism-ch/muscat#612]
There are some issues with the display of the holdings in source show. We should probably have a marc_editor_summary_show

This was planned for sources but not fully implemented. The idea there was to have a summary of the source content to be shown from the holding (basically the opposite situation).

**Comment by xhero** [comment]
Is this related to the show in Blacklight or in AA? Blacklight show was quite improved for 5.0

**Comment by lpugin** [comment]
This was more for AA. But we can close it for now
