### ISSUE TITLE
040 $b Auswahlmenu erstellen

### ISSUE THREAD

**Issue by MFalletta** [rism-ch/muscat#616]
Auswahlmenu für die Angabe der Sprache der Bemerkungen einrichten.
Für engliche Oberfläche: English, German, French, Spanish, Italian 
Für deutsche Oberfläche: Englisch, Deutsch, Französisch, Spanisch, Italienisch

**Comment by HirschSt** [comment]
done with https://github.com/rism-ch/muscat/commit/ecbca5b6db4628b50f7d97b24795522428b4453d
