### ISSUE TITLE
Record Actions - Record Origin

### ISSUE THREAD

**Issue by MFalletta** [rism-ch/muscat#618]
Entgültige Entscheidung zu:
https://github.com/rism-ch/muscat/issues/569

Bitte drei verschiedene Auswahlmenus erstellen:

[599 $b]
Origin / Herkunft 
RISM

Retrospective conversion / Retroeinspielung

Import / Fremddateneinspielung

[599 $c]
Cataloging level / Erfassungstiefe
Full / Vollkatalogisat
Standard / Standard
Brief / Kurzkatalogisat

[599 $d]
Material examined? / Autopsie?
-- / --
Yes / Ja

**Comment by jenniferward** [comment]
What is the status of this? Our Dresden colleagues have asked about it.

**Comment by HirschSt** [comment]
Since internal remarks 599 should be excluded from the export, the datafield must be changed to another one. Please give me a proposal.

**Comment by jenniferward** [comment]
A 9xx local field would be the most flexible. 

Leader 17 with some redefinition or local fields would cover $c and $d. 

For $b: 987 is used for converting from Chinese-character records and is in use by [OCLC and LC](https://www.oclc.org/bibformats/en/9xx/987.html), so perhaps something in the 98x range would be appropriate. 

Dresden wants to be able to mark when a record was created in RISM (RISM), when it was imported from the books (Retrospective conversion), or when it was imported from other data sources (import). I think there is an assumption and expectation that this field would be automatically added to the RISM data in the course of a data transfer (whether from the B books or from imported MARC records), or even retrospectively added to the existing A/I and B/I records.

**Comment by HirschSt** [comment]
980 looks fine for me, so I would suggest the following:

[980 $a]
Origin / Herkunft
RISM
Retrospective conversion / Retroeinspielung
Import / Fremddateneinspielung

[980 $b]
Cataloging level / Erfassungstiefe
Full / Vollkatalogisat
Standard / Standard
Brief / Kurzkatalogisat

[980 $c]
Material examined / Autopsie

This information would be added automatically during import etc., but only for new records at now.
