### ISSUE TITLE
597 aus Materialbeschreibung löschen

### ISSUE THREAD

**Issue by MFalletta** [rism-ch/muscat#620]
- [x] Momentan ist 597 im Block Title and content description und Material description vorhanden.
- [x] Es soll nur einmal im Block Title and content description vorhanden sein. 
- [ ] Inhalte sollen in [...] ans Ende von 245 kopiert werden.
- [x] Anschließend Feld umbenennen in Colophon / Kolophon und 
- [ ] nach Additional title (730) platzieren.

**Comment by HirschSt** [comment]
Moving content (with maintenance script) and new pacement of field are in progress

**Comment by jenniferward** [comment]
Can "Colophon" be moved up to after "Additional title (730)"?
