### ISSUE TITLE
657 in Template Musikdruck, Haupteintrag Sammlung oder Individualeintrag ergänzen

### ISSUE THREAD

**Issue by MFalletta** [rism-ch/muscat#621]
Im Block Literatur und Fussnoten bitte das Feld Liturgische Feste 657 nach Querverweise zu RISM A/I und RISM B (596) einfügen

**Comment by xhero** [comment]
This tag is explicitly disabled for Prints, I can enable it back, should it be added to the guidelines?

**Comment by jenniferward** [comment]
No change needed for the guidelines; when users see 657 in the template then they will see the current guidelines, which are also valid for prints.
