### ISSUE TITLE
Distributor [dst] für 700 und 710 ergänzen

### ISSUE THREAD

**Issue by MFalletta** [rism-ch/muscat#623]
Den Begriff benötigen wir für die Drucke.
Distributor / Vertrieb

**Comment by xhero** [comment]
Should I add this in 4.1?

**Comment by HirschSt** [comment]
That would be great if possible, thanks. 
BTW: is 4.1-devel the actual develop master branch now?

**Comment by xhero** [comment]
Yes! Just freshly done

**Comment by HirschSt** [comment]
Perfect!
