### ISSUE TITLE
Secondary literature: Data is deleted if Short title (210) duplicated

### ISSUE THREAD

**Issue by jenniferward** [rism-ch/muscat#627]
If a short title is entered in 210 that has already been assigned, this warning rightfully appears:
Record not saved: Same short title 'BWV' already exists.

However, any information already entered is erased! The template is reset. 

Can the warning appear _without_ deleting the information in the other fields?

**Comment by HirschSt** [comment]
this will be fixed with the new version of serverside validation, see https://github.com/rism-ch/muscat/commit/d806b083de86c860510d8554b62e329cd03ddbde
