### ISSUE TITLE
Add url capabilities for 690 / 691

### ISSUE THREAD

**Issue by lpugin** [rism-ch/muscat#63]
We need the option to store and display urls for literature references and consultation date. These should be put into \[\]\(\), for example:
Where in the resource \[http://this.is.the.url\](date of consultation)

Todo:
- Edit the guidelines
- Change the display in show for 690/691 accordingly (make the url a link).

Only permanent links should be considered

**Comment by xhero** [comment]
I added the partial - we need to define the guidelines

**Comment by lpugin** [comment]
Can you drop an email to Jennifer?
