### ISSUE TITLE
Secondary literature: Data/Link missing to Previous entry (780)

### ISSUE THREAD

**Issue by jenniferward** [rism-ch/muscat#630]
Die Verknüpfung von einer Zeitschrift zu seinem "Früherer Eintrag (780)" fehlt. Dies war in Kallisto vorhanden.  Können die Daten bitte nachmigriert werden? Beispiel:
Eichstätter Intelligenzblatt http://muscat.rism.info/admin/catalogues/30023740 braucht eine Verknüpfung im Feld "Früherer Eintrag (780)" zu Königlich-Bayerisches Intelligenzblatt für den Ober-Donaukreis http://muscat.rism.info/admin/catalogues/30027975 .  Siehe Kallisto-Bild.

![eichstadter](https://user-images.githubusercontent.com/18663291/38735290-ae4e17fe-3f28-11e8-9a7c-9e6670ec2779.png)

**Comment by jenniferward** [comment]
If you don't mind me commenting on this: Was this closed because it is fixed, or closed because it is old? This data is still missing from Muscat, I think (I checked test and beta).

**Comment by HirschSt** [comment]
This is more on the maintenance side, see also https://github.com/rism-international/tasks/issues/148

**Comment by HirschSt** [comment]
The relation is existent with 785$w on https://muscat.rism.info/admin/catalogues/30027975, but this is not bidirectional. To make it somehow bidirectional if necessary, there should be a new issue
