### ISSUE TITLE
Link "Passwort vergessen?"

### ISSUE THREAD

**Issue by jenniferward** [rism-ch/muscat#634]
On the Muscat login page, can the link to "Passwort vergessen?" either be removed or enabled? Users, unsurprisingly, actually think it works and then are confused when nothing happens.

**Comment by xhero** [comment]
It actually does work on the CH system! Should I debug it for the new installation or remove it altogether? We do not allow users to change the password, so I guess remove is better

**Comment by HirschSt** [comment]
Removing is better, yes.

**Comment by xhero** [comment]
Removed :recoverable in user.rb so the link is not shown.
