### ISSUE TITLE
Secondary literature: 2 fields in 710

### ISSUE THREAD

**Issue by jenniferward** [rism-ch/muscat#635]
I am wondering why there is a 2nd free-text field in the 710 in Secondary Literature. Can it be deleted? If not, what is it for and what subfield is it?

See image, the field highlighted yellow.

![710 lit](https://user-images.githubusercontent.com/18663291/39194507-32f4d9c6-47de-11e8-9219-6b59faa3d911.png)

**Comment by HirschSt** [comment]
It's 710$b; labels added with 61bd5dc824a600085e8818d77d99f599be5ae960
