### ISSUE TITLE
Create alert for new sources

### ISSUE THREAD

**Issue by jenniferward** [rism-ch/muscat#638]
Something useful for the long-term RISM project would be the ability for ZR staff to create alerts for new sources in which an email is sent whenever a new source matching specified criteria is added to Muscat. I input a lot of catalogs and other articles/books but the sources aren't always in RISM. It is time-consuming and unrealistic to check Muscat occasionally to see if the source has been added. I would create an alert for the missing sources so that when they are added, I can add a catalog number or reference to an article/book/etc.

For example, I would like to create alerts for
-The manuscript GB-Lcm MS 6861 so that I can add a reference to JohnstoneA 2014, which describes the MS in detail
-GB-Ob MS Mus. Sch. c.117 so that I can add a reference to RangeB 2006, which is the focus of the article

This could be extended to certain composers and their catalogs of works, so that the ZR can make sure every new source by Verdi/Mozart/CPE Bach etc without a catalog number receives one.

**Comment by lpugin** [comment]
Interesting idea. Are you aware of other systems where something similar exists? The only case I can think of is subscription to alerts on ads system, but maybe you have something else in mind.

**Comment by jenniferward** [comment]
I had in mind RILM (through EBSCO), where I subscribe to alerts to receive notifications of new articles that have either certain subject headings, certain people, or certain keywords.
Example:  I get alerts for new records with the subject heading "manuscripts and prints." 

> EBSCOhost Alert Notification
> To: jennifer.ward@rism.info
> Subject: EBSCO Alert: SU manuscripts and prints on 2018-02-12 06:41 AM
> 
> The information below provides links to the 03/20/2018 02:10:36 AM Alert run 
> for "SU manuscripts and prints on 2018-02-12 06:41 AM" on the RILM Abstracts 
> of Music Literature (1967 to Present only) database with 1 hit(s).
> Following the links below will bring you to the start of the article or 
> citation.
> 
> Alert Run Date: 03/20/2018 02:10:36 AM
> Alert Name: SU manuscripts and prints on 2018-02-12 06:41 AM
> Database: RILM Abstracts of Music Literature (1967 to Present only) 
> Number of Hits: 1
> 
> Record  Results
> 
> 1.      Omne trium perfectum: D-minor lute works composed using three 
>         tablature letters. II (Main Record)  By: Foxe, Wilfred; Gafurius, 
>         Franchinus Medium:  print.  Source: Lute news, (124).  Published in: 
>         United Kingdom.  Publication Date: December, 2017.  Language: English.  
>         Abstract available.
> 
> http://search.ebscohost.com/login.aspx?direct=true&db=rih&AN=A1241616&site=ehost-live
> 
> 

I then look to see if it is potentially useful for RISM. If it is, I add it to Muscat. If we have the relevant sources, I add a lit reference. If we don't have the relevant sources, then I can't do anything except hope that future catalogers think to check the lit database when they are cataloging. There's no mechanism in place where we regularly check for new Mozart or Bach or XYZ sources because there are simply too many catalogs and composers and manuscripts. But if we had Muscat alerts, I would create them to ensure the quality of the data. 

I also have alerts set up for Google Scholar. It's quite simple and keyword based.
Example: 

> RISM - new results
> Opera & Ballet Primary Sources
> A Andries - Nineteenth-Century Music Review, 2018
> … The simple search automatically looks by keyword, while the advanced
> search offers the following additional categories for a more focused result:
> person (with a choice of composer, librettist, choreographer, and set designer) …
> https://doi.org/10.1017/S1479409818000071`

**Comment by HirschSt** [comment]
We can add this easly by supporting eg. stored queries of SRU (so it would be independent from muscat at all):

http://muscat.rism.info/sru/sources?operation=searchRetrieve&version=1.1&query=siglum=GB-Lbl%20AND%20shelfmark=%22Add.%2027636%22&maximumRecords=1
are returning 7 records

http://muscat.rism.info/sru/sources?operation=searchRetrieve&version=1.1&query=siglum=GB-Lbl%20AND%20shelfmark=%22MS%206861%22&maximumRecords=1
with zero records

Scheduling this on daily basis and alerting if some criteria (eg numberOfRecords=1) is fulfilled, then we have it (for example as Chrome browser plugin).

**Comment by xhero** [comment]
We could also create a trigger on saving that spawns a small mail job

**Comment by xhero** [comment]
How should we proceed for this? We can either do it in Muscat or using the SRU as Stephan poposed. In Muscat it is very easy to do at a basic level, we could consider an interface for users to configure which notifications to receive.

**Comment by HirschSt** [comment]
IMO it would be better to deal with this anywhere from client (because it would be better not to blow up server actions too much), since this request is also usefull for non muscat-users. Maybe there is any similar function in blacklight?

**Comment by xhero** [comment]
In the meantime we could also activate the dashboard: #649

**Comment by xhero** [comment]
This is implemented in -devel-alerts, will be merged in 5.0

**Comment by lpugin** [comment]
A few things:
- Where should we have the basic documentation on how pattern works? What to enter in the form?
- The content of alert is not displayed in the users/show
- It seems to ask for the password to be given for saving the user

**Comment by xhero** [comment]
Where should we add the documentation? The password box is shown only to the lucky ones that are admin

**Comment by lpugin** [comment]
> Where should we add the documentation?

I was thinking above the field? Or in the sidebar?

>  The password box is shown only to the lucky ones that are admin

This is solved, then!
