### ISSUE TITLE
Rename gem as language 041

### ISSUE THREAD

**Issue by jenniferward** [rism-ch/muscat#639]
Currently German and Germanic are next to each other in the 041 drop-down list as are Slavic and Slovak. I checked all the "Germanic" sources and they were all mistakes for German and have been corrected. 

As far as I'm concerned, gem (Other Germanic language) in the field 041 can be deleted. 

If you don't want to delete it, then I think the close placement leads to confusion, and I suggest renaming it  "Other Germanic language." (After all, the Likewise, "Slavic" might be better as "Other Slavic language."

**Comment by xhero** [comment]
I can remove it from the dropdown, but what about the data? I think a script to clean that up is needed.

**Comment by jenniferward** [comment]
As far as I know, there are no records containing 041 gem. I checked the OPAC. Could you please confirm? I didn't think there would be anything to clean up.

**Comment by xhero** [comment]
Double checked, it is not used, so I will remove it.
