### ISSUE TITLE
incipit subfields mixed up

### ISSUE THREAD

**Issue by rettinghaus** [rism-ch/muscat#648]
I noticed that the used subfield values for incipits don't match the [UNIMARC Manual](https://books.google.de/books?id=I9rPDkF0_ZQC&lpg=PP1&hl=de&pg=PA73#v=onepage&q&f=false) nor the [IAML Information on Plaine & Easie Code](http://www.iaml.info/plaine-easie-code):

* $r is used for key/mode, should be $g
* $g is used for clef, should be $m
* $m is used for voice/instrument, should be $d
* $d is used for movement caption/heading, should be $f

What am I missing?

**Comment by jenniferward** [comment]
Muscat matches the current MARC21 standard for field 031. See https://www.loc.gov/marc/bibliographic/bd031.html
The IAML page references "proposed MARC21 789 fields." Somewhere along the line the field 031 was adopted. A couple things on that IAML page are outdated; I'll try to fix the RISM stuff.

**Comment by rettinghaus** [comment]
Thanks!
