### ISSUE TITLE
Activate dashboard

### ISSUE THREAD

**Issue by xhero** [rism-ch/muscat#649]
Some translations are missing. The Dashboard could also be used as the first page upon login.
It will show sources made in the last 15 days and people/catalogues/institutions in the last 7 days.

**Comment by xhero** [comment]
We also have a statistics page, why don't we merge it with the dashboard?
Unfortunately it does work if the user has 0 elements to display )like me), but we can fix it

**Comment by HirschSt** [comment]
It's sensible concerning privacy, at the moment statistics is only available for admins and editors. I think we shouldn't change this.
