### ISSUE TITLE
Insert label for postponed issues

### ISSUE THREAD

**Issue by HirschSt** [rism-ch/muscat#651]
Proposal: since we have about 100 remaining open issues it's difficult to find the **REAL** stuff aside from many enhancement requests. Maybe we can give them a **postponed** label and **close** them? Then we can reopen if necessary and we have a cleaner tracking.

**Comment by xhero** [comment]
I agree with the postponed label, but I would keep them open and either label them properly and put them in milestones (like the "whishlist" for the ideas and the release versions for the real issues) and assign them to somebody. I use it this way and I do not find it too clumsy. My fear with closing them is to completely forget about them...

**Comment by HirschSt** [comment]
In some cases this wouldn't my fear but my hope :) ; but since eg node has > 650 issues we are quite good, so they could remain open.
