### ISSUE TITLE
Deleting Sources in Folders

### ISSUE THREAD

**Issue by xhero** [rism-ch/muscat#654]
Right now the folder is not updated and will not load anymore. Two solutions:

1) Delete the item from the folder automatically when the Source is removed
2) Have a contraint in the source and have the user delete it from the folder beforehand. Which needs #55 fixed as currently one cannot remove items from folders.

I vote for 1) and then to fix #55

**Comment by lpugin** [comment]
+1 for 1)

**Comment by HirschSt** [comment]
1) make sense and is clear
