### ISSUE TITLE
sources#index (SystemStackError) "stack level too deep"

### ISSUE THREAD

**Issue by xhero** [rism-ch/muscat#660]
in 

```
   app/models/user.rb:76:in `can_edit_edition?'
```

This happens when source_id = source.id. Ex. 241210, 1001015354. This should be fixed in 4.1, but probably there is old data around that needs to be fixed.

**Comment by xhero** [comment]
Complete list:

```
241210
1001015354
1001028660
1001028662
```

**Comment by HirschSt** [comment]
the old issue was fixed with 0492496909292e11866719b8bd1cc1b6df41869c , but now unfortunatly we have the infinloop at line 72, needs more investigation

**Comment by HirschSt** [comment]
@xhero  working on the same issue :wink: I hope we can close this :feelsgood:

**Comment by xhero** [comment]
I just pushed a fix too for that :D could you review it please? We can keep either for me :)

**Comment by HirschSt** [comment]
We can keep your version, which is already merged to head of the 4.3-devel

**Comment by xhero** [comment]
@jenniferward Could you have a look at the records to fix the linking?

**Comment by jenniferward** [comment]
Done except for 241210, which is imported data (and unpublished). I need to consult with the library on this one.
