### ISSUE TITLE
before_destroy destroys when false is returned

### ISSUE THREAD

**Issue by xhero** [rism-ch/muscat#661]
Apparently a "feature" of rails 5: http://guides.rubyonrails.org/5_0_release_notes.html (who spots the note wins). If you return false in the callback _it will delete the element_ but the browser will still show a "could not delete error"! Already fixed in a57d862d3a83ce90896b048b30408a422b40007f, we will need a script to spot the orphans.

**Comment by HirschSt** [comment]
Holy sh*t ... :flushed:

Item is probably:
"Deprecated returning false as a way to halt Active Record callback chains. The recommended way is to throw(:abort). (Pull Request)" 
Didn't make sense to me, but this is critical.

Please make the hotfix, we will see howto filter the orphans (I think you have a well known script :anguished:)...

**Comment by xhero** [comment]
Hotfix deployed in v4.1.4, d128a9a2684b425abae10b4ccfd7ff0fd7d4317e
