### ISSUE TITLE
Deprecated "paper_trail.without_versioning :save" in fix_ids

### ISSUE THREAD

**Issue by HirschSt** [rism-ch/muscat#668]
DEPRECATION WARNING:       my_model_instance.paper_trail.without_versioning is deprecated, without
      an exact replacement. To disable versioning for a particular model,

      ```
      PaperTrail.request.disable_model(Banana)
      # changes to Banana model do not create versions,
      # but eg. changes to Kiwi model do.
      PaperTrail.request.enable_model(Banana)
      ```

      Or, you may want to disable all models,

      ```
      PaperTrail.request.enabled = false
      # no versions created
      PaperTrail.request.enabled = true

      # or, with a block,
      PaperTrail.request(enabled: false) do
        # no versions created
      end
      ```
 (called from fix_ids at /home/dev/projects/muscat/app/models/source.rb:456)

**Comment by xhero** [comment]
I would enable this just after the release of 4.3 so we can test it well

**Comment by HirschSt** [comment]
Sure, but we should keep this in mind. Postponing deprection warnings is not a great idea - as you know :sunglasses:

**Comment by HirschSt** [comment]
Deprecation warning time is over, now leads to "NoMethodError"

**Comment by HirschSt** [comment]
@xhero can you check this? Saving is not possible with the current paper_trail method.

**Comment by xhero** [comment]
Did you update paper_trail?

**Comment by HirschSt** [comment]
Not AFAIK, except "bundle install"

**Comment by HirschSt** [comment]
Version on my installation is 10.0.3

**Comment by xhero** [comment]
In any case, I took the chance just to fix it :)

**Comment by HirschSt** [comment]
:crystal_ball: most probably fixed :wink:
