### ISSUE TITLE
"Download: XML" in the lower left corner of the list view brings error

### ISSUE THREAD

**Issue by bjoernkessler** [rism-ch/muscat#672]
XML is clickable. Click takes the user to a page with this message:

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<nil-classes type="array"/>

The whole item could be removed from the site.

**Comment by xhero** [comment]
This is related to #587. I made a patch to disable the download links, but retain the .xml functionality for a single item. In the future we can add a more elaborate xml/json/csv download of the index page, which will require a bit of working.

**Comment by xhero** [comment]
This is related to #587. I made a patch to disable the download links, but retain the .xml functionality for a single item. In the future we can add a more elaborate xml/json/csv download of the index page, which will require a bit of working.

**Comment by xhero** [comment]
Well my comment disappeared...
Related to #587. I made a patch to .xml so the download links are not there and we retain .xml for each item. In the future we can add back download links for any format but it will require a bit of work to generate the output we need.

**Comment by xhero** [comment]
Well my comment disappeared...
Related to #587. I made a patch to .xml so the download links are not there and we retain .xml for each item. In the future we can add back download links for any format but it will require a bit of work to generate the output we need.

**Comment by xhero** [comment]
Well my comment disappeared...
Related to #587. I made a patch to .xml so the download links are not there and we retain .xml for each item. In the future we can add back download links for any format but it will require a bit of work to generate the output we need.

**Comment by xhero** [comment]
Ok github is more weird than normal today

**Comment by HirschSt** [comment]
@xhero https://blog.github.com/2018-10-21-october21-incident-report/

**Comment by xhero** [comment]
Ok I deleted them and I hope this ticket does not automatically re-open :D
