### ISSUE TITLE
Move and rename 033

### ISSUE THREAD

**Issue by HirschSt** [rism-ch/muscat#674]
this should be directly above 518 and renamed from "date". 
Keep in mind: 033 **is** part of the material group, 518 **not**, so it's tricky to prevent data corruption.

**Comment by lpugin** [comment]
I think the decision was to remove 033 completely. We need to investigate this

**Comment by HirschSt** [comment]
I'm not sure if removing was RISM-CH related, probably @jenniferward knows more.

**Comment by jenniferward** [comment]
033 came from CH, it was never in Kallisto.
According to my notes, "Stephan wants to keep the field in case we import data with it." (23. Nov. 2016)

If we keep it, it should be called "Coded date for performance" in English and placed below the 518.

**Comment by cgueggi** [comment]
Since we still have this field, I'd propose to rename it as Jennifer called it "Coded date for performance" and replace it to the "references and notes" section (above 518). It doesn't make any sense to have it in the material description. Would this be possible for Muscat 5.1 (or even 5.0.1)?

**Comment by jenniferward** [comment]
What is the status of this? Can it, as an initial step at least, be moved to be above the 518? Having it so close to the 260 leads to mistakes.

**Comment by cgueggi** [comment]
I'm ok with the proposal of @jenniferward 
I just think it's important to take it out of the material description

**Comment by xhero** [comment]
Plan:
* 6.1 remove from editor
* 6.2 remove altogether

**Comment by xhero** [comment]
Make a list with the date values, used to fix the data.

**Comment by xhero** [comment]
List il done, cleanup script will be run after 6.2 release
