### ISSUE TITLE
588 terminology and placement

### ISSUE THREAD

**Issue by jenniferward** [rism-ch/muscat#678]
The field 588 is now live in Muscat but several of things have to be changed:

1. Change tag name in EN to: Source of description note
and change field name (588 $a) to: Copy examined for cataloging
2. The field must appear first in the section.
3. This field must be open and in yellow. It should also trigger a warning if not filled out.

#493

**Comment by HirschSt** [comment]
1 and 2 completed with fca16af2cee3a6fea5b0de5209797dcdf3d566d4 
3: this datafield only concerns prints, so validation can't be done with the generic MarcSource template IMO.

**Comment by lpugin** [comment]
3. Agree. Also, we do not have it for existing records, and it is always annoying / problematic to have old records not passing validation

**Comment by HirschSt** [comment]
@lpugin 100% correct, closed

**Comment by jenniferward** [comment]
3: Can it at least be open and in yellow? This field is central for cataloging printed music and must be more visible.
