### ISSUE TITLE
Implement Holdings to Collections

### ISSUE THREAD

**Issue by xhero** [rism-ch/muscat#683]
- [x] Add collection_id to Holding
- [x] Change behavior of 77x $4 so the right link gets referenced
- [x] add .items to access the whole collection of items: sources + holdings from the collection

**Comment by HirschSt** [comment]
@jenniferward this issue is connected with the holding/collection for SLUB

**Comment by xhero** [comment]
Actually .items is not really necessary, as from the view the items are iterated from the 774
