### ISSUE TITLE
Adding mention feature to commments

### ISSUE THREAD

**Issue by lpugin** [rism-ch/muscat#684]
Users should be able to use `@` to include other users in a comment conversation. See examples:

https://github.com/ichord/jquery-atwho-rails
https://stackoverflow.com/questions/22104048/mentioning-user-username-in-comments-mention-rails

**Comment by lpugin** [comment]
The simplest is probably to store / user names with white spaces replaced with _ and then look up for corresponding user names -> emails in the CommentNotifications class. 

This means the the comment is readable (even if the user mentioned is eventually deleted). This assumes that user names have no '_', which should be OK. We already have comments with `@` in the text, but always for email addresses. The lookup should be only for `@` not with a letter before (it has to work at the beginning of a comment, so requiring a white space before is not good enough).

**Comment by xhero** [comment]
At.js is not maintained anymore, I used  https://github.com/zurb/tribute.

**Comment by xhero** [comment]
Sometimes with some sources the address box appears out of position
