### ISSUE TITLE
"Holding without silgum"

### ISSUE THREAD

**Issue by jenniferward** [rism-ch/muscat#691]
Look here:
https://muscat.rism.info/admin/holdings
![image](https://user-images.githubusercontent.com/18663291/46798767-2619ba00-cd53-11e8-8afd-aa1aa4a25960.png)

Or https://muscat.rism.info/admin/sources/992001173 and https://muscat.rism.info/admin/sources/990026677

On each record, one of the holdings records says "Holding without silgum."

It is possible to save a new holdings record without inputting any data. This happened during the workshop and I deleted those, but it is still happening.

The empty holdings records should be deleted (there are probably more), and there should be a validation that triggers a warning if a user tries to save a holdings record without (at the very least) a siglum.

**Comment by xhero** [comment]
This should be already there, at least it in in the configuration. I will have a look

**Comment by xhero** [comment]
I do remember fixing this already, I'm not sure how the old (and wrong) validation got there. I will do a patch on the configuration on the live system and then have it as default on the release.
