### ISSUE TITLE
Extend source index with new holding tags (eg 592$a)

### ISSUE THREAD

**Issue by HirschSt** [rism-ch/muscat#692]
it seems that currently only 852 is indexed with sources, see  https://github.com/rism-ch/muscat/blob/e3389677a9590f5fa18a8a571565acd4e3929394/lib/marc_index.rb#L68

SourceIndex should be extended to support other tags too, probably needs some new implementation

@xhero Any ideas?

**Comment by xhero** [comment]
It probably would not be too difficult - we could have some sort of helper, and we need to test it for performance too

**Comment by HirschSt** [comment]
related https://github.com/rism-international/tasks/issues/192

**Comment by HirschSt** [comment]
done with https://github.com/rism-ch/muscat/commit/5ed02acd59f234a92b48b7756ab00447c319bd13
