### ISSUE TITLE
ActiveRecord::StatementInvalid occurred in sources#index

### ISSUE THREAD

**Issue by HirschSt** [rism-ch/muscat#694]
sources#index (ActiveRecord::StatementInvalid) "Mysql2::Error: Unknown column 'shelf_mark_shelforder' in 'order clause'

Mysql2::Error: Unknown column 'shelf_mark_shelforder' in 'order clause': SELECT  `sources`.* FROM `sources` WHERE (`sources`.`id` LIKE 0) ORDER BY `shelf_mark_shelforder` asc LIMIT 10 OFFSET 10
  app/admin/source.rb:134:in `index'

**Comment by xhero** [comment]
Argh! when does this happen?

**Comment by HirschSt** [comment]
last_order_page"=>{"sources"=>"shelf_mark_shelforder_asc"},
   "last_search_filter"=>
    {"sources"=>
      <ActionController::Parameters {"852a_facet_contains"=>"A-MS"} permitted: true>},
   "last_search_page"=>{"sources"=>"2"}}

**Comment by HirschSt** [comment]
in some special cases :sunglasses:

**Comment by HirschSt** [comment]
I cannot reproduce this ... :fearful:

**Comment by HirschSt** [comment]
closed because unreproducable and the error didn't happen again
