### ISSUE TITLE
Include holdings as default with marcsource.to_external

### ISSUE THREAD

**Issue by HirschSt** [rism-ch/muscat#697]
see https://github.com/rism-ch/muscat/blob/e3389677a9590f5fa18a8a571565acd4e3929394/lib/marc_source.rb#L505

currently holdings are only included with holding==true as param

holdings should be included always if existent

**Comment by xhero** [comment]
I'm not sure why it is `false` by default... Maybe a conservative option? I'm going to test `true` by default a bit.

**Comment by HirschSt** [comment]
yes, it is for being on the very secured side :see_no_evil:
