### ISSUE TITLE
Adding images to holdings

### ISSUE THREAD

**Issue by alexandermarxen** [rism-ch/muscat#702]
We need the possibility to add images to holdings, for example to add watermark-drawings:
https://muscat.rism.info/admin/sources/550281856

**Comment by HirschSt** [comment]
Are the watermarks different between exemplars of a bibliographic record?

**Comment by xhero** [comment]
We need to think this a bit, as holdings only have "edit" mode, would it be enough to show the image there?

**Comment by xhero** [comment]
I think this came up again recently. The problem is that there is no "show" for holdings, so no place to really show the images attached to the holding.
One solution could be like we (will) do for IIIFs, I can add a box for each Holding in the parent Source with all the Holdings' images.

**Comment by xhero** [comment]
Show the images in the source show page, as we do for IIIF.

**Comment by xhero** [comment]
I would like to do this in 10, but there are still two open questions:

* Where to add the images. Normally the "add digital object" is in the Show page, but there is no show for Holdings
* Where to show the images, again there is no show page for holdings

My proposal is:
* Add the images from the source *show* page, with a button in the holding box
* Show the images after the digital objects in the source *show* page
