### ISSUE TITLE
Library Sigla in 852 should lead to general search result or authority entry

### ISSUE THREAD

**Issue by bjoernkessler** [rism-ch/muscat#707]
For Example

in this entry:
https://muscat.rism.info/catalog/451002078

under "library information" the value of the field 852 "D-MÜs" is clickable.

Expectation:
either this
https://muscat.rism.info/catalog/?q=D-M%C3%9Cs&search_field=any_field

this
https://muscat.rism.info/catalog/?q=D-M%C3%9Cs&search_field=library_siglum

or this:
https://muscat.rism.info/admin/institutions/30000239
(actually what I expected to see)

But it leads back to the same page following this URL:

https://muscat.rism.info/catalog/451002078?q=D-M%C3%9Cs&search_field=any_field

**Comment by bjoernkessler** [comment]
Done with 7b3ada

**Comment by xhero** [comment]
👍  thanks!
