### ISSUE TITLE
Add clarification of @-mentions in comments

### ISSUE THREAD

**Issue by jenniferward** [rism-ch/muscat#716]
In the comments area, could you add a clarification that @-mentions are possible? For new users who weren't here for the 5.0 announcements, it isn't obvious that this feature is in place.

Suggestion:
Type @ to mention a specific user, who will then receive a notification by email.

**Comment by xhero** [comment]
Done! Could you have a check at the translations?

**Comment by jenniferward** [comment]
Where has this been added? I can check it if you wish.
