### ISSUE TITLE
Add Taiwan to Country of Publication in 044 in Secondary Literature

### ISSUE THREAD

**Issue by jenniferward** [rism-ch/muscat#719]
Please add Taiwan to Country of Publication in 044 in Secondary Literature.
MARC has this:
China (Republic : 1949- ) [ch]

I'll leave it up to you whether to call it that, Republic of China, or Taiwan.

**Comment by HirschSt** [comment]
closed with 6be5749b07186f915cc1ffba09093b506a98cb08
