### ISSUE TITLE
Templates needed for treatise or libretto within printed edition

### ISSUE THREAD

**Issue by jenniferward** [rism-ch/muscat#722]
The last release of Muscat included the ability to add holdings to printed treatises and libretti. 

However, we still need a template for a single treatise or libretto that is found within a printed edition - i.e. https://muscat.rism.info/admin/sources/new?new_type=013_edition_content but for libretto and treatises, so a printed treatise/libretto that cannot take holdings.

Or can we use template 013 for _any_ kind of "item in edition"?

Example:
https://muscat.rism.info/admin/sources/653005911
This is a single printed edition that contains multiple libretti.

(Might affect #566 )

**Comment by jenniferward** [comment]
As far as I'm concerned, for now it's ok with me if the current libretto and treatise templates are duplicated in content with https://muscat.rism.info/admin/sources/new?new_type=015_libretto_edition_content and https://muscat.rism.info/admin/sources/new?new_type=017_theoretica_edition_content with the sole difference that they lack the ability to add holdings. 

My coworkers and I would like to see further refinements of the libretto and treatise templates (for example, we probably don't need a field for key) but this is a separate project that we are in the initial stages of.

**Comment by xhero** [comment]
From my side of things, we should add two record_types for these templates, so we can block the holdings on them

**Comment by jenniferward** [comment]
There are some translations missing on beta. Suggestions:

https://beta.rism.info/admin/sources/new?new_record_type=libretto_edition_content
translation missing: en.record_types.libretto_edition_content
Translation: Printed libretto, item in collection

https://beta.rism.info/admin/sources/new?new_record_type=theoretica_edition_content
 translation missing: en.record_types.theoretica_edition_content
Translation: Printed treatise, item in collection

**Comment by xhero** [comment]
Done in 26ddce6f44f626ed5314623ff3e852b90bc20a3b, I wrote the wrong nr. in the commit message
