### ISSUE TITLE
Create special template for composite volumes 

### ISSUE THREAD

**Issue by HirschSt** [rism-ch/muscat#730]
since the template structure of composite volumes now it's more or less the same as with manuscript collections, but still eg does'nt need the material block, I think it's cleaner to have a special template for "composite volume". What do you think?

**Comment by jenniferward** [comment]
The ZR editors propose a radical slimming down of the "Collection" template to make the new template for the composite volumes. We propose the following:

* Pflichtfeld

**Library information and relations:** 
Delete Parent record (773) and Initial entry (775)
Keep the rest

**People and institutions**
Delete  Composer (100)
Keep 700 and 710, all subfields, but reduce the functions:
700 $4: Only dedicatee, former owner, other
710 $4: Only previous owner, depositor, other, bookseller, and dedicatee

**Title and content description**
Keep 245 $a
Keep 246 $a
Keep 240 but only $a
Keep 730 but only $a and $g
Keep 520
Delete all other fields in this block

**Material description**
Keep 260 but only $c
Keep 300 but only $c
Keep 340 but only $m
Keep 563 $a
Delete all other fields in this block

**References and notes**
Delete 510, 596, 518
Keep the rest

**Work**
Delete

**Administration**
Keep

**Comment by jenniferward** [comment]
Currently there are 25 records for composite volumes:
https://muscat.rism.info/admin/sources?utf8=%E2%9C%93&q%5Bstd_title_contains%5D=items&q%5Brecord_type_select_with_integer%5D=record_type%3A1&commit=Filter&order=id_desc

I presume some of them use fields that we propose for deletion. Once the template is finalized, I can look at them individually and move the data that appears in a field that will be deleted--does that sound ok?

**Comment by HirschSt** [comment]
This proposal needs further discussion, eg. why should 240 and 245 be mandatory, since in the example records we have "3 items" etc. in 240 and "[no title]" in many records (should work or expression related entities really be part of this template?). 
AFAIK 'composite' is a template to show a (more or less physical) binding of different records; most probably the material section in this template will only duplicate information by the associated records.

**Comment by jenniferward** [comment]
Having 240 and 245 mandatory is in accordance with current practice for manuscript collections. In manuscript collections, the 240 refers to the number of items linked to the record (32 Sonatas etc) and in composite volumes it refers to the number of items linked to the record as well. In manuscript collections, the 245 refers to the title on the item or a title on a partbook, and in composite volumes it refers to the title on the item or a partbook. It is quite likely that some composite volumes have 245=[without title] but the same is true for manuscript collections.

Information in the material section refers to the binding.
260 $c: Date of binding (not the publication date of the items)
300 $c: Dimenions of the item, including the binding (not the dimensions of the prints, which are smaller)
340 $m: Format of the book. Yes, this could be duplicated in the associated record, but if someone is creating a composite template for say 100 items, are they going to change 340$m 100 times?
563 $a: This is a description of the binding. Individual items therein are not, strictly speaking, "bound"  (though I have nothing against a contributor who does not create a composite record but instead describes the binding at the holdings level).

**Comment by HirschSt** [comment]
It seems there are unclear definitions around here what a composite is (eg compared with collection). Until now a composite is pretty one of the fewest needed things we had in the RISM world - and I'd like to have it remaining there. So we need a clear definition what a composite is to choose the correct template structure.
In addition to that: with the current layout of Muscat it is not possible to extract subfields from the source template, so we had to choose if we want eg. tag 300 with all subfields or not (and not "we want to have 300$c, but not 300$a").

**Comment by jenniferward** [comment]
Composite volume definition: A Composite volume is a volume that consists of items that were created separately but later bound together, typically by an owner or institution. This includes volumes in which individual printed items are bound together, as well as volumes in which printed items and manuscripts are bound together.

**Comment by HirschSt** [comment]
So we have this layout for the composite template, please check:
```yaml
#LIBRARY
- 852
- 591
- 035
- 506
- 561
- 541
- 774
#PEOPLE
- 700
- 710
#TITLE
- 245
- 246
- 240
- 730
- 520
#MATERIAL
- 260
- 300
- 340
- 500
- 563
- 856
#REFERENCE
- 500
- 505
- 525
- 691
#ADMIN
- 040
- 980
- 559
```

**Comment by xhero** [comment]
To follow Oliver's suggestion: what about 'bundle'?

**Comment by jenniferward** [comment]
@xhero : What do you mean by 'bundle'? (I probably missed that conversation, maybe it doesn't involve me.)

**Comment by jenniferward** [comment]
@HirschSt 
#MATERIAL
-delete 500
-delete 856
-add 592

#REFERENCE
-add 856


@ all: Is there a situation where we would need the "+Add a group" feature in the Material block? I'm thinking no.

**Comment by xhero** [comment]
'bundle' instead of 'composite volume'

**Comment by jenniferward** [comment]
I'm not familiar with that term used in this context. "Composite volume" is one of several possible terms used in libraries (including "bound-withs", "sammelband" "binder's volumes") but I think "composite volume" is the clearest to most people.

**Comment by jenniferward** [comment]
I see that the following was overlooked (comment 8 April). Watermark is missing, and there are 2 fields in Material that we don't need. Can this be changed?

#MATERIAL
-delete 500
-delete 856
-add 592

**Comment by jenniferward** [comment]
Please delete the "+ add a group" function.

**Comment by HirschSt** [comment]
I'd like to have this in a new issue, see #806
