### ISSUE TITLE
Delete "music periodical" from 593

### ISSUE THREAD

**Issue by jenniferward** [rism-ch/muscat#733]
The ZR does not want the source type "music periodical" in the field 593. 

There are ca. 30 records with this designation. Martina, Guido, and I will edit these. Then I will update this ticket so "music periodical" can be removed.

**Comment by xhero** [comment]
Done! This will be in 5.2, is it ok to clean up the data beforehand? We can then run a script to make sure no more exist afterwards.

**Comment by jenniferward** [comment]
I don't know, I've already asked.

**Comment by xhero** [comment]
ok I will make a note to check this upon 5.2

**Comment by jenniferward** [comment]
That reminds me, we need to delete it as an option in the OPAC too. Will write ticket for BSB.

**Comment by MFalletta** [comment]
Ich bin auch durch mit meinen Titeln. Es gibt keine "Music periodical" mehr!
