### ISSUE TITLE
Default values for 980

### ISSUE THREAD

**Issue by jenniferward** [rism-ch/muscat#734]
The ZR wants the following to be the default values in the field 980, i.e. each new "Source" record in Muscat should have these values pre-selected:

980 $a: RISM
980 $c: Material examined

Catalogers will have to decide whether to fill out $b, cataloging level. Question for everyone: Should this field be open and thus more visible? Then catalogers might pay more attention to it.

**Comment by HirschSt** [comment]
it looks like that we don't have default values for subfield_select_codes now, so this needs some more preparation.
I am not in favour to have open 980 since it is a local field. Maybe preselecting values in 980$b could be made by user configuration (as with prefered wf_stage).

**Comment by HirschSt** [comment]
for now 980 is open and and $a and $c preselected with default marc, see https://github.com/rism-ch/muscat/commit/ea35db7debe06c0e2c535d864ce424b65c25e81e.

For $b it has to be defined sonehow what the meaning is of a "full" or "brief" record, so this one is difficult. I like to separate this to another new issue for more discussion.
