### ISSUE TITLE
Add 593 to holdings

### ISSUE THREAD

**Issue by jenniferward** [rism-ch/muscat#735]
The field 593 is needed for holdings because the values "Print with autograph annotations" and "Print with non-autograph annotations" are plausible situations that only apply to specific copies.

Thinking long term, it would be good if the 593 menus were template specific. For example, "Print with autograph annotations" and "Print with non-autograph annotations" are not needed on the bibliographic level.

**Comment by HirschSt** [comment]
I didn't found a related discussion in the correspondence history of the print templates, so we just can insert the field 593 into the holding template. 
Adding a new template senifitive option list logic should nevertheless only be added if this could be made with clean and easy code - maybe we should consider to give the editor configuration section a new layout

**Comment by HirschSt** [comment]
closed with commit
