### ISSUE TITLE
Remove some functions in  700 (Holdings)

### ISSUE THREAD

**Issue by jenniferward** [rism-ch/muscat#736]
In 700 $4 in the holdings information, there are more functions in the list than are required for copy-specific information. The complete list is:

Arranger
Author
Co-composer
Composer cross-reference
Copyist
Dedicatee
Editor
Engraver
Former owner
Illustrator
Librettist
Lithographer
Other function
Performer
Printer
Publisher
Text author
Translator
Uncertain

After a quick consultation with my coworker, we propose deleting the following:
Arranger
Author
Co-composer
Librettist
Printer
Publisher
Text author

Comments welcome.

**Comment by jenniferward** [comment]
Another thing: Can you change "Other function" to "Other", to match the term in the other sources?

**Comment by HirschSt** [comment]
cmp Composer cross-reference
scr Copyist
dte Dedicatee
edt Editor
egr Engraver
fmo Former owner
ill Illustrator
ltg Lithographer
oth Other function
prf Performer
trl Translator
dub Uncertain

I think we can also drop prf and trl

**Comment by jenniferward** [comment]
We need prf because sometimes the name of the choir or orchestra that used the material is handwritten on the item.

I was thinking trl might be useful if a local copy has translations written in, but maybe this is not very common (i.e. German words written above Latin texts; this happens in D-F a lot).

**Comment by HirschSt** [comment]
ok, thanks.
