### ISSUE TITLE
Remove some functions in  710 (Holdings)

### ISSUE THREAD

**Issue by jenniferward** [rism-ch/muscat#737]
In 710 $4 in the holdings information, there are more functions in the list than are required for copy-specific information. The complete list is:

Copyist
Dedicatee
Depositor
Editor
Former owner
Other
Other function
Performer
Printer
Publisher

We propose deleting:
Copyist
Editor
[either] Other [or] Other function
Printer 
Publisher

Comments welcome!
See also #736

**Comment by jenniferward** [comment]
A Muscat contributor alerted me to this this morning.
I think there was a misunderstanding: either "Other" or "Other function" should be removed, but we need one of them. It looks like both were removed. As a result, (1) there is no option for 'other' and (2) the records that were marked "other" or "other function" are now labeled "asn" which is not a valid function.

I think "Other" [oth] should be the phrase used, to keep it consistent with the terminology in the "Source" records. I suspect, then, that the records with "other function" [asn??] would have to be migrated to "other".  

And hopefully there weren't any holdings with Copyist, Editor, Printer, Publisher?

Also related, while we're talking about 710 holdings: #738

**Comment by jenniferward** [comment]
Example: https://muscat.rism.info/admin/sources/1001051476

**Comment by xhero** [comment]
so `asn` -> becomes `oth`?

**Comment by HirschSt** [comment]
FYI: this was done with sorces in 2017, see https://github.com/rism-international/muscat-maintenance/blob/06b40a192bbcd789adf2e4144b0dcf4ffe236803/archive/20170208-sources-relator.rb, we can do the same with holdings if necessary
