### ISSUE TITLE
Tibetisch für Sprachcode 041

### ISSUE THREAD

**Issue by MFalletta** [rism-ch/muscat#741]
Für 041 bitte "Tibetan" bzw. "tibetisch" ergänzen, 
Beispiel: RISM ID no. 1001062263
https://muscat.rism.info/admin/sources/1001062263

**Comment by HirschSt** [comment]
![image](https://user-images.githubusercontent.com/6461776/53226712-4439e400-367c-11e9-9465-f529edaeb8ca.png)
