### ISSUE TITLE
Collection Template mit Incipits

### ISSUE THREAD

**Issue by MFalletta** [rism-ch/muscat#742]
In den Altdaten kommt das Template "Musikhandschrift, Haupteintrag Sammlung" mit zahlreichen Incipits vor. Es handelt sich hier wohl ausschließlich um die Compilation-Redaktion. 
Bei diesen Titeln erscheint die Meldung: "Eintrag enthält falsche Felder". Man kann keine Korrekturen an diesen Titeln vornehmen.  
Teilweise gibt es Verknüpfungen zu untergeordneten Einträgen, z. B.: https://muscat.rism.info/admin/sources/270001565
oder https://muscat.rism.info/admin/sources/270001358
oder auch https://muscat.rism.info/admin/sources/270001893

Wie verfahren wir mit diesen Titeln? 
Können sie zur Bearbeitung freigegeben werden?
Oder müssen diese Titel jetzt anders redigiert werden?

**Comment by HirschSt** [comment]
es gibt dazu ein Ticket unter https://github.com/rism-international/tasks/issues/385; zunächst müssen alle Einträge, die keine Kindeinträge haben, ein entsprechendes Template bekommen. Alles weitere im og Ticket.
