### ISSUE TITLE
Avoid subfields ($u and $z) should not be repeatable in 856

### ISSUE THREAD

**Issue by lpugin** [rism-ch/muscat#744]
We probably want to make sure we do not loose anything. Probably just a few records to be edited by hand?

**Comment by jenniferward** [comment]
I will edit them by hand if you can tell me the RISM ID numbers. I don't think it will be a lot.

**Comment by xhero** [comment]
Do you know how many we have? I would like to modify the marc configuration on this in 5.2.1

**Comment by xhero** [comment]
There is a grand total of... three. @jenniferward could you please have a look?

```
553015044
1001016150
1001071971
```

**Comment by jenniferward** [comment]
Those 3 are done.

**Comment by xhero** [comment]
Danke!
