### ISSUE TITLE
Unknown template - Unbekannte Vorlage

### ISSUE THREAD

**Issue by MFalletta** [rism-ch/muscat#746]
Beim Aufrufen des folgenden Titels 
https://muscat.rism.info/admin/sources/990070397
heißt es "[Unknown template] / [Unbekannte Vorlage]" anstelle von "Musikdruck, Haupteintrag Sammlung oder Individualeintrag".
Beim Bearbeiten wird ist ein Abspeichern nur mit 852 möglich?!

**Comment by xhero** [comment]
Record type for this record is 0! In my dump of the database from two weeks ago it is 8 (music edition)!
Do you know who edited it? what was done to it?

**Comment by jenniferward** [comment]
Yesterday Alexander merged two names together, "Anonymus" plus variants.
![image](https://user-images.githubusercontent.com/18663291/53802971-8c41ec00-3f43-11e9-9924-edfb75d11374.png)

Take a look at Composer Anonymus plus edits yesterday:
https://muscat.rism.info/admin/sources?utf8=%E2%9C%93&q%5Bcomposer_contains%5D=anonymus&q%5Bupdated_at_gteq_datetime%5D=2019-03-03&q%5Bupdated_at_lteq_datetime%5D=2019-03-05&q%5Brecord_type_select_with_integer%5D=record_type%3A0&commit=Filtern&order=id_desc&per_page=100

4,600 with "unknown template"

Does this have to do with merging?

**Comment by HirschSt** [comment]
probably some trouble due to unset record_type with auth_merge, we have to check...

**Comment by HirschSt** [comment]
@xhero we can reify the record_type from papertrail

**Comment by xhero** [comment]
OMG I'm too young to have a stroke!
@HirschSt could you have a look to reify the record_type? Or should I look into it? I'm a bit confused on what is happening, auth merge should not change the record_type of the sources no?

**Comment by HirschSt** [comment]
I am just preparing a hotfix; afterwards we run a script to can get the old record types, I am working on this

**Comment by xhero** [comment]
👍

**Comment by HirschSt** [comment]
Maintenance script see https://github.com/rism-international/muscat-maintenance/commit/9674fdc1278e2cfca1a94856c7db8ef3bd79052f

**Comment by xhero** [comment]
super thanks! Shall I make release + run the script?

**Comment by HirschSt** [comment]
Yes!
