### ISSUE TITLE
Change "In progress" to "Unpublished" in Edit view 

### ISSUE THREAD

**Issue by jenniferward** [rism-ch/muscat#755]
In the Muscat main search screen, the Status is Published/ Unpublished.
![image](https://user-images.githubusercontent.com/18663291/54673532-ba562d00-4afa-11e9-8ad4-ca66f3209994.png)

In the Edit mode, it is called Published/In progess
![image](https://user-images.githubusercontent.com/18663291/54673578-d2c64780-4afa-11e9-864b-9ef4403b14ef.png)

Can this be consistent? I prefer "Unpublished".

**Comment by xhero** [comment]
Are there any more? If not we can close
