### ISSUE TITLE
Cleanup index after folder deletion (background task)

### ISSUE THREAD

**Issue by lpugin** [rism-ch/muscat#76]
Deleting folder yields endless SQL queries and needs to be optimized in the same way inserts are

**Comment by lpugin** [comment]
@xhero ? Is this solved?

**Comment by lpugin** [comment]
@xhero solved?

**Comment by xhero** [comment]
Not yet

**Comment by lpugin** [comment]
Don't you want to keep the ticket, then?

**Comment by xhero** [comment]
Ops! that is the wrong message!!! I actually fixed it in 3854577!
