### ISSUE TITLE
Optimize SOLR indexed fields

### ISSUE THREAD

**Issue by xhero** [rism-ch/muscat#764]
A long standing wish of mine. Currently the index works quite well but it could be better. Many many fields are fulltext (*_text) where they could be strings, making them useful for filtering. We could then tune by hand schema.xml to use <copyField> if we need a copy instead of indexing twice, and a catch-all __text__ field for automatic fulltext.
And also we can see if we can remove some fields that are not necessary.

The table is the fields in use with the description if I know they do something special:

**NOTE THE LIST IS A WORK IN PROGRESS!!**

Interrogate the luke handler:
```http://localhost:8982/solr/development/admin/luke?numTerms=0```

**Key:**
* **C:** Catalogue
*  **I:** Institution
* **H:** Holding
* **P:** Person
* **S:** Source
* **W:** Work

Field | Where | What | Comments
----- | ------ | ------ | ----------
001_text | C I H P S W | Record id, fulltext version | Probably better indexed?
024a_text | I 
026e_text | S
028a_text | S | | There is also 028b with no data
031d_text | S
031e_text | S
031m_text | S
031p_texts | S | Pae data | Raw PAE code for each incipit, stored for display
031q_text | S
031t_filter_sm | S | Incipit text, string | Used for filtering
031t_text | S W | Incipit text | As above but for fulltext
033a_text | S
035a_text | P S
040a_text | P
040b_text | P
040c_text | P
041a_text | S
041e_text | S
041h_text | S
043c_text | I P
100a_or_700a_texts | C | Aggregated text for author | I think?
100a_text | Name on source full text
100d_birthdate_text | P W
100d_deathdate_text | P W
100d_text | C P S W | Dates | Maybe as integer is better?
110a_text | I S
110c_text | I
110g_facet_sm | I |  | Indexed for faceting
110g_text | I | as above | Full text
210a_text | C
240a_filter_sms | S | Title | For indexing
240a_text | C S | as above | For full text
240g_text | C
240k_text | S
240m_filter_sm | S | | For index
240m_text | S | | Full-text
240n_texts | S | | Full text and stored
240o_text | S |
240p_text | S |
240r_texts | S | | Full text and stored
245a_text | S
245b_text | S
245c_text | S
246a_text | S
246i_text | S
260a_text | C S
260b_text | C S
260c_text | C S | Year | Full text field
260c_year_ims | S | Year | Index field for the year
260e_text | S
260f_text | S
300a_text | S
300b_text | S
300c_text | S
340d_text | S
371a_text | I
371u_text | I 
375a_text | P 
383b_text | S
400a_text | C P W
400d_text | P
410a_text | I
500a_text | S
505a_text | S
506a_text | S
510a_text | S
510c_text | S
511a_text | S
518a_text | S
520a_text | S
525a_text | S
541a_text | S
541c_text | S
541d_text | S
546a_text | S
550a_text | P
551a_text | P
5615_text | S
561a_text | S
563a_text | S
5800_text | I
580x_text | I
590a_text | S
590b_text | S
591a_text | S
592a_text | S
593a_filter_sm | S | | For index and filtering
593a_texts | S | | Text version stored
594a_text
594b_sms
594c_text
595a_text
595u_text
596a_text
597a_text
598a_text
599a_text
650a_filter_sm
650a_text
651a_text
657a_text
667a_text
670a_text
670b_text
678a_text
678b_text
678u_text
6805_text
680a_text
680i_text
690a_text
690n_text
691a_text
691n_text
7004_text
700a_text
700d_text
700e_text
700t_text
7104_text
710a_text
710b_text
730a_filter_sm
730a_text
730k_text
730m_text
730n_text
730o_text
730r_text
740_autocomplete_sms
740a_text
7600_text
760g_text
760t_text
773w_text
774w_text
787a_text
787n_text
787w_text
852a_facet_sm
852a_text
852b_text
852c_texts
852d_text
852e_text
852q_text
852z_text
856u_text
856x_sm
856z_text
address_text
alternate_dates_text
alternate_names_text
alternate_terms_order_s
alternate_terms_text
author_order_s
author_text
catalogues_im
class_name
composer_d_text
composer_order_s
composer_texts
copies_is
country_order_s
country_text
created_at_d
created_at_dm
date_order_s
date_text
description_order_s
description_text
district_text
folder_id_i
full_name_d_text
full_name_order_s
full_name_text
id
id_fulltext_text
id_i
id_text_text
institutions_im
item_id_i
latin_order_b
lib_siglum_order_s
lib_siglum_s
lib_siglum_ss
lib_siglum_text
life_dates_order_s
life_dates_text
liturgical_feasts_im
location_lls
location_lls_0_coordinate
location_lls_1_coordinate
name_order_s
name_text
notes_text
pae
people_im
place_order_s
place_text
places_im
record_type_i
revue_title_order_s
revue_title_text
shelf_mark_order_s
shelf_mark_shelforder_s
shelf_mark_text
siglum_order_s
siglum_text
source_id_text
source_text
sources_im
src_count_order_is
standard_terms_im
standard_titles_im
std_title_d_text
std_title_order_s
std_title_shelforder_s
std_title_texts
sub_topic_text
term_order_s
term_text
textSpell
title_d_text
title_order_s
title_text
title_texts
topic_text
type
updated_at_d
url_text
wf_owner_i
wf_owner_im
wf_stage_s
works_im

for a grand total of 233 items shared with all auth files

**Comment by HirschSt** [comment]
Fantastic work, thanks :clap: a long work in progress IMO

**Comment by xhero** [comment]
Many of the _text fields are useful just to respond to the "any field" fulltext queries. I think we could vene just index the whole marc field (there should be a processor to remove the marc tags or we can make one) so to get fulltext phrases in there, and then keep separate fields for only those fields we want to provide as an option for filtering and faceting.

**Comment by HirschSt** [comment]
Sounds a tricky way to slim down the configuration :1st_place_medal: and to (string)index only the real stuff, so :+1:

**Comment by HirschSt** [comment]
BTW your proposal is somehow like the postgres fulltext approach

**Comment by fjorba** [comment]
May I suggest changing `fulltext` to `any field`? This way we can use `fulltext` for effectively indexing attached documents (typically pdfs) fulltext, like Google or other repository software (like Invenio, DSpace and others).  Solr is perfectly capable of doing it, but we should keep the terminology clear so concepts don't mix.

**Comment by fjorba** [comment]
Excuse me, @xhero, but what do you think about this terminology proposal?  Should I better open a specific issue for discussing it?

Thanks

**Comment by xhero** [comment]
I agree with you but... we do not actually have any `fulltext` search right now, and the search in the _text fields is actually called "any field". Then, there is some confusion with sunspot, since searching _text fields is called "fulltext" there, but it is not something we can change.

**Comment by fjorba** [comment]
I see; thanks for the explanation.  I'll see if I should knock Sunspot door ;-)
