### ISSUE TITLE
Rename LiturgicalFeast to Feast

### ISSUE THREAD

**Issue by HirschSt** [rism-ch/muscat#783]
follow up of #756 
rename UI and models accordingly in dedicated branch

**Comment by HirschSt** [comment]
branch https://github.com/rism-ch/muscat/tree/5.2-devel-feast

**Comment by HirschSt** [comment]
For now I don't like to rename everything, since the benefit is very small. We could discuss this again if we put this into Thesaurus (about 2021).

**Comment by xhero** [comment]
I propose to close this and then rediscuss when we do the thesaurus
