### ISSUE TITLE
Undefined method `src_count' running 01_update_src_count.rb

### ISSUE THREAD

**Issue by fjorba** [rism-ch/muscat#784]
After loading several thousand records into Muscat, and following the https://github.com/rism-ch/muscat/blob/master/3-%20IMPORT.rdoc instructions, I run the following script:

$  rails runner housekeeping/correct/01_update_src_count.rb

For each of the record types, I get an undefined method src_count:

```
muscat-5.1.2/vendor/bundle/ruby/2.3.0/gems/activemodel-5.1.6/lib/active_model/attribute_methods.rb:432:in 
`method_missing': undefined method `src_count' for #<Institution:0x00564b3f55af88> (NoMethodError)
        from housekeeping/correct/01_update_src_count.rb:56:in `block in <top (required)>' 
```
Commenting out each of the update_attribute calls, for example:

```
@@ -13,7 +13,7 @@ puts "Fixing Standard Title"
 pb = ProgressBar.new(StandardTitle.count)
 StandardTitle.all.each do |s|
   c = s.referring_sources.count
-  s.update_attribute( :src_count, c ) if c != s.src_count
+#  s.update_attribute( :src_count, c ) if c != s.src_count
   pb.increment!
 end
 ```

allows the script to finish.  However, it is not clear to me if I have explicitly run:

$ time bundle exec rake sunspot:reindex

Should I? But, even after running it, the records don't appear.  Smaller loads did (the https://github.com/rism-ch/muscat/blob/master/housekeeping/import/sample.xml), or a sample 500 records before, but not a large, 115,561 records.

Where is the problem, in the 01_update_src_count.rb or do I miss something else?

**Comment by fjorba** [comment]
The records that didn't appear was due to a stupid error on the MarcXML controlfield tags.

However, is the 01_update_src_count.rb needed?  After manually running sunspot:reindex (this one as well, has it to be run manually?), the records are searchable.

**Comment by xhero** [comment]
Actually ```src_count``` was removed ages ago... and the script is not needed anymore. Sorry for this! I updated the doc

**Comment by fjorba** [comment]
Thanks!
