### ISSUE TITLE
Cannot use Muscat without signin in

### ISSUE THREAD

**Issue by fjorba** [rism-ch/muscat#787]
When using a local Muscat instance (with RAILS_ENV=development, if that matters), the application insists that the user must be logged in, even for just searching and browsing. As far as I've seen, the cause seems to be here:

https://github.com/rism-ch/muscat/blob/2b96ab061c96a3a30baeb7b924b6b9016de36345/app/controllers/application_controller.rb#L28

As stated in the comments of this file, this is a Blacklight requirement.  However, http://rism-ch.org/ instance allows searching and browsing without being logged in.

Is it possible to implement an anonymous use of Muscat?

**Comment by xhero** [comment]
You just need to comment out that line :)
Maybe it is something I could add to the docs, it is not the first time this question is asked!

**Comment by fjorba** [comment]
Thanks. So, it becomes an _empty_ funcion, like that?

```
--- a/app/controllers/application_controller.rb
+++ b/app/controllers/application_controller.rb
@@ -25,7 +25,7 @@ class ApplicationController < ActionController::Base
   end
 
   def auth_user
-    redirect_to "/admin/login" unless (request.path == "/admin/login" or user_signed_in?)
+    # redirect_to "/admin/login" unless (request.path == "/admin/login" or user_signed_in?)
   end
   
   def test_version_warning
```

In my previous tests (before I opened the issue) I commented out the whole function, and that gave me an error.  Is it correct to leave such an empty function, or the solution should be not to trigger a call to `auth_user` from somewhere else (that I still don't know)?

**Comment by xhero** [comment]
yes the function must be defined but it returns nothing
