### ISSUE TITLE
Display of G clef in incipits

### ISSUE THREAD

**Issue by jenniferward** [rism-ch/muscat#789]
See photos: A RISM contributor and I are both having problems seeing the octave treble clef in Muscat. The 8 isn't visible. Is there a way to increase the space below the clef so that the full clef plus 8 is visible? I have the display problem in both Chrome and Firefox (Win7, desktop).
![image007](https://user-images.githubusercontent.com/18663291/59340420-45178400-8d06-11e9-929a-92a355a4b9c9.jpg)

![image009](https://user-images.githubusercontent.com/18663291/59340431-46e14780-8d06-11e9-8547-6e885055f7a3.jpg)

![image004](https://user-images.githubusercontent.com/18663291/59340432-48127480-8d06-11e9-906a-4aff6f9dba59.jpg)

![image005](https://user-images.githubusercontent.com/18663291/59340433-4943a180-8d06-11e9-911f-6d00c0213c7c.jpg)

**Comment by lpugin** [comment]
@xhero : we probably need to change pageMarginBottom parameter for verovio
