### ISSUE TITLE
Please change column type `marc_source` to mediumtext

### ISSUE THREAD

**Issue by fjorba** [rism-ch/muscat#792]
When loading a particularly long marc bibliographic record (Source) into Muscat, I found this error:

```
Marc Import: Could not save the imported record
Mysql2::Error: Data too long for column 'marc_source' at row 1: INSERT INTO `sources` (`id`, `std_...
```

The error was shown by Mysql2, not by Muscat itself.  Googling around, I think I found the solution changing the current text type into longext or, even better, mediumtext:

https://stackoverflow.com/questions/18897420/data-too-long-for-column-why

According to MariaDB documentation, the three text type limits are:

* 64 Kb Text: https://mariadb.com/kb/en/library/text/
* 16 MB Mediumtext: https://mariadb.com/kb/en/library/mediumtext/
* 4 GB Longtext: https://mariadb.com/kb/en/library/longtext/

In MySQL the limits seem to be the same:

* https://dev.mysql.com/doc/refman/8.0/en/string-type-overview.html

So, most likely a change to Mediumtext would be enough.

I don't know if this change it would be necessary for other Marc types (catalogues, holdings, institutions, people and works),  but maybe it would be useful to keep all them in sync.

Sorry I cannot provide a patch, because I'm still new into Rails.

**Comment by HirschSt** [comment]
The rails datatype for marc_source is "text", see https://github.com/rism-ch/muscat/blob/863abfd3faa2270af653134342561a2a6e0763ef/db/schema.rb#L456. 

"mediumtext" etc. are datatypes specific for Mysql, see https://stackoverflow.com/questions/4443477/rails-3-migration-with-longtext

So we can still extent the limit, but I wonder if a marc record really would be so huge to extent the existing 64k limit.  The biggest entry in RISM with ~ 1.4 million records for now has 35kb. Can we have a look at this giant record?

**Comment by HirschSt** [comment]
BTW according to https://www.loc.gov/marc/specifications/specrecstruc.html the "maximum length of a record is 99999 octets [bytes]".

**Comment by xhero** [comment]
I Agree with @HirschSt on this - 64k is quite a big for the source blob. Could you post the contents of the record?

**Comment by fjorba** [comment]
Not really a musical manuscript (like the ones we have at https://ifmuc.uab.cat/?ln=en), but they do exist in scientific literature, for example:

* https://ddd.uab.cat/record/185284?ln=en
* https://ddd.uab.cat/record/185151?ln=en
* https://ddd.uab.cat/record/115513?ln=en
* and so on...

Yes, I noted that those limitations and datatypes are specific to MariaDB/MySQL, but we have faced this limit quite a few times during our tests. At the same time, I understand that Rails tries to be database agnostic, and I have no idea how to deal with it in ActiveRecord (but then, there are MariaDB/MySQL specificities like InnoDB in the schema). But in this case, the limit is real, specially for those huge list of authors in physics literature, and I think that it would be useful to remove it.

**Comment by HirschSt** [comment]
Thanks a lot for this background information. Sorry for being not clear enough: I just would like to check the record where your import crashes.

**Comment by xhero** [comment]
You can quite easily change the column type with an ALTER TABLE, or you can add it to a migration. But I'm not sure what could be the performance impact if we did that too for the RISM data

**Comment by xhero** [comment]
You can quite easily change the column type with an ALTER TABLE, or you can add it to a migration. But I'm not sure what could be the performance impact if we did that too for the RISM data

**Comment by fjorba** [comment]
Thanks for the suggestions. However, I doubt that it could impact the performance, because, according to the (MySQL) documentation, it just adds a byte to the already existing byte that indicates the number of bytes in the value. And converting it to mediumtext would make Muscat definitively more flexible and capable, should the need arise, wouldn't it?

**Comment by fjorba** [comment]
> BTW according to https://www.loc.gov/marc/specifications/specrecstruc.html the "maximum length of a record is 99999 octets [bytes]".

Yes, but this maximum length is for the iso2709 structure, that reserves the fist 5 bytes to store the length of the record. This structure was designed in the late sixties for exchange in computer tapes and probably nobody is using it for this purpose (I did that, and in the office I still have tapes with Marc records in iso2709, but just for nostalgia). It should't affect other ways to express (or exchange) Marc21 records, like MarcXML or any other sytax, like JSON, or internal representations.

**Comment by HirschSt** [comment]
@fjorba maybe you can give us access to the record where your import crashes?

**Comment by xhero** [comment]
I'm not contrary _per se_ to change the field type, but we have almost 1.8M records using that field, and before changing something that could have a serious impact I would prefer to toughly test it.

**Comment by fjorba** [comment]
> @fjorba maybe you can give us access to the record where your import crashes?

Sure, just append /export/xm to the sample urls I gave before, for example:

* https://ddd.uab.cat/record/185284/export/xm
* https://ddd.uab.cat/record/185151/export/xm
* https://ddd.uab.cat/record/115513/export/xm
* https://ddd.uab.cat/record/204463/export/xm

(Not unlike adding .marcxml in Muscat, by the way...)

Or, in general, there are links to different export formats at the bottom right of the record

**Comment by HirschSt** [comment]
@xhero Yes! I think performance impact means especially parsing, resolving dependencies, indexing and validating of the muscat record.

**Comment by HirschSt** [comment]
@fjorba thanks a lot! Just to be sure: these records are not RISM related, correct?

**Comment by fjorba** [comment]
> I'm not contrary _per se_ to change the field type, but we have almost 1.8M records using that field, and before changing something that could have a serious impact I would prefer to toughly test it.

I understand, but it seems to me that `marc_source` is just a blob, in the sense that it gets retrieved by Muscat when displaying (or editing) a full record. Adding a second (length) byte in MariaDB (or MySQL) internal representation is something very internal to MariaDB, and we should trust their technical capabilities about how they efficiently implement it. In theory, as Rails allows it, this should be not a problem with other database managers (say, SQLite or PostgreSQL).

**Comment by fjorba** [comment]
> @fjorba thanks a lot! Just to be sure: these records are not RISM related, correct?

No, they are not. We are evaluating Muscat to not only for https://ifmuc.uab.cat, but also for other systems we have. And yes, we know that your main concern is RISM's concerns, that is, musical sources.

**Comment by fjorba** [comment]
> @xhero Yes! I think performance impact means especially parsing, resolving dependencies, indexing and validating of the muscat record.

I dont't think so. I understand that is just a matter of how MariaDB/MySQL server saves the data or performs the SELECT statement. I'd say that it should not affect Muscat per se.

**Comment by xhero** [comment]
Now that I saw the record I recalled that years ago we had the same problem in another muscat system that used huge blobs of text and we alter-tabled them to longtext.

I think at this point the best solution if you want to test longtexts is to manually change the marc_source filed after the migration is performed, I would also be curious to see what happens.
In theory it should work without problems, but in practice experience tells me that small modifications can come with big unforeseen issues (sometimes even in quite seemingly unrelated areas), and we had quite a few when optimizing the database store.
If then this works as is tested, we can possibly include a hard migration in one of the next releases.

**Comment by fjorba** [comment]
Ok, I'll experiment; however, measuring performance is not an obvious science, it is certainly tricky, and it is nothing I have special experience with.  However, my impression is that, as `marc_source` does not belong to any index, nor, as such, it does not belong to any relation, it is just a blob that gets retrieved.  Moreover, only when viewing full records, as (if I understand it correctly) brief records come straight from Solr results; I cannot see how this change could affect Muscat.

Anyway, do we leave this issue open?

**Comment by fjorba** [comment]
Sorry, @xhero, but could you explain why have you closed the issue without a patch nor an explanation?  For me, the problem still exist, and the solution is viable; unfortunately, I'm still not able to provide a patch.

**Comment by xhero** [comment]
So, if I push this in a migration, it means all my productions systems will change with it upon installation, and it is not something that right now is on our list to do.
If you need to have bigger marc_sources, can you try running:

```sql
ALTER TABLE sources MODIFY marc_source LONGTEXT;
```

This will change it, and since we normally do not modify `marc_source` it should be permanent in your system. If you need to enlarge other data, you can run it too for them:

```sql
ALTER TABLE people MODIFY marc_source LONGTEXT;
ALTER TABLE institutions MODIFY marc_source LONGTEXT;
ALTER TABLE people MODIFY marc_source LONGTEXT;
ALTER TABLE holdings MODIFY marc_source LONGTEXT;
ALTER TABLE works MODIFY marc_source LONGTEXT;
```

I can pack these in a migrations, but it will be the same thing if you run them my hand.

**Comment by fjorba** [comment]
Thanks, @xhero.  I understand and respect your priorities.  However, I think that MEDIUMTEXT is more than enough; no need for LONGTEXT, not even for particle physics records.
