### ISSUE TITLE
Export of sources throws "unknown record type 11"

### ISSUE THREAD

**Issue by HirschSt** [rism-ch/muscat#793]
see https://github.com/rism-ch/muscat/blob/863abfd3faa2270af653134342561a2a6e0763ef/lib/marc_source.rb#L403, resulting in an empty leader, see 
```xml
<marc:record>
<marc:leader/>
<marc:controlfield tag="001">1001074052</marc:controlfield>
<marc:controlfield tag="003">DE-633</marc:controlfield>
<marc:controlfield tag="005">20190617100623.0</marc:controlfield>
```

**Comment by xhero** [comment]
We need to make the correct leader for composite volumes

**Comment by xhero** [comment]
In case, we can fix the leader from 'pc'
