### ISSUE TITLE
Authority Institution, Type of institution (368), German version

### ISSUE THREAD

**Issue by Docudoctor** [rism-ch/muscat#800]
Add to the list following terms in alphabetical order:

- Dokumentationszentrum
- Druckerei
- Forschungsinstitut
- Museum

**Comment by HirschSt** [comment]
@Docudoctor I need english terms too

**Comment by HirschSt** [comment]
done with https://github.com/rism-ch/muscat/commit/6b9747af41eba46efa23b474e78be1acc065fe47

**Comment by Docudoctor** [comment]
> 
> 
> @Docudoctor I need english terms too

The English terms are:  Documentation centre – Printer - Research institute - Museum

**Comment by Docudoctor** [comment]
> 
> 
> @Docudoctor I need english terms too

See also ticket #799
