### ISSUE TITLE
Add fields to composite template

### ISSUE THREAD

**Issue by HirschSt** [rism-ch/muscat#806]
Watermark is missing, and there are 2 fields in Material that we don't need. Can this be changed?

#MATERIAL
-delete 500
-delete 856
-add 592

followup to #730

**Comment by jenniferward** [comment]
Please delete the "+ add a group" function.

Please adjust the Pflichtfelder: only 852 $a, $c; 245 $a, 240 $a

**Comment by HirschSt** [comment]
- [ ] add 592 watermark
- [ ] change validation
- [ ] remove "add a group" button

500 and 856 are also part of the global source configuration of composite, so I didn't find an easy way to exclude them only from the material group. Any ideas?
