### ISSUE TITLE
593 in Holdings should only have 2 options 

### ISSUE THREAD

**Issue by jenniferward** [rism-ch/muscat#811]
See #735
I think the 593 in the Holdings should only have two options: 
-Print with autograph annotations
-Print with non-autograph annotations

If the item is "Print", "Libretto, printed", or "Treatise, printed", this information will go in the main bibliographic record. I don't think there is a reason why someone needs to fill out "Print" in the bib record and then "Print" again in holdings--is there?

**Comment by xhero** [comment]
So it is not tragic:

```
Other
Print
Print with autograph annotations
Print with non-autograph annotations
```

I'm going to remove the others before more damage is done, then we can decide what to do with "print" and "other"
