### ISSUE TITLE
Content description of composite with 774 

### ISSUE THREAD

**Issue by HirschSt** [rism-ch/muscat#814]
Actual the content description of a composite sounds like this (https://muscat.rism.info/admin/sources/550503237):

```xml
<marc:datafield tag="774" ind1="0" ind2=" ">
  <marc:subfield code="w">550503238</marc:subfield>
</marc:datafield>
<marc:datafield tag="774" ind1="1" ind2="8">
  <marc:subfield code="w">317039</marc:subfield>
  <marc:subfield code="4">holding</marc:subfield>
</marc:datafield>
```
So the last node gives in $w the ID of the **holding** entry with relator "holding" in $4. All this dereference is done then in the view https://github.com/rism-ch/muscat/blob/863abfd3faa2270af653134342561a2a6e0763ef/app/views/marc_show/_show_774_773_links.html.erb#L29

But the **internal** holding-ID is not and should not be accessible outside the connected edition

Proposal:
If we do not want to change the marc-configuration: in 774$w should contain the ID of the edition (_most important for BSB OPAC_), in 77$4 indicator with holding ID, eg:

```xml
<marc:datafield tag="774" ind1="0" ind2=" ">
  <marc:subfield code="w">550503238</marc:subfield>
</marc:datafield>
<marc:datafield tag="774" ind1="1" ind2="8">
  <marc:subfield code="w">992006916</marc:subfield>
  <marc:subfield code="4">holding (317039)</marc:subfield>
</marc:datafield>
```

Any ideas or remarks?

**Comment by xhero** [comment]
I'm unsure for the internal format, as for the specifications it should be an internal id directly pointint to the actual item (the holding).
If the export cannot be properly processed in bsb maybe we can patch it in to_external?

**Comment by HirschSt** [comment]
@xhero see it in action at https://beta.rism.info/admin/sources?utf8=%E2%9C%93&q%5Brecord_type_select_with_integer%5D=record_type%3A11&commit=Filtern&order=id_desc with changed internal 

$w here is pointing directly to the edition.id, not to the holding.id - which never resolves, but redirects to the edition

**Comment by lpugin** [comment]
The composite volume definitely contains the holding and not the edition. Fixing this in to_external sounds correct to me. Maybe adding an extra subfield in 774 can be done there?

**Comment by HirschSt** [comment]
IMO this would be a bad solution, since a holding record only exists embedded in a source.  Fixing this with to_external is strange. $w should only contains IDs from sources, not holdings

**Comment by lpugin** [comment]
Maybe the best is to send to the BSB to data as it is with holding as separate records and they can handle as they want. What do you think?

**Comment by HirschSt** [comment]
Just didn't understand: the holdings are already included in the sources export. Here I have a couple of questions: 

1. should we extent the gap between internal and external marc by blowing up to_external-method?
2. should the holdings or ID of Holdings really by used outside of internal? 
3. how are the specifications that an internal id directly should pointing to the actual item (the holding), since the view are reversing this process by pointing to the source, not the holding?

I think -aside from questions of design - it's mainly the question if a holding is an independent item or not.

If we stay with the current export, I think a solution would be that BSB could parse the xml and make a hash with holding - source references - crazy, but not impossible.

**Comment by xhero** [comment]
But the holding _is_ a separate entity...? It is even expressed with its own model.
With the current setup, it behaves exactly as any other linked data into Muscat. Since the holding represent the physical object, it is that that gets linked to a composite volume. And through the linking mechanism in Muscat this is all automatically resolved. If you look at the item list in the composite page, the link is to the print bibliographical object but it also says "through Holding xxxx", because the link to the print bib record is through the holding. This comes from the requirements of this design and this is why it is implemented with $4holding.
Putting the print source id in the 774 would be redundant, since in Muscat, that value is embedded in the resolved holding record.
I also don't completely understand the BSB issue at hand. This link behaves exactly as any other link in muscat, they surely can resolve back to people or catalogues for example?
I think the data in Muscat should be kept consistent with our data model.

**Comment by lpugin** [comment]
> I think -aside from questions of design - it's mainly the question if a holding is an independent item or not.

Indeed. And I think it is an independent item.

I agree it would be best to have to_external doing as little transformation as possible. Ideally nothing.

**Comment by HirschSt** [comment]
Ok, thanks, we disagree on this. For now I will adjust the export-script https://github.com/rism-international/muscat-maintenance/blob/master/export/sources_to_bsb.rb to resolve the IDs to sources, but it would be good if we could fix this later by changing the to_external or whatever if we add an OAI interface - so it's postponed from my side.
