### ISSUE TITLE
Finalize experimental ttl export

### ISSUE THREAD

**Issue by lpugin** [rism-ch/muscat#822]
- [x] Change pae:key to pae:keysig
- [x] Change pae:time to pae:timesig
- [ ] Add to .ttl response for sources
- [x] Add Themefinder namespace and fields (http://www.themefinder.org/help/)
- [x] Change base url to demo.muscat-project.org
- [x] Run Blazegraph on sparql.muscat-project.org
- [ ] Export basic authority files (people in priority)

**Comment by xhero** [comment]
I think we have all the basic stuff here, I would make specific tickets for the next steps.
