### ISSUE TITLE
852 $z data from Muscat2 cleanup

### ISSUE THREAD

**Issue by jenniferward** [rism-ch/muscat#823]
In Muscat2 we entered some information in a certain field (possibly the non-public note??) that became 852 $z (Provenance) in Muscat. As a result, there are some records (ca. 1700 in PL-Kj alone) that have "General note"-type and other information in the Provenance field. 

Examples:
Title page transcription: 990010828: ALTO | PRIMO CHORO | LI DILLETTEVOLI | MAGNIFICAT | [...]
General note: 1000000347: At the beginning of Cantus - handwritten title page.
General note: 990002559: complete
Provenance note (561): 1000000244: Ex libris: "Ex   Bibliotheca Poelchaviana".
URLs (Digital copies/bib records?) 990002531: http://www.bibliotecamusica.it/cmbm/scripts/gaspari/scheda.asp?id=3740

In the new OPAC release, the info in the 852 $z will be displayed as "Provenance," which will be confusing for the users.

How can we go about cleaning this field up?

**Comment by jenniferward** [comment]
In records from D-Mbs they also entered information in Muscat2 in a single field but in the format "Signatur:  " and "Umfang: ", which is now in 852 $q.

Examples: 
991021545 Signatur: Mus. th. 7323 Umfang: 16p. p. 14-16: VI. Leichte Stücke [für 2 fl] 
991015195 Signatur: 4 Mus. pr. 65070, Beibd. 1 Kopftitel, S. 2: THE FAIRIES | J: W: Callcott. M: B. Price 1. Umfang: 4 S. (S. 1 leer) Beginn: Mark the merry elves of fairy land
990069811: Signatur: 4 Mus. pr. 66039 St.: v und pf Umfang: 35p.

**Comment by xhero** [comment]
This should be quite easy to do, do you have a list?

**Comment by jenniferward** [comment]
I will correct this. I have a list. (Sorry, I don't remember why I made a ticket for this.)
