### ISSUE TITLE
031 $d autocomplete

### ISSUE THREAD

**Issue by cgueggi** [rism-ch/muscat#824]
For the wishlist: Would it be possible to create an autocomplete tool in the "title of movement, text" field which is built from the index (analogous to e.g. text 031 $t)? There are often the same titles (e.g. Kyrie etc.) or tempo indications (e.g. Moderato etc.). An autocomplete tool would make work a little bit easier.

**Comment by xhero** [comment]
031d_sms needs to be stored for this
