### ISSUE TITLE
Change "Table of content" to "Table of contents"

### ISSUE THREAD

**Issue by jenniferward** [rism-ch/muscat#827]
Please change the heading here to: Table of contents
https://muscat.rism.info/admin/guidelines?locale=en
![image](https://user-images.githubusercontent.com/18663291/63750619-142f0000-c8ae-11e9-9b68-4c44b1a46c05.png)

**Comment by HirschSt** [comment]
already done with https://github.com/rism-ch/muscat/commit/8111371448ff93b3237998c3512ebfba616d8226
