### ISSUE TITLE
Reorder images in a record

### ISSUE THREAD

**Issue by jenniferward** [rism-ch/muscat#835]
From an old wish list: The ability to reorder images attached to a record is desirable.

**Comment by lpugin** [comment]
I think this will not be straightforward. Could you provide some examples where this would be relevant?

**Comment by jenniferward** [comment]
An example would be if someone adds
-watermark 2
-image of cover
-watermark 1

then wants to reorder it so it goes cover, watermark 1, watermark 2.

I'll admit I haven't heard this wish since a very old workshop.

**Comment by lpugin** [comment]
OK. I think we can make sure the images are displayed in the ordered they are entered. As I said, allowing for them to be re-ordered is probably tricky.

**Comment by jenniferward** [comment]
OK, good to know that it is tricky (for future reference). I will add something to the guidelines so others know that images are displayed in the order they are entered - maybe obvious, but having the confirmation is good.
