### ISSUE TITLE
Publish Secondary Literature fields in the guidelines

### ISSUE THREAD

**Issue by jenniferward** [rism-ch/muscat#839]
In the guidelines here
https://muscat.rism.info/admin/guidelines
I don't see the following fields for the Secondary Literature:
210  (catalogue_210)
250 (catalogue_250)
502 (catalogue_502)

Can they be published on that page?

**Comment by HirschSt** [comment]
done with https://github.com/rism-ch/muscat/commit/0754308fd31fe566d7b52075f3a6ca09ff3e0ed3
