### ISSUE TITLE
How to create a new template?

### ISSUE THREAD

**Issue by fjorba** [rism-ch/muscat#843]
I'd like to create a new template for a different document type in Muscat.  I've find a few places where I there are files that I should work on, but I think that I better ask.

Is there a guide about creating a new template?  Or could you please give me some hints?

**Comment by fjorba** [comment]
Hi, I've tried to create a simple author-title-year form from scratch, but it is quite hard, and I haven't succeeded much beyond having it appear in the forms list.  Regarding the form itself, it seems that there are quite a few things that are not obvious, at least to me.

May I have a friendly hand to help me in that purpose, please?  Thanks.

I'm attaching my current version of the patch.

```
diff --git a/config/editor_profiles/default/configurations/SourceLayoutDefault.yml b/config/editor_profiles/default/configurations/SourceLayoutDefault.yml
index c8e3c37c..32729429 100644
--- a/config/editor_profiles/default/configurations/SourceLayoutDefault.yml
+++ b/config/editor_profiles/default/configurations/SourceLayoutDefault.yml
@@ -142,7 +142,34 @@ tag_exclude:
   - '773'
   - '775'
   - '787'
-
+simple_form:
+  - '026'
+  - '028'
+  - '033'
+  - '041'
+  - '100'
+  - '383'
+  - '510'
+  - '518'
+  - '546'
+  - '588'
+  - '590'
+  - '592'
+  - '594'
+  - '595'
+  - '596'
+  - '597'
+  - '598'
+  - '650'
+  - '651'
+  - '657'
+  - '690'
+  - '740'
+  - '773'
+  - '775'
+  - '787'
+  - '852'
+  
 tag_exclude_with_holdings:
   collection:
   - '506'
@@ -151,7 +178,7 @@ tag_exclude_with_holdings:
   - '591'
   - '773'
   - '852'
-
+  
 groups:
   edit_library:
     all_tags:
diff --git a/config/locales/en.yml b/config/locales/en.yml
index 59839b0f..2f901142 100644
--- a/config/locales/en.yml
+++ b/config/locales/en.yml
@@ -244,6 +244,9 @@ en:
     collection_record_threatise_printed: "Collection record for printed treatises"
     individual_entry_threatise_printed: "Individual entry in a printed treatise collection"
     single_threatise_printed: "Single printed treatise"
+
+    simple_source: "Simple source form"
+    uab_simple_forms: "UAB simple forms"
         
   #################### MENUS
   menu_home: "Home"
diff --git a/config/marc/default/source/090_author_title_year.marc b/config/marc/default/source/090_author_title_year.marc
new file mode 100644
index 00000000..86c58da2
--- /dev/null
+++ b/config/marc/default/source/090_author_title_year.marc
@@ -0,0 +1,4 @@
+=001 __TEMP__
+=100 1#$a
+=245 10$a
+=260 ##$c
diff --git a/config/marc/default/source/template_configuration.yml b/config/marc/default/source/template_configuration.yml
index 23a7ec3d..58848cc2 100644
--- a/config/marc/default/source/template_configuration.yml
+++ b/config/marc/default/source/template_configuration.yml
@@ -57,6 +57,10 @@ display:
     composite_volume:
       record_type: composite_volume
 
+  uab_simple_forms:
+    simple_source:
+      record_type: author_title_year
+
 default_mapping:
   collection: "000_collection"
   source: "002_source"
@@ -69,3 +73,4 @@ default_mapping:
   libretto_edition_content: "015_libretto_edition"
   theoretica_edition_content: "017_theoretica_edition"
   composite_volume: "019_composite"
+  author_title_year: "090_author_title_year"
diff --git a/lib/marc_source.rb b/lib/marc_source.rb
index 3edf3457..ebaf8e63 100644
--- a/lib/marc_source.rb
+++ b/lib/marc_source.rb
@@ -14,6 +14,7 @@ class MarcSource < Marc
     libretto_edition_content: 9,
     theoretica_edition_content: 10,
     composite_volume: 11,
+    simple_source: 12,
   }
   
   RECORD_TYPE_ORDER = [
@@ -28,6 +29,7 @@ class MarcSource < Marc
     :libretto_edition_content,
     :theoretica_edition_content,
     :composite_volume,
+    :simple_source,
     :unspecified
   ]
 
```

**Comment by xhero** [comment]
Hi! I have not yet tried to apply your patch (will do ASAP), but it seems all ok from reading it.
With appear in the forms list you mean when you create a new record? What happens when you create a record with that template?

Configuring the Editor can be a bit more tricky. SourceLayoutDefault and SourceLayoutShow + SourceFormOption select what to show in the editor (LayoutDefault and FormOptions) and the "show" page (LayoutShow). FormOptions configures the editing properties of each tag, then the "Layout" file selects if it should be shown or not. This is configured with "group_exclude" in the LayoutDefault file. For example a composite volume excludes works and incipits:

```
group_exclude:
[snip]
  composite_volume:
  - edit_incipits
  - edit_works
```

The idea behind this is that in Muscat records normally share the majority of marc tags, except for some that should not be present (a composite volume must not have musical incipits)

**Comment by fjorba** [comment]
What happens is that the form that appears on the screen starts with a *There are ungrouped fields in this record* and has a long list of Marc21 fields, instead of the minimal 100, 245 and 260 that was intended.

May I ask: as there is this https://github.com/rism-ch/muscat/tree/master/config/marc/default directory, would you reccommend us to start with a directory something different of this default?  Something like muscat_repository, for example?

Would this different-than-default-marc activated changing the value of the variable MARC in config/application.rb (as exemplified https://github.com/rism-ch/muscat/blob/master/config/sample_application.rb), right?

At this moment we are still evaluating.  What would be less costly? (Again, we are still Ruby on Rails newbies)

**Comment by fjorba** [comment]
Could you please refer us to commit where a new form is created, so we which files are modified to create a new form?  With no documentation is difficult to guess the right file and the right place.  Thanks

**Comment by fjorba** [comment]
As I think that I'm starting to understand how it works, I close this issue and I'll ask help for more specific questions.
