### ISSUE TITLE
Add transposed modes in PT to 031, 240

### ISSUE THREAD

**Issue by jenniferward** [rism-ch/muscat#845]
Is it possible to add the transposed modes to the 031 and 240, as in #791? (I do not see this area in the yml file I am working with.)

Modos eclesiásticos ocidentais
1tt = pt: "Modo:  1º tom (Dórico), transposto"
2tt = pt: "Modo: 2º tom (Hipodórico), transposto"
3tt = pt: "Modo:  3º tom (Frígio), transposto"
4tt = pt: "Modo:  4º tom (Hipofrígio), transposto"
5tt = pt: "Modo:  5º tom (Lídio), transposto"
6tt = pt: "Modo:  6º tom (Hipolídio), transposto"
7tt = pt: "Modo:  7º tom (Mixolídio), transposto"
8tt = pt: "Modo:  8º tom (Hipomixolídio), transposto"
9tt = pt: "Modo:  9º tom (Eólio), transposto"
10tt = pt: "Modo:  10º tom (Hipoeólio), transposto"
11tt = pt: "Modo:  11º tom (Jônio), transposto"
12tt = pt: "Modo:  12º modo (Hipojônio), transposto"

**Comment by xhero** [comment]
Done in 6.1!
