### ISSUE TITLE
mutliple meters

### ISSUE THREAD

**Issue by rettinghaus** [rism-ch/muscat#853]
In [this record](https://opac.rism.info/search?id=240004132&View=rism) there are in the first and last movement two meters encoded. Is this actually allowed? If not, it would be good if Muscat could check these entries. 
If it is allowed, then Verovio probably should handle it somehow.

**Comment by rettinghaus** [comment]
In [this one](https://opac.rism.info/search?id=301003972&View=rism) there are up to three meters entered.

**Comment by lpugin** [comment]
> Two meters encoded. Is this actually allowed?

No this should not be there. As always, we have to deal with old data, and trying to improve existing incipits is on the map. Thanks for reporting these cases.
