### ISSUE TITLE
guidelines: disable "Tag" field for other translations

### ISSUE THREAD

**Issue by jenniferward** [rism-ch/muscat#864]
Currently any guidelines editor can edit the field "Tag" on guidelines.rism.info when editing a document. Can this field be grayed out? It it not necessary for anyone other than the Central Office to change this field.

![image](https://user-images.githubusercontent.com/18663291/69638561-39710d00-105b-11ea-8c9c-7a6843a03b31.png)

**Comment by HirschSt** [comment]
This is related to the guidelines editor https://github.com/rism-international/rism_guidelines_editor/tree/3.4.0-editor-app/app, not to muscat. New issue at  https://github.com/rism-international/tasks/issues/720
