### ISSUE TITLE
Change 710 $4 asn to oth

### ISSUE THREAD

**Issue by jenniferward** [rism-ch/muscat#867]
There are some records where "oth" or "other function" in 710 $4 was removed and "asn" replaced it. These should all be "oth".

See my comment (17 April) here where I first pointed this out: #737 

Example:
https://muscat.rism.info/admin/sources/1001044930 , US-BETm needs to have "oth" rather than "asn"

**Comment by xhero** [comment]
Do you have a list of these? Are the all holdings?

**Comment by jenniferward** [comment]
I don't have a list per se. Yes, it is holdings only.

**Comment by jenniferward** [comment]
But wait, now I see "Associated name" in the holdings anyways? I guess that was added in #943 - so maybe this is all moot!

**Comment by xhero** [comment]
Sincerely I lost track about "oth" and "asn"...

**Comment by jenniferward** [comment]
Me too ... let's forget this!
