### ISSUE TITLE
Rethink data publication workflow

### ISSUE THREAD

**Issue by lpugin** [rism-ch/muscat#87]
In Muscat 2.0, new foreign (authority) data remain unpublished unless explicitly published, even if the source attached is published. We should probably keep new data unpublished when created but make them published once related sources are published.

**Comment by lpugin** [comment]
@xhero: we need to have the all items published by default, then we can close this ticket

**Comment by lpugin** [comment]
@xhero I guess this is now fixed with the wf_stage preference, isn't it?

**Comment by xhero** [comment]
Yes! closing
