### ISSUE TITLE
log directory missing in Muscat 6.0

### ISSUE THREAD

**Issue by fjorba** [rism-ch/muscat#872]
Hello,

when installing Muscat 6.0, the following error appears:

```
$ bundle exec rake db:migrate 
rake aborted!
Errno::ENOENT: No such file or directory @ rb_sysopen - log/development.log
```
Creating the log dir solves it.  Sorry I cannot suggest a patch or solution to be included in the distribution.

```
~/download/muscat/muscat-6.0$ mkdir log
~/download/muscat/muscat-6.0$ bundle exec rake db:migrate 
~/download/muscat/muscat-6.0$ 
```

**Comment by HirschSt** [comment]
its due to https://github.com/rism-ch/muscat/blob/87b9deb245627489a3d889112668afda24ff1d3e/.gitignore#L6

therfore the log directory is not included in the repository. It could be fixed by allowing the folder, but not it's content in .gitignore

**Comment by fjorba** [comment]
This bug still appears in 6.1.
