### ISSUE TITLE
Duplicate "master" tags

### ISSUE THREAD

**Issue by xhero** [rism-ch/muscat#876]
This is a two fold problem, in data and editor mode.
In the data, this sometimes happens:
```
=240  ##$aConcertos$aConcertos$aConcertos$rE $rA $rE$05188801
```
Note the tripicate `$a Concertos`. This is innocuous in the data per se, but when opened in the editor these fields cannot be removed because the mess up validation. This must be fixed.
See the complete list for the records.
[records_with_duplicate_master_tags.txt](https://github.com/rism-ch/muscat/files/4064374/records_with_duplicate_master_tags.txt)

**Comment by HirschSt** [comment]
I will prepare a maintenance script. IMO it would be sufficient to leave the first $a-Subfield and to copy the others to 599$a something like: 

`Marc 700$a with additional subfield '{content; content}'"`

Any comments?

**Comment by xhero** [comment]
In the records I saw they were all the same, I think we can safely delete them. A better way would be to remove completely, reopen and resave the record to pull the current value from the authority file.

**Comment by HirschSt** [comment]
Fine, so the duplicate sf can be deleted. Exchanging the node by recreating it is ok with me too

**Comment by HirschSt** [comment]
done with https://github.com/rism-international/muscat-maintenance/commit/eca401b1f5afdf178db9b29cadde1e52116f69c0
