### ISSUE TITLE
Various validation requirements

### ISSUE THREAD

**Issue by lpugin** [rism-ch/muscat#88]
- validate 594
- validate presence/absence of link to to collection in collection/non-collection items

**Comment by lpugin** [comment]
The problem with 3.5.0 is that we have data that actually will not validate. For example: a title without scoring. @HirschSt what shall we do for this? Shall we add [unspecified] to all 240 $m? Are there any other known cases? 852 without shelfmark?

**Comment by HirschSt** [comment]
I think we should not change this fields to fulfill validation; would it be possible to have validation rules according to their context (eg migrated record can have empty 240$m, but not a new record)?

**Comment by xhero** [comment]
I don't think we can distinguish from easily from imported / new during editing. The ideal case is that the data is correct and validation rules follow the actual data.

**Comment by lpugin** [comment]
My proposal is to have a checkbox showing up when the record is not valid that can be checked for by-passing the validation. Eventually we will use this only for warnings but having two levels (errors and warnings) is too much of a change for 3.5.0. OK?

**Comment by HirschSt** [comment]
@lpugin yes, good solution!

**Comment by xhero** [comment]
Ok I will proceed to the implementation :)

**Comment by xhero** [comment]
Added in af965bd4. I would make a ticket for the final system.
