### ISSUE TITLE
Bad gateway 502 with logger -> assets not loaded

### ISSUE THREAD

**Issue by HirschSt** [rism-ch/muscat#883]
nginx.log:
App 17142 output: [ 2020-01-21 09:58:09.5719 17142/0x00000005494170(Worker 1) utils.rb ]: *** Exception NoMethodError in Rack application object (undefined method `silence' for #<Logger:0x000000068dfb20>) (process 17142, thread 0x00000005494170(Worker 1)):
App 17142 output:       from /home/dev/.rvm/gems/ruby-2.4.1/gems/sprockets-rails-3.2.1/lib/sprockets/rails/quiet_assets.rb:11:in `call'
[ W 2020-01-21 09:58:09.5720 16915/Te age/Cor/Con/InternalUtils.cpp:96 ]: [Client 4-32] Sending 502 response: application did not send a complete response
App 17142 output:       from /home/dev/.rvm/gems/ruby-2.4.1/gems/actionpack-5.1.7/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
App 17142 output:       from /home/dev/.rvm/gems/ruby-2.4.1/gems/request_store-1.4.1/lib/request_store/middleware.rb:19:in `call'
App 17142 output:       from /home/dev/.rvm/gems/ruby-2.4.1/gems/actionpack-5.1.7/lib/action_dispatch/middleware/request_id.rb:25:in `call'
App 17142 output:       from /home/dev/.rvm/gems/ruby-2.4.1/gems/rack-2.1.1/lib/rack/method_override.rb:24:in `call'
App 17142 output:       from /home/dev/.rvm/gems/ruby-2.4.1/gems/rack-2.1.1/lib/rack/runtime.rb:24:in `call'
App 17142 output:       from /home/dev/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.7/lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
App 17142 output:       from /home/dev/.rvm/gems/ruby-2.4.1/gems/actionpack-5.1.7/lib/action_dispatch/middleware/executor.rb:12:in `call'
App 17142 output:       from /home/dev/.rvm/gems/ruby-2.4.1/gems/actionpack-5.1.7/lib/action_dispatch/middleware/static.rb:125:in `call'
App 17142 output:       from /home/dev/.rvm/gems/ruby-2.4.1/gems/rack-2.1.1/lib/rack/sendfile.rb:113:in `call'
App 17142 output:       from /home/dev/.rvm/gems/ruby-2.4.1/gems/railties-5.1.7/lib/rails/engine.rb:522:in `call'
App 17142 output:       from /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
App 17142 output:       from /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:149:in `accept_and_process_next_request'
App 17142 output:       from /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
App 17142 output:       from /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:415:in `block (3 levels) in start_threads'
App 17142 output:       from /usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'

**Comment by HirschSt** [comment]
possible fix:

replace Logger. new with ActiveSupportLogger.new in https://github.com/rism-ch/muscat/blob/3461e9a49c92424b0c141dfc900cbef5f6fdd5db/config/environments/development.rb#L56 like in production.log https://github.com/rism-ch/muscat/blob/3461e9a49c92424b0c141dfc900cbef5f6fdd5db/config/environments/production.rb#L82

see
https://github.com/rails/sprockets-rails/issues/376#issuecomment-287560399

**Comment by xhero** [comment]
That was my "fix" to avoid huge log files and it never worked properly :worried:, we can roll it back

**Comment by HirschSt** [comment]
Alas, sorry for that ... 

:grimacing:
---
