### ISSUE TITLE
Mistake in validation while saving printed treatise template

### ISSUE THREAD

**Issue by Docudoctor** [rism-ch/muscat#886]
852 is mistakenly mandatory while saving printed treatise template.
Can you correct this for the new release?
Best,
Guido

![852 mistakenly mandatory in template treatise, printed](https://user-images.githubusercontent.com/26874482/73824437-721b2880-47fa-11ea-946e-91cdc0fa60fe.PNG)

**Comment by HirschSt** [comment]
Yes, I will fix this ASAP

**Comment by HirschSt** [comment]
can be tested on beta as well
