### ISSUE TITLE
Fehlermeldung nach dem Speichern einer Körperschaft

### ISSUE THREAD

**Issue by Docudoctor** [rism-ch/muscat#895]
![Körperschaften Fehlermeldung](https://user-images.githubusercontent.com/26874482/75326679-5647f700-587b-11ea-9d4c-78923d0d5b70.PNG)

Fehlermeldung von heute. Das Sigel konnte überarbeitet und abgespeichert werden.

**Comment by xhero** [comment]
Fixed it, we restated some services this morning.
As a rule of thumb, this is maintenance stuff and does not influence the normal operation of the system. This means that if jobs don't work the main system will not be affected.
