### ISSUE TITLE
Expand autocomplete from 10 to 20 options

### ISSUE THREAD

**Issue by jenniferward** [rism-ch/muscat#899]
In the autocomplete fields: Sometimes 10 isn't enough, especially with names and institutions. It would be nice to have a longer list.

**Comment by HirschSt** [comment]
please give an example

**Comment by jenniferward** [comment]
KV (690)

**Comment by xhero** [comment]
One more thing: we search also in the description (you clearly see it with KV), does it make sense to to it like this or should we constraint the autocomplete to author + short name?

**Comment by xhero** [comment]
you can see it live on muscat-test
