### ISSUE TITLE
Download records from folders

### ISSUE THREAD

**Issue by jenniferward** [rism-ch/muscat#920]
I get this request regularly from users: the ability to download records from a Muscat folder. 

Possibly related to #62

**Comment by lpugin** [comment]
Yes. However, the format is always the question. CSV? Plain text? What do you think users would like to get?

**Comment by jenniferward** [comment]
The librarians want MARCXML. CSV would be useful for Muscat users who need to pull records for non-RISM people.

**Comment by xhero** [comment]
One thing we also need to factor in is the time needed to generate an export. 500 records is almost instantaneous, but if a user requests 20'000 it will take a couple minutes, so we will need to think about something like a "waiting" page.
There was also a ticket regarding just downloading the index of the contents of the folder, is this still valid?

**Comment by jenniferward** [comment]
A couple minutes of waiting is absolutely no problem, if the user gets the records in the end. 

@xhero Which ticket are you referring to?

**Comment by HirschSt** [comment]
IMO a user should receive a mail with a download link after export is finished, so it's sufficient to show a message something like "Executions process started - we send a mail after complete" with a link to the archived xml-export.

**Comment by xhero** [comment]
In which format would you like them? Exported Marc records? For CSV we need to select which fields to include as we do for sources.
