### ISSUE TITLE
Correct leader with collections without subentries

### ISSUE THREAD

**Issue by HirschSt** [rism-ch/muscat#933]
some german: Der Fehler liegt bei der dynamischen to_external Methode https://github.com/rism-ch/muscat/blob/c1a715d45c9d9eec8ac048d2944f0cd2af5c3e57/lib/marc_source.rb#L374:

Hier wird bei Collections zunächst "cc" festgelegt; in der anschliessenden Verzweigung wird dieses zu "dc", wenn bei den Untereinträgen kein Druck vorliegt. Da die von Dir genannten Titel aber keine Untereinträge haben, bleibt das "cc" einfach stehen. 

see https://github.com/rism-international/opac-report/issues/263

**Comment by xhero** [comment]
The code there comes from the times when one could mix prints and manuscripts as 774 in a collection, I think it can be safely amended.
