### ISSUE TITLE
Libretti collections cannot take child records

### ISSUE THREAD

**Issue by jenniferward** [rism-ch/muscat#948]
See https://muscat.rism.info/admin/sources/653001228
A book containing 9 dramas. Each drama is its own record. The individual dramas are linked correctly to the parent record, but the parent record says "unknown fields" for the items in the source (774).
I think "items in this source" (774)  needs to be added to the template.

(This problem does not occur with the collection records for printed treatises.)

**Comment by xhero** [comment]
This gor fixed from the modifications in #949 and #950
