### ISSUE TITLE
Remove "parent record" (773) in template for printed treatise

### ISSUE THREAD

**Issue by jenniferward** [rism-ch/muscat#950]
The template for single printed treatises (not in a collection)
https://muscat.rism.info/admin/sources/new?new_record_type=theoretica_edition
contains a field to link to a parent record (773). I'm sure this is just an oversight because the field is not present in the [similar template for printed libretti](https://muscat.rism.info/admin/sources/new?new_record_type=libretto_edition). Can the 773 be removed?

**Comment by xhero** [comment]
Printed libretto actually _does_ have 773!
I think the two top-level templates should have 774 (link to child) and the *_content ones the 773. Now there is a mixture of 773/774 in a random manner in these templates.

**Comment by xhero** [comment]
(this is related to #949). I removed 773 in both _edition templates and 774 in both _content templates

**Comment by jenniferward** [comment]
Oops, did I mix up my numbers? Hopefully you know what I mean anyways?  Yes - Top-level links to child and content links up via 773.
