### ISSUE TITLE
Remove 740

### ISSUE THREAD

**Issue by jenniferward** [rism-ch/muscat#954]
We retained 740 from RISM CH for imported data only, but since that import is complete, I don't think we need it. As of April 2020, it had only been used in 13 records, all incorrectly (duplicate of text incipit or 240).

I suggest that it be removed from all templates.

**Comment by cgueggi** [comment]
We are just working on it and have a look if there are any adjustments necessary.

**Comment by xhero** [comment]
It only seems to happen in 4 records:
456014812
1001002360
1001026160
1001026341

I will remove 740 for 6.3

**Comment by jenniferward** [comment]
Thanks, I fixed those 4 records - all duplicates of the text incipit.

**Comment by xhero** [comment]
fixed in a2a83ae6f4279ff9badacc7050d72d1881074cec
