### ISSUE TITLE
Secondary literature (Catalogues) not searchable via the Faceted search in Muscat 6.2

### ISSUE THREAD

**Issue by fjorba** [rism-ch/muscat#958]
I've downloaded all RISM catalog files from https://opac.rism.info/main-menu-/kachelmenu/data, extracted catalogues.xml, and uploaded it to a clean Muscat 6.2 instance, using the instructions from https://github.com/rism-ch/muscat/blob/develop/3-%20IMPORT.rdoc:

<pre>
$ rails runner housekeeping/import/import_from_marc.rb catalogues.xml Catalogue
</pre>

Import went right, and tables have been populated accordingly (those folders items are tests of mine, just to check that the functionality was working fine):

<pre>
MariaDB [muscat_development]> select table_name, table_rows from information_schema.tables where table_schema = 'muscat_development' order by table_name;

+--------------------------------+------------+
| table_name                     | table_rows |
+--------------------------------+------------+
| active_admin_comments          |          0 |
| ar_internal_metadata           |          1 |
| bookmarks                      |          0 |
| catalogues                     |      42814 |
| catalogues_catalogues          |          0 |
| catalogues_to_catalogues       |       6038 |
| catalogues_to_institutions     |       2603 |
| catalogues_to_people           |      19783 |
| catalogues_to_places           |       2261 |
| catalogues_to_standard_terms   |       2175 |
| crono_jobs                     |          0 |
| delayed_jobs                   |          0 |
| digital_objects                |          0 |
| digital_object_links           |          0 |
| folders                        |          2 |
| folder_items                   |         81 |
| holdings                       |          0 |
| holdings_institutions          |          0 |
| holdings_to_catalogues         |          0 |
| holdings_to_people             |          0 |
| holdings_to_places             |          0 |
| institutions                   |       1345 |
| institutions_institutions      |          0 |
| institutions_to_catalogues     |          0 |
| institutions_to_people         |          0 |
| institutions_to_places         |          0 |
| institutions_to_standard_terms |          0 |
| institutions_users             |          0 |
| institutions_workgroups        |          0 |
| liturgical_feasts              |          0 |
| people                         |       9535 |
| people_to_catalogues           |          0 |
| people_to_institutions         |          0 |
| people_to_people               |          0 |
| people_to_places               |          0 |
| places                         |        724 |
| roles                          |          5 |
| schema_migrations              |         79 |
| searches                       |          6 |
| sources                        |          0 |
| sources_to_catalogues          |          0 |
| sources_to_institutions        |          0 |
| sources_to_liturgical_feasts   |          0 |
| sources_to_people              |          0 |
| sources_to_places              |          0 |
| sources_to_sources             |          0 |
| sources_to_standard_terms      |          0 |
| sources_to_standard_titles     |          0 |
| sources_to_works               |          0 |
| standard_terms                 |        489 |
| standard_titles                |          0 |
| users                          |          2 |
| users_roles                    |          2 |
| users_workgroups               |          0 |
| versions                       |          0 |
| workgroups                     |          0 |
| works                          |          0 |
| works_to_catalogues            |          0 |
| works_to_institutions          |          0 |
| works_to_liturgical_feasts     |          0 |
| works_to_people                |          0 |
| works_to_standard_terms        |          0 |
| works_to_standard_titles       |          0 |
| works_to_works                 |          0 |
| work_incipits                  |          0 |
+--------------------------------+------------+
65 rows in set (0.019 sec)
</pre>

With Solr up and running, I've reindexed the records:

<pre>
$ rails sunspot:reindex
</pre>

Those catalog records are searchable via the Muscat internal Active Admin interface, but not in the public Blacklight faceted search interface.  However, on the public RISM opac, they are searchable indeed, for example:

https://opac.rism.info/metaopac/search?searchCategories%5B0%5D=-1&q=ifmuc&View=rism&Language=en

Is this a bug or is it intentional, or have I missed something?  Can those record types be publicly searchable in Muscat?  (Although I'm trying, I haven't yet found how.)

**Comment by xhero** [comment]
Unfortunately for the moment only Sources are searchable from the Blacklight interface, and this was dictated by the specific requirements of our project.
It would be probably not too complex to make a dedicated catalog controller for other authority files, or to mix the sources and other items in the existing controller.  You can have a look in the catalog controller: https://github.com/rism-ch/muscat/blob/ab452e62bd4d5faf1f1e7feac62727bcd67c4b24/app/controllers/catalog_controller.rb#L180

this is where the filtering is done. If you change the type you can get other indexed items. The only caveat is probably making sure all the indexed fields match for the different data types (or you will not be able to see/search items).

**Comment by fjorba** [comment]
Thanks for the hint and advices, I'll work on that.

Out of curiosity, reading from different RISM notes here and there, isn't that right that Muscat (the software) is going to replace whatever is running now in opac.rism.info? When is this change going to happen?  Because, at least in that case, Catalogues should appear like they do it now.

**Comment by jenniferward** [comment]
It helps to know the context of the secondary literature: it's meant to serve as references in the sources; our project does not aim to make such items discoverable per se. They can be found in the public OPAC through "all fields" search only and we don't offer any other kind of access points for them (i.e., they are excluded from the advanced search and the facets, except for "Indexes"). We really don't try to facilitate the findability of these.

**Comment by xhero** [comment]
Muscat and the OPAC at rism.info are independent, and there is no plan to have the Muscat Blacklight OPAC replacing it. Out of curiosity: where did you read this?

**Comment by fjorba** [comment]
Thanks for the explanation, @jenniferward, it makes sense.  However, in https://opac.rism.info/, those records can be found in the basic search, even as authors, ex:

https://opac.rism.info/metaopac/search?searchCategories%5B0%5D=-1&q=pessarrodona&View=rism&Language=en

This behavior is not possible using unpatched Muscat 6.2, with the same records.  If (when) Muscat replaces the current system, is this restriction going to be acceptable?

**Comment by fjorba** [comment]
> Muscat and the OPAC at rism.info are independent, and there is no plan to have the Muscat Blacklight OPAC replacing it. Out of curiosity: where did you read this?

Clearly I misunderstood, probably because I'm not familiarised with internal names like Kallisto (?), at least here, and I'd say somewhere else, but the idea was the same:

http://www.rism.info/home/newsdetails/article/64/rism-at-iaml-part-1-muscat-almost-ready-to-go.html?tx_ttnews%5Byear%5D=2016&tx_ttnews%5Bmonth%5D=07&cHash=ae85c994f5da10029d7cc4e964172a12 (in the July 2016 archives of http://www.rism.info/home/news-archive.html)

**Comment by jenniferward** [comment]
Right, the basic search searches all fields, so if you enter pessarrodona then the name will be found in our authority files (once as a Personal Name and once in the article by her).
(The fact that Pessarrodona turns up as a "Composer" in the filters must be an error; I'll look into that.)

**Comment by jenniferward** [comment]
Kallisto was the old cataloging program used internally by RISM contributors. Muscat replaced Kallisto.

**Comment by fjorba** [comment]
Ok, I see.  Once upon a time, there was a http://demo.muscat-project.org/, that I discovered in a page in rism.info that I cannot find now, with some demo training accounts and the whole RISM catalog.  This fact reinforced my thought that the current opac system will eventually be replaced by Muscat.

**Comment by xhero** [comment]
wait demo should not be down! But there are no training accounts there, just an example catalog for searching incipits.

**Comment by fjorba** [comment]
You are right, my bad. I confused this address with http://muscat-training.rism.info, found in the pdf slides http://www.rism.info/fileadmin/content/community-content/events/2018_IAML_Leipzig/Ward_Workshop_slides_Leipzig_version.pdf in http://www.rism.info/fr/publications/iaml-congresses/2018.html

**Comment by fjorba** [comment]
Understanding now that it is not a bug, I close this issue, and I'll take some lessons learned for future directions. Thanks.

**Comment by fjorba** [comment]
Done in #1106
