### ISSUE TITLE
New languages in Sources 041

### ISSUE THREAD

**Issue by jenniferward** [rism-ch/muscat#961]
I've come across some language codes in Muscat - probably imported from Kallisto - that aren't officially in the 041 list yet. Could these please be added to 041 $a, $e, and $h in Sources:

arm | Armenian
art | Artificial (Other)
bos | Bosnian
cel | Celtic (Other)
crp | Creoles and Pidgins (Other)
goh | German, Old High (ca. 750-1050)
ice | Icelandic
mao | Maori
per | Persian
tat | Tatar
tha | Thai
xal | Oirat

**Comment by jenniferward** [comment]
Also please: 
tgl | Tagalog

**Comment by fjorba** [comment]
I thought I could contribute with some easy tasks like this one. Please excuse me if there is something wrong with it.

**Comment by jenniferward** [comment]
Oops, with "Artificial (Other)" the wires got crossed (our fault, not yours, @fjorba !) 
EN: Artificial (Other)
ES: Artificial (otros)

I can maybe get PL soon; if so, I will add it here.

**Comment by nifcbff** [comment]
PL: Sztuczny (Inne)

**Comment by xhero** [comment]
Thanks everybody! Do you have German too? is `Künstlich (andere)` ok?

**Comment by MFalletta** [comment]
DE: 
art | Kunstsprache
cel | Keltisch
tat | Tartarisch
xal | Oiratisch
