### ISSUE TITLE
Auf bestimmte Werktitel kann man nicht zugreifen

### ISSUE THREAD

**Issue by MFalletta** [rism-ch/muscat#966]
Die Werktitel https://muscat.rism.info/admin/works/266 bis https://muscat.rism.info/admin/works/257 lassen sich nicht aufrufen.

Die Meldung lautet "The page you were looking for doesn't exist. ...."

In der nummerischen Liste stehen sie aber incl. Verknüpfung mit einer Quelle.
![werktitel](https://user-images.githubusercontent.com/18736235/89808077-da481f80-db39-11ea-9ad9-f5c958ca069b.jpg)

**Comment by DadimoPflege** [comment]
Bei diesen Werken wurde eine Person gelöscht (id: 40220402), als der verbesserte Dependency check noch nicht wirksam war. Die entsprechenden Felder müssen jetzt über ein Wartungsskript entfernt werden.

**Comment by HirschSt** [comment]
done with https://github.com/rism-international/muscat-maintenance/commit/649329dc1ca152a306f2db5a4eb032e5b1047264
