### ISSUE TITLE
"Any field" in Institutions

### ISSUE THREAD

**Issue by jenniferward** [rism-ch/muscat#990]
If you search in Institutions in "Any field" it seems that actually only the field "Name" is searched. Can it be expanded to really search any field?
![image](https://user-images.githubusercontent.com/18663291/94041228-3f926000-fdca-11ea-8466-bece1a9cc172.png)

**Comment by xhero** [comment]
It is actually! I'm not sure why that particular string is not found.

**Comment by xhero** [comment]
This will work in 7, the 680 $a field was added in this release
