### ISSUE TITLE
Add a brief_record column for Sources and Secondary Literature tables

### ISSUE THREAD

**Issue by fjorba** [rism-ch/muscat#991]
Brief records in Muscat currently are very brief indeed, as they only show the composer and the title.  Currently they rely on the fields Solr returns, provided they are indexed with the stored property.  This brief information is often not enough to differenciate between records.  But adding fields to Solr, moreover with this stored property, just to have them displayed in the brief record may not be efficient.

Let me display with and example the difference between a simple author-title and richer records, searching the same author:

* http://www.rism-ch.org/catalog?utf8=%E2%9C%93&locale=en&search_field=composer&q=palestrina
* https://ifmuc.uab.cat/search?sc=1&p=palestrina&f=author&ln=en

A normal user, searching a catalog-like site, forces the display of dozens or hundreds of brief records, so they may be displayed fast, with a minimum of computing overhead.  Most of the systems I've worked with have the brief record pre-formated in a table, so they are just retrieved from there and send to the screen as-is.  With this strategy, in the faceted search (Blacklight) only the record id is needed from Solr, and this id will be used to retrieve the brief record from the database table. (Active record in the internal Muscat work area is not the target of this issue.)

Details of how and when this field is created will be defined in a future issue, but let me advance here some of the basic ideas I have in mind.

Which fields are chosen to this play brief records, and how they are formatted will probably different from site to site, they may change depending on the record type, due to personal criteria, changing opinions or requirements.  In my experience, creating them may require some sophisticatcation, because the how some fields are shown may depend on the existence of another one, or even the number of yet another field.  My experience is that templates are never enough, and they must be completed with a real programming language.  So, I'd leave them to be written in Ruby; I would't even try to create a template.  There should be a default implementation upstream, but may be modified in each instance.  I volunteer to write a first version.

The brief record column should be updated whenever the record is updated, but there should be a command line utility to update them (probably in record subsets) if the brief record definition has changes.

As hopefully there is a database migration in the horizon (#975), I think that it would be a great moment to add this column in both bibliographic records models.  Text type would be enough; medium text is not needed here.

**Comment by xhero** [comment]
You mean the titles displayed in the list results in blacklight? In the discovery interface we don't really have brief records, as only the title is displayed, ad in the cataloguing interface we have a slightly more complex version of it, stored in the database. For our current requirements we don't really need brief records in blacklight, but I think this could actually be very easily be implemented in solr without touching the db, blacklight actually does it by default and we disabled it. I don't think concatenating stored fields has a big performance impact, and in this way we don't need to add another field in the database.

**Comment by fjorba** [comment]
Yes, I mean the list result in Blacklight, right.  I understand that you may now not need it, but I do think that many of the rich information in brief records, like thumbnails, external urls, icons, may not be in Solr.  For example, this display of text documents, images and videos:

https://ddd.uab.cat/search?ln=en&p=covid&sc=1

Each of this record type has slightly different format options.  Those brief records are stored in html in a table, and so the display is fast. Creation takes more time.

If some Muscat instance, like yours, think that this column is not needed, fine, but in other instances I think that the only way to provide those richer brief records, without impacting the performance, is to store them somewhere, and I'd say the obvious way is in an extra column of those two models.

**Comment by xhero** [comment]
Yes but isn't it more easy to construct it in the view? Blacklight does it this way, I don't think the overhead of generating it on the fly is great, and it has the advantage that you can change the visualisation without having to re-save all the documents on the db. Besides, I prefer not to store html in the database.

**Comment by ahankinson** [comment]
@fjorba have you done some benchmarking to quantify the difference in time between storing the records in HTML, and generating them on-the-fly?

**Comment by fjorba** [comment]
I think that it is easier to store it preformatted, but it may well be because it is what I'm used to, and not only with our current repository system, but also with older standard ILS system written in Cobol I worked with in my youth.  Browsing pages of brief records may be slower or faster depending on how many operations you do with your program.  If different people (say, first year students looking for the same information) are performing the same search (or different search with common records), you can avoid resources if those brief records are already precomputed. You can serve them faster and the system performs better.  Call it cache, like Invenio, if you prefer.

I do have a recent benchmark with our current Invenio system.  This weekend I have regenerated our brief records (the public ones and the non-published ones):

```
2020-09-26 16:30:28 --> Querying database for records without cache...                                                               
2020-09-26 16:30:32 --> Records to be processed: 232573                                                                              
2020-09-26 16:30:32 --> Out of it records without existing cache: 0                                                                  
2020-09-26 16:30:37 -->    ... formatted 100 records out of 232573
2020-09-26 16:30:40 -->    ... formatted 200 records out of 232573
...
2020-09-26 17:52:37 -->    ... formatted 232500 records out of 232573
2020-09-26 17:52:38 -->    ... formatted 232573 records out of 232573                                                                
2020-09-26 17:52:38 --> total records processed: 232573
2020-09-26 17:52:38 --> total processing time: 4929.500000 sec
2020-09-26 17:52:38 --> Time spent on external call (os.system):
2020-09-26 17:52:38 -->  bibformat: 4920.500000 sec
2020-09-26 17:52:38 -->  bibupload: 0.000000 sec
2020-09-26 17:52:38 --> Task #424345 finished and resubmitted.
```
Certainly, the time per record is low (0.02 seconds per record), but when running a heavily used system, anything that you can avoid in real time and leave it for batch operations is welcome.

**Comment by ahankinson** [comment]
You would be probably better served by putting a caching system like Varnish or even just the built-in cache in NginX in front of Muscat if you were worried about load, and thereby addressing the actual problem without needing to punt it up to the application layer.

This would have the advantage of automatically caching the whole rendered HTML response, rather than just individual records, and it would automatically refresh the cache periodically, particularly for the use case you give of first-year students looking for the same thing.

If the amount of traffic is a big issue you could also probably put muscat behind some load balancers and have two or more instances serving data. Again, you could use a dedicated solution like HAProxy, or you could use the one built-in to NginX.

**Comment by fjorba** [comment]
I understand that those general-purpose front-end solutions for high-traffic can be complementary to my petition. And I'm not asking that all Muscat instances use those brief_record column. In those cases it would be an empty value.  According to each experience, abilities and infrastructure, it may be easier to install a Varnish, HAProxy pr NginX.  I recognize that I have no experience with any of them. I do know, however, how to format a brief record and how many disc access do I need, either due to database queries or disc accesses.  And I'm sure, from decades of real-world experience, that it works.

Adding those columns in the standard Muscat schema would satisfy those hypothetical users that may prefer this solution, either alone or complementary to the front-end alternatives you have mentioned.  What it is certain is that the way information is presented varies from site to site. Look at the so-many different Blacklight implementations out there to see that there is no single style that fits everybody.  Only DSpace is rigid enough that all instances look the same.  My understanding that this extra flexibility is a good thing.

**Comment by xhero** [comment]
Sincerely I'm a bit perplexed on this, it seems to me it adds more complexity than it saves. For example, if you need to change the display of an item in the title, you will have to resave all the records. And how are translations managed? If we have a label in the blurb, we then must have it in 6 languages, if we change any of these, we must resave everything. All this would be just done with one page reload from the view. I think the right place here is the view not hardcoding this data with formatting in the backend. And the view can be very easily manipulated too. Besides, solr does not really get upset with stored data or with queries to fetch it.

**Comment by fjorba** [comment]
Good point.  Yes, I'm used to reformat all brief records whenever we decide to change the brief format. It is not so often, but probably I see it normal because I'm used to.

About the translations, in general the brief records do not have labels, and in the labels are what is translated in a multilingual site, not the record itself, and records belong to the full record, not the brief one.

I wrote this request because I'm testing Muscat using only Secondary Literature records, and the brief records list appear as:

```
 1. [n.a.]
    [n.a.]

 2. [n.a.]
    [n.a.]

 3. [n.a.]
    [n.a.]

 4. [n.a.]
    [n.a.] 
```

I had played a little bit with the https://github.com/rism-ch/muscat/blob/v6.3.1/app/views/catalog/_index_header_rism_default.erb before, but as I saw that the values shown come from Solr and I need to display some that are not there, I resourced back to what I know.

I'm not familiarised enough with Blacklight and Solr (I've started to study them, but I've had to learn so many things!) to see better alternatives.  I've dived into Blacklight sources to see how to display richer brief records, but I haven't found it yet.

May I know would you recommend store in Solr?  All the brief record fields that I need to display? Or are you suggesting me to store my pre-build brief record in Solr? I still think that if a record is modified once and shown thousands of times without being modified, it is better to built it once and serve it cached.  However, I will not insist more if you think that it is not worthwhile, as you do.

**Comment by fjorba** [comment]
Given that the reception of my proposal has not been seen obviously positive, it may have been a premature optimization.

So I'm closing it as I explore implementing it as alternative format (as a matter of fact, this is how Invenio does it), besides studying if Rails provides caching of complex (computationally speaking) objects like brief records..
