### ISSUE TITLE
Additions to Institutions 

### ISSUE THREAD

**Issue by jenniferward** [rism-ch/muscat#992]
In cooperation with the Series C project group, please add the following to the Institutions:

1.  670: add 
$u (R) URI

2. 510:
Indicators: 2#
Add $w (NR) Control subfield
Drop-down list for $w: 
Code | Term
a | Earlier heading
b | Later heading
d | Acronym
f | Musical composition
g | Broader term
h | Narrower term     
i | Reference instruction phrase in subfield $i     
n | Not applicable    
r I Relationship designation in $i or $4     
t | Immediate parent body

Add $i (R) Relationship information

3. 371: Add 
$s (NR) Start period
$t (NR) End period
$v (R) Source of information 

4. 368: Add
$b (R) Type of jurisdiction
$c (R) Other designation
$2 (NR) Source 

5. 024: Add
$c (NR) Terms of availability
$d (NR) Additional codes following the standard number or code
$q (R) Qualifying information
$z (R) Canceled/invalid standard number or code
$0 (NR) Authority record control number or standard number
$1 (NR) Real World Object URI
$6 (NR) Linkage
$8 (R) Field link and sequence number

6. Add 372 Field of activity (R)
Indicators: ##
$a (R) Field of Activity 
$2 (NR) Source of term

7. Add 370 Associated place (R)
Indicators: ##
$c (R) Associated country
$e (R) Place of residence/headquarters
$f (R) Other associated place
$2 (NR) Source of term

**Comment by xhero** [comment]
For 024
records.authority_record_control_number
records.real_world_object_uri
records.linkage
records.field_link
records.terms_of_availability
records.additional_codes
records.qualifying_information
records.invalid_standard_number

For 368
records.type_of_jurisdiction
records.other_designation
records.source

For 370
records.associated_country
records.place_of_residence
records.other_associated_place
records.source_of_term

For 317
general.start_period
general.end_period
general.source_of_information

For 372
records.field_of_activity
records.source_of_term

For 510
records.relationship_information
records.control_subfield

**Comment by xhero** [comment]
I added all the items, we need to coordinate for the translations. In the comment above there are the keys I used for the Labels, you can change those freely if you want, just update InstitutionLabel. We will need at leat the English translation for those + the Control subfield, which I did not add to the Labels yet.

**Comment by xhero** [comment]
@MFalletta would you mind looking at the German translations for the keys? They are in the https://github.com/rism-digital/translations repo

**Comment by ahankinson** [comment]
Here are the changes with the new additions highlighted: https://github.com/rism-digital/translations/commit/0ec416d0db31d5bc7867b32d2522c4eb664bd53a

**Comment by jenniferward** [comment]
One more we need for this, a local field: 

Field 670: 
$9 Source citation

**Comment by jenniferward** [comment]
Polish: 
Nazwa źródła informacji

**Comment by xhero** [comment]
Only German in missing! :)

**Comment by MFalletta** [comment]
German 670 $9:
Quellenangabe
