### ISSUE TITLE
Problems with SourceLabel translations

### ISSUE THREAD

**Issue by ahankinson** [rism-ch/muscat#996]
There are a few errors and issues with `config/editor_profiles/default/configurations/SourceLabels.yml`. 

1. There are quite a few duplicated language keys, with different values. I'm guessing this is a copy/paste error, where someone copied an existing entry and changed the translation, but did not change the key. For example: https://github.com/rism-ch/muscat/blob/develop/config/editor_profiles/default/configurations/SourceLabels.yml#L78-L85, where there are two `it` translations, and one is probably supposed to be `es`. 
2. Having all the MARC indicator codes in the same level means there are duplicate keys. For example, `art` is used for both "Artist" (as a relator code) and "Artificial" (as a language). See https://github.com/rism-ch/muscat/blob/develop/config/editor_profiles/default/configurations/SourceLabels.yml#L2881 and https://github.com/rism-ch/muscat/blob/develop/config/editor_profiles/default/configurations/SourceLabels.yml#L3372
3. There are duplicate entries for the same codes. For example, `asn` is defined twice, slightly differently: https://github.com/rism-ch/muscat/blob/develop/config/editor_profiles/default/configurations/SourceLabels.yml#L2898, https://github.com/rism-ch/muscat/blob/develop/config/editor_profiles/default/configurations/SourceLabels.yml#L3078. This is also a problem with `ccp`. 

I have gone through and fixed the issues with 1 where I could and have filed a PR for review. Issue 3 will require someone to go through and select the correct translation, and remove the other one. For issue 2 it would benefit from further subdividing the configuration into sections, like `relators:`, `languages:`, etc. to avoid the naming collisions.

**Comment by ahankinson** [comment]
Most of the other label configurations have similar problems. (My code editor highlights the lines with errors, so it may be worth going through with a similar tool to check it. Interestingly, many YAML linting tools do not catch this, but this one does:

https://jsonformatter.org/yaml-validator

**Comment by ahankinson** [comment]
Additionally, some of the keys are in uppercase, e.g. `IT` instead of `it`.

**Comment by lpugin** [comment]
> For issue 2 it would benefit from further subdividing the configuration into sections, like relators:, languages:, etc. to avoid the naming collisions

Maybe another option could be to prefix them. `lang.art` vs `relator.art`?

**Comment by ahankinson** [comment]
In YAML the hierarchy structure parses out to a map / dict / JSON object, so that’s effectively what it’s doing anyway.

**Comment by ahankinson** [comment]
Will be fixed as part of #1004
